### PR TITLE
#6285: Add backward support for floor round and div_no_nan

### PR DESCRIPTION
**Pull request by Aswinmcw**
Add backward support for floor, round and div_no_nan
All post commit test : https://github.com/tenstorrent-metal/tt-metal/actions/runs/8250908197

### CODE REVIEW

**Review by eyonland — CHANGES_REQUESTED** [review]
Where is the requirement from Moreh for the div_no_nan ?

**Comment by Aswinmcw** [comment]
@razorback3 can you please review this PR specifically for the div_no_nan op and give me a suggestion on it, so that i will modify it accordingly?

**Comment by razorback3** [comment]
@Aswinmcw 
I looked through the entire PR. The formula for getting the backward output of div_no_nan is OK.
However, is there any plan to implement backward ops with dedicated kernels rather than using composite ops?

**Comment by Aswinmcw** [comment]
> @Aswinmcw I looked through the entire PR. The formula for getting the backward output of div_no_nan is OK. However, is there any plan to implement backward ops with dedicated kernels rather than using composite ops?

@razorback3 currently we are implementing backward ops using composite ops alone

**Review by eyonland — APPROVED** [review]

**Pull request merged**
