### PR TITLE
#13517: Remove backward relational ops

### LINKED ISSUE #13517: Remove backward relational ops

### PR DESCRIPTION
**Pull request by VirdhatchaniKN**
Work Done : Remove relational ops support for backward ops

CI : https://github.com/tenstorrent/tt-metal/actions/runs/11209987182 - passed

### CODE REVIEW

**Review by Aswinmcw — APPROVED** [review]
LGTM

**Review by mouliraj-mcw — APPROVED** [review]

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11214012269

**Review by eyonland — APPROVED** [review]

**Review by ayerofieiev-tt — APPROVED** [review]

**Review by umadevimcw — APPROVED** [review]

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11240266556 - passed

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11244424391 - passed

**Pull request merged**
