### PR TITLE
Rename the wheel files from metal_libs to `ttnn`

### PR DESCRIPTION
**Pull request by dimitri-tenstorrent**
### Ticket
#15803 

### Problem description

Small clean up before the work of packaging and releasing the wheel to PyPI 

### What's changed
Renamed the project to ttnn and updated the references to the wheel filename as `ttnn`

### Checklist
- [x] Post commit CI passes
https://github.com/tenstorrent/tt-metal/actions/runs/12283866710
- [x] Blackhole Post commit (if applicable)
https://github.com/tenstorrent/tt-metal/actions/runs/12285993698
- [x] Model regression CI testing passes (if applicable)
https://github.com/tenstorrent/tt-metal/actions/runs/12286019337
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) tests passes
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by tt-rkim** [comment]
I like this change, but this will likely fail pipelines. There's some other stuff you'll have to change

Do a fuzzy search in the repo for `metal-libs` or something like that

cc: @ayerofieiev-tt - pls give your feedback as a consuemr

**Comment by dimitri-tenstorrent** [comment]
> I like this change, but this will likely fail pipelines. There's some other stuff you'll have to change
> 
> Do a fuzzy search in the repo for `metal-libs` or something like that
> 
> cc: @ayerofieiev-tt - pls give your feedback as a consuemr

I think I got most instances but I will run the other pipelines before merging.
What is the most comprehensive pipeline that we have?

Do we have any external dependencies that I did not think of?

**Comment by ayerofieiev-tt** [comment]
We have a wheel to let users do `import ttnn` so my take - this wheel must be renamed to `ttnn`.

**Comment by ayerofieiev-tt** [comment]
PyTorch 2.0  project depends on the name, but now that I know that it might be changed - I don't have problems fixing it there. 

There might be a dependency on the Forge side @tapspatel

**Comment by dimitri-tenstorrent** [comment]
> We have a wheel to let users do `import ttnn` so my take - this wheel must be renamed to `ttnn`.

This still happens with the wheel named as `metal_libs`

One big supporting argument for `ttnn` is that `tt-metalium` refers to metal side. (@tt-rkim is that the point you wanted to add as well?)

**Comment by dimitri-tenstorrent** [comment]
@ayerofieiev-tt In our meeting today, we have discussed that the wheel and the project should be named `ttnn` on PyPI and the apt-package (when it is ready) will be called `tt-metalium`

**Review by ayerofieiev-tt — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Pull request merged**
