### PR TITLE
#9305: Add wheel installation instructions

### PR DESCRIPTION
**Pull request by tt-rkim**
### Ticket
https://github.com/tenstorrent/tt-metal/issues/9305

### Problem description
We want to fully enable simpler wheel install.

### What's changed

Added instructions to enable easy Python install.
No code changes.

### Checklist
- [x] Post commit CI passes
- [x] Model regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by tt-rkim** [comment]
@adifrancescoTT @mbahnasTT @Shubhamsaboo @dvartaniansTT 
Easier wheel install Pull request. Pls review and approve.

**Comment by dvartaniansTT** [comment]
@tt-rkim this [link](https://github.com/tenstorrent/tt-metal/releases/tag/v0.48.0) is shared to download the .whl file. but I can't find any whl file there!

**Comment by tt-rkim** [comment]
Pls try again @dvartaniansTT

**Comment by tt-rkim** [comment]
@dvartaniansTT please try the latest instructions on main

**Pull request merged**
