### PR TITLE
#12323: delete ctor of AllGatherFusedOpSignaler

### PR DESCRIPTION
**Pull request by marty1885**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/12323)

### Problem description
Due to the ctor of `AllGatherFusedOpSignaler` is essentially the default constructor. The expression `std::optional<AllGatherFusedOpSignaler> all_gather_fused_op_signaler = AllGatherFusedOpSignaler();` triggers GCC14's uninitialized variable detection.

### What's changed
Delete the default constructor.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by ayerofieiev-tt — APPROVED** [review]

**Review by ayerofieiev-tt — COMMENTED** [review]
Or this constructor has to be removed
```
    MatmulFusedOpSignaler() {}
```

**Comment by marty1885** [comment]
Oops.. forced pushed the wrong commit and GH auto closed the PR. Fixed now.

@ayerofieiev-tt Still compiling on my machine but I think your solution is better.

**Comment by marty1885** [comment]
@tt-rkim I understand TT's difficulties keeping up with new compilers. I also have no problem keep upstreaming these patches when breaks do happen. The last thing I want is maintaining a branch with piles of patches just so I can get tt-metal working on my machine but TT still gotta reinvent the wheel when the next version of Ubuntu released.

Can TT accept these patches as-is and we keep an eye on gcc-12 compatibility?

**Comment by tt-rkim** [comment]
Just running this to be sure: https://github.com/tenstorrent/tt-metal/actions/runs/10775571014

**Comment by tt-rkim** [comment]
And we are okay with that workflow, if you are okay with it

**Comment by marty1885** [comment]
I would prefer if TT can have newer GCC in CI. But welcome to open source where downstream developers will do anything and everything to get their code working. And expect upstream to accept the patches unless there's a good reason not to. Mutual help.

So yes, I'm happy keep upstreaming these fixes if TT doesn't have the resource.

**Comment by tt-rkim** [comment]
Once we get more compute resources, we should be able to support more GCC releases. I'm wondering given the stage we are currently in, if it's worth just upgrading our gcc across the board and requiring 14 or higher.

**Comment by TT-billteng** [comment]
which OS natively supports GCC 14 currently?

**Pull request merged**
