### PR TITLE
Improve Mixtral perf with ttlib

### PR DESCRIPTION
**Pull request by mtairum**
- Changed all ttnn matmuls to ttlib version. 
- Cached lambda functions and memory config. 
- Avoid inheriting torch.nn.module.

Latest measurements at 6.3 t/s/u

python_dispatch_for_inference_0: 28.821ms
model_run_for_inference_0: 140.948ms
end_to_end_inference: 158.247ms

### CODE REVIEW

**Comment by mtairum** [comment]
FIY @sraizada-tt

**Review by boris-drazic — APPROVED** [review]

**Comment by tapspatel** [comment]
whenever you're ready to submit, uncomment all the other tests in the t3k run_* files and it should be good to go

**Review by yieldthought — APPROVED** [review]
Approved pending a clean run of the tests and re-enabling the other models in the test scripts

**Comment by tapspatel** [comment]
ditto what mark said

**Review by tapspatel — APPROVED** [review]

**Pull request merged**
