### PR TITLE
#7509: added separate C++ operation for ttnn.add

### PR DESCRIPTION
**Pull request by arakhmati**

### CODE REVIEW

**Review by eyonland — APPROVED** [review]

**Review by davorchap — COMMENTED** [review]
Is Binary::validate() cached ?

**Comment by arakhmati** [comment]
> Is Binary::validate() cached ?

Yes, it is

**Comment by davorchap** [comment]
> > Is Binary::validate() cached ?
> 
> Yes, it is

where is it called from, not from `create_program` ?

**Comment by arakhmati** [comment]
> > > Is Binary::validate() cached ?
> > 
> > 
> > Yes, it is
> 
> where is it called from, not from `create_program` ?

This is the code that runs every time an operation is executed
```
#ifdef DEBUG
    operation.validate(input_tensors, optional_input_tensors, optional_output_tensors);
#endif
    auto output_tensors = operation.create_output_tensors(input_tensors, optional_output_tensors);
    auto program = get_or_create_program(operation, input_tensors, optional_input_tensors, output_tensors);
    uint32_t device_id = detail::get_device(input_tensors, optional_input_tensors)->id();
```

**Comment by davorchap** [comment]
> > > > Is Binary::validate() cached ?
> 
> > > 
> 
> > > 
> 
> > > Yes, it is
> 
> > 
> 
> > where is it called from, not from `create_program` ?
> 
> 
> 
> This is the code that runs every time an operation is executed
> 
> ```cpp
> 
> #ifdef DEBUG
> 
>     operation.validate(input_tensors, optional_input_tensors, optional_output_tensors);
> 
> #endif
> 
>     auto output_tensors = operation.create_output_tensors(input_tensors, optional_output_tensors);
> 
>     auto program = get_or_create_program(operation, input_tensors, optional_input_tensors, output_tensors);
> 
>     uint32_t device_id = detail::get_device(input_tensors, optional_input_tensors)->id();
> 
> ```

Only the code that is run as part of get_or_create_program is cached. So validate is not currently cached.

Can't we call validate from create program , in which case we could run it even in RELEASE mode ?

**Pull request merged**
