### PR TITLE
Merge v2 of untilize_with_halo, maxpool, and conv ops for Resnet-50

### PR DESCRIPTION
**Pull request by TT-BrianLiu**

### CODE REVIEW

**Review by mywoodstock — APPROVED** [review]

**Comment by TT-BrianLiu** [comment]
Passing slow and fast dispatch pipelines on slightly older version of branch:
- https://github.com/tenstorrent-metal/tt-metal/actions/runs/7202406123/job/19622244953
- https://github.com/tenstorrent-metal/tt-metal/actions/runs/7202405041

**Comment by TT-BrianLiu** [comment]
Almost passing post-commit: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7203768044/job/19624146385

**Comment by TT-BrianLiu** [comment]
All post commit passing except for one UMD related hang: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7204615231/job/19626337731

**Review by boris-drazic — APPROVED** [review]

**Comment by TT-BrianLiu** [comment]
Passing slow and fast dispatch:
- https://github.com/tenstorrent-metal/tt-metal/actions/runs/7205830828
- https://github.com/tenstorrent-metal/tt-metal/actions/runs/7205832622

**Comment by TT-BrianLiu** [comment]
Post-commit is timing out for slow dispatch unit tests. Otherwise, everything is passing: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7204615231.

Bumped timeout to 120 mins and rerunning just this job: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7213907760

Also picked up one very small commit from `main` (f29c0a2222a164f). Shouldn't need to rerun all pipelines for this.

**Review by tt-nshanker — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Comment by TT-BrianLiu** [comment]
All tests are passing until `/mnt/MLPerf/bit_error_tests`: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7213907760/job/19660246517

**Pull request merged**
