### PR TITLE
#3310: Fix rdiv

### PR DESCRIPTION
**Pull request by Aswinmcw**
Fix issues related to rdiv
Unit test : `pytest tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_rdiv.py`
Sweep Test: `tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_eltwise_rdiv_test`
All post commit test : https://github.com/tenstorrent-metal/tt-metal/actions/runs/8568850128

### CODE REVIEW

**Review by eyonland — COMMENTED** [review]
Did this change not break a test?  Can we add one?

**Review by eyonland — CHANGES_REQUESTED** [review]
Do we already have a test (maybe a sweep test?) that is already failing that you can reference in the description before I approve?
If we do not have a test for this, can we please make a unit test?

**Comment by Aswinmcw** [comment]
> Do we already have a test (maybe a sweep test?) that is already failing that you can reference in the description before I approve? If we do not have a test for this, can we please make a unit test?

Hi @eyonland , i have attached the result of rdiv unit test after this fix, the last one fails as it exceeds the memory limit
image
[eltwise_rdiv_sweep.csv](https://github.com/tenstorrent-metal/tt-metal/files/14921115/eltwise_rdiv_sweep.csv)

**Review by eyonland — APPROVED** [review]
Please add the reference to the existing tests in the description going forward.  Thanks

**Pull request merged**
