### PR TITLE
Vecadd example

### PR DESCRIPTION
**Pull request by tt-rkim**

### CODE REVIEW

**Comment by tt-rkim** [comment]
@marty1885 
Because you cannot run our CI, I have mirrored your branch to our repo, rebased and resolved conflicts, and added your vecadd example to our CI: https://github.com/tenstorrent/tt-metal/actions/runs/8852232233

Once this passes, we will merge this PR and close your original PR.

Unless there is an issue with the actual test, there are no further steps you need to take.

We are still working on documenting a final process for contributions to tt-metal given the above constraints. Sorry for the delay and inconvenience. Please feel free to tag us again if there are any further issues.

cc: @jliangTT @TT-billteng

**Review by mo-tenstorrent — APPROVED** [review]

**Comment by tt-rkim** [comment]
I have:

- squashed your commits
- passing post-commit CI
- fixed an incorrectly-formatted commit message

**Comment by marty1885** [comment]
@tt-rkim Thanks. Hopefully the contribution process could be finalized soon. I have a lot of local changes to get Metalium working on Arch Linux and newer compilers. I definitely want to upstream them as soon as possible.

**Comment by jliangTT** [comment]
hey Marty, thanks for all the great contribution so far, and appreciate your patience so far. As evident in this past experience, we are not where we want to be when it concerns our contribution process in term of staffing / process maturity. We are learning / improving fast because it is now our company priority. Keep em coming!

**Comment by TT-billteng** [comment]
> @tt-rkim Thanks. Hopefully the contribution process could be finalized soon. I have a lot of local changes to get Metalium working on Arch Linux and newer compilers. I definitely want to upstream them as soon as possible.

What compiler versions are you using? We have plans to switch to clang 17 or gcc 13 soon

**Comment by marty1885** [comment]
@TT-billteng Yes, I'm using GCC 13 and Clang 17 right now. I'll move to GCC 14 and Clang 18 as soon as their are released.

**Pull request merged**
