### PR TITLE
 fix page_shape for rm tensor sharding

### LINKED ISSUE #4319: Sharded tensor move to host `.cpu()` hangs for a particular config in Fast Dispatch mode
**Describe the bug**
The following unit test hangs at the `.cpu()` call when run in fast dispatch:
```pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_v2.py::test_generate_all_configs_and_references[False-conv_params22-20-input_chw_shape22-98-grid_size22-False]```

No issues with slow dispatch mode.

Performing a `sharded_to_interleaved` and then moving to host with `.cpu()` works fine too. So the sharded tensor move to host hangs.

**To Reproduce**

Branch: `bliu/issue-4319`
Test: `pytest tests/tt_eager/python_api_testing/unit_testing/test_untilize_with_halo_v2.py::test_generate_all_configs_and_references[False-conv_params23-20-input_chw_shape23-98-grid_size23-False]`

The input tensor shape to this unit test (UTWHv2) is: `[1, 1, 62720, 128]` and the constructed output is the following shape:
`[1, 1, 98 * 913, 128]`, each shard being `[913, 128]` sized.
Datatype is `BFLOAT16`

### PR DESCRIPTION
**Pull request by ntarafdar**
Addresses this issue: https://github.com/tenstorrent-metal/tt-metal/issues/4319

### CODE REVIEW

**Comment by tt-aho** [comment]
Is this pr still needed or can it be closed?

There was an actual fix for interleaved_to_sharded op pushed to main so the second commit in this pr should be removed.

**Comment by tarafdarTT** [comment]
@tt-aho the first commit I think needs to be there, the page shape that was returning for bfloat16 was too big otherwise. Should I separate that PR?

**Comment by tt-aho** [comment]
You can just remove the second commit from this pr since it is no longer needed after rebase

**Comment by tarafdarTT** [comment]
@tt-aho haha nvm, its been a while, looks like that commit was already pushed to main as it was cherry-picked in another PR.
Closing this one now

**Pull request closed without merging**
