### PR TITLE
#10548: Support tile layout for width/height-sharded concat

### PR DESCRIPTION
**Pull request by jerrysky3**
### Ticket
#10548

### Problem description
Change kernel to support concat on both width and height-sharded tensors in tile layout. The kernel supports the following cases:

- Height-sharded width concat in row-major/tile layout
- Width-sharded height concat in row-major/tile layout

For now it's only used to concat > 2 tensors. Two tensor concatenation is currently handled by a special unrolled kernel due to performance issue with runtime args. This new kernel can be unrolled and replace it if needed in the future

### What's changed
- Rename and change `s2s_rm_concat_multi_core` to `s2s_concat_multi_core` to support tile layout besides the row-major layout
- Rename `reader_s2s_rm_tensor_concat.cpp` to `reader_s2s_tensor_concat.cpp`

### Checklist
- [x] Post commit CI passes https://github.com/tenstorrent/tt-metal/actions/runs/11396048642
- [ ] Blackhole Post commit (if applicable)
- [x] Model regression CI testing passes (if applicable) https://github.com/tenstorrent/tt-metal/actions/runs/11396057538
- [x] Device performance regression CI testing passes (if applicable) https://github.com/tenstorrent/tt-metal/actions/runs/11396055725, the fails are due to [other changes](https://github.com/tenstorrent/tt-metal/pull/13744#issuecomment-2422843900)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by jerrysky3** [comment]
Device performance regression (https://github.com/tenstorrent/tt-metal/actions/runs/11396055725) is failing with:

```
AssertionError: Some model(s) AVG DEVICE KERNEL SAMPLES/S are faster than expected, see above for details. {'AVG DEVICE KERNEL SAMPLES/S': [('ttnn_distilbert8_distilbert-base-uncased-distilled-squad', 90.4624, 20.394), ('ttnn_functional_ttnn_vgg11_1_', 270.5544, 108.871), ('ttnn_functional_ttnn_vgg16_1_', 195.0345, 95.378)]}
```

However it is currently also happening on the main branch: https://github.com/tenstorrent/tt-metal/actions/runs/11399044245/job/31717674624#step:9:2739

**Review by sjameelTT — APPROVED** [review]
Looks good to me, nice work.

**Comment by sjameelTT** [comment]
> Device performance regression (https://github.com/tenstorrent/tt-metal/actions/runs/11396055725) is failing with:
> 
> ```
> AssertionError: Some model(s) AVG DEVICE KERNEL SAMPLES/S are faster than expected, see above for details. {'AVG DEVICE KERNEL SAMPLES/S': [('ttnn_distilbert8_distilbert-base-uncased-distilled-squad', 90.4624, 20.394), ('ttnn_functional_ttnn_vgg11_1_', 270.5544, 108.871), ('ttnn_functional_ttnn_vgg16_1_', 195.0345, 95.378)]}
> ```
> 
> However it is currently also happening on the main branch: https://github.com/tenstorrent/tt-metal/actions/runs/11399044245/job/31717674624#step:9:2739

Yeah this was actually me, perf numbers have improved on a bunch of models but I didn't update them with my change since we fail on very big improvements too (to prevent the numbers from getting stale).

**Comment by jerrysky3** [comment]
Hi @ayerofieiev-tt , this is another kernel ramp-up task that needs a code owner review and merge. Thanks!

**Review by ayerofieiev-tt — APPROVED** [review]

**Pull request merged**
