### PR TITLE
#0: Update license header from 2023 to 2024 / to TT AI ULC

### PR DESCRIPTION
**Pull request by ayerofieiev-tt**
### Ticket
No ticket

### Problem description
License header specifies 2023 even though files were created or touched in 2024

### What's changed
Update header

Company's legal name changed too from TT Inc. to TT AI ULC according to legals.

```
find /home/ubuntu/tt-metal -type f -not -path '*/.*' -exec sed -i '1,20s|SPDX-FileCopyrightText: © 2023 Tenstorrent Inc.|SPDX-FileCopyrightText: © 2024 Tenstorrent AI ULC|' {} +
```

Screenshot 2024-08-19 at 10 50 12 AM

the difference in created/removed is due to a black formatting (py files)

### Checklist
- [ ] Post commit CI passes

### CODE REVIEW

**Review by skhorasganiTT — APPROVED** [review]

**Review by yan-zaretskiy — APPROVED** [review]

**Comment by bbradelTT** [comment]
Did you check that this okay?

I thought the year should at least be when the file was initially created?

**Review by mo-tenstorrent — APPROVED** [review]

**Review by esmalTT — APPROVED** [review]

**Review by shwetankTT — APPROVED** [review]
LGTM

**Review by yugaoTT — APPROVED** [review]

**Comment by ayerofieiev-tt** [comment]
> Did you check that this okay?
> 
> I thought the year should at least be when the file was initially created?

@bbradelTT , 

I assume that
* we have lots of files which were substantially updated since they were created in 2023
* there are many files created in 2024 which have 2023 header
* this is not the most important thing in the world

**Review by bbradelTT — APPROVED** [review]

**Review by tt-aho — COMMENTED** [review]
We should update the contribution guide if we are changing how we set the year in the header to whenever the file is modified.

Not asking for this in this pr, but if this is the style we choose then we should be able to update our post-commit check to enforce having the current year on any touched file.

**Review by cglagovichTT — APPROVED** [review]

**Pull request closed without merging**
