### PR TITLE
#0: Get rid of run_pre_post_commit_regressions* scripts and split CPP tests as much as we can

### PR DESCRIPTION
**Pull request by tt-rkim**
…

### Ticket

Suggestions from @ttmchiou and @TT-billteng 

### Problem description

We want to split running our tests more so that we can track down issues to specific suites in a simpler manner, rather than running the whole damn thing in one go, muddling problematic tests with ones that are okay and don't need attention

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [x] Post commit CI passes https://github.com/tenstorrent/tt-metal/actions/runs/12286441974
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] **(For models and ops writers)** Full [new models](https://github.com/tenstorrent/tt-metal/actions/workflows/full-new-models-suite.yaml) tests passes
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by tt-rkim** [comment]
Recent post-commit run showing all the jobs: https://github.com/tenstorrent/tt-metal/actions/runs/12300288212

With this proposed change, we will be:

- splitting the C++ tests into various jobs to enable us to reduce load on individual machines and isolate issues to smaller suites
- reducing the number of scripts and reliance on `run_tests.sh`
- Further locking down script usage for C++ tests

**Review by afuller-TT — APPROVED** [review]
Nice!

**Review by abhullar-tt — APPROVED** [review]
@TTDRosen fyi. I Know you guys are running run_cpp_unit_tests.sh as sanity check on fw releases now. This moves some of the test targets to different locations

**Comment by TTDRosen** [comment]
😢 new week, new way to execute the tests. So what is the new mechanism for executing the equivalent to the old cpp tests?   Should I be executing all of the commands under `cpp-unit-tests-slow-dispatch`?

**Comment by abhullar-tt** [comment]
> 😢 new week, new way to execute the tests. So what is the new mechanism for executing the equivalent to the old cpp tests? Should I be executing all of the commands under `cpp-unit-tests-slow-dispatch`?

yes and `cpp-unit-tests`

**Review by TT-billteng — APPROVED** [review]

**Comment by TT-billteng** [comment]
Sorry about the new headache @TTDRosen but we're having problems with turnaround time for the C++ pipelines :(

Perhaps we can migrate `run_tests.sh` to CTest / tox in the future to make this easier to figure out which target maps to which test suite

**Comment by tt-rkim** [comment]
I think this is a good reason to push up migrating test driver to ctest, at least for C++ tests since that's harder to keep track of than pytests

**Comment by ttmchiou** [comment]
Would recommend double checking on what run times would be affected for blackhole post commit too.
Would be a good sanity check

**Review by blozano-tt — APPROVED** [review]

**Review by ttmchiou — APPROVED** [review]

**Comment by tt-rkim** [comment]
For BH: https://github.com/tenstorrent/tt-metal/actions/runs/12304265010
Screenshot 2024-12-13 at 11 07 06 AM

**Pull request merged**
