### PR TITLE
#8965: gc collect before device close

### PR DESCRIPTION
**Pull request by aliuTT**
Seeing post commit CI tests hanging if I call garbage collection before device close. Should we just disable any tests that fail like this? https://github.com/tenstorrent/tt-metal/actions/runs/9352480375/job/25740974650

@tarafdarTT @abhullar-tt @tt-aho

### CODE REVIEW

**Comment by abhullar-tt** [comment]
does it also hang locally?

**Comment by tt-rkim** [comment]
You can try on a CI VM, maybe it shows w/ host side resource constraints

**Comment by tarafdarTT** [comment]
curious about this as well

> does it also hang locally?

**Comment by aliuTT** [comment]
Was able to see it hang locally on N150 172.27.28.71, running 
```pytest $TT_METAL_HOME/tests/ttnn/unit_tests -xv --splits 2 --group 1 -m "not disable_fast_runtime_mode```
It hangs at a different test: `tests/ttnn/unit_tests/operations/test_conv2d.py`
From my device pool CI triage, I've found that the tests in `test_conv2d.py` and `group_norm.py` tend to have random hangs if we try to clean up python memory usage...

**Comment by abhullar-tt** [comment]
do you think its worth making device track buffers rather than using the gc collect?

**Comment by aliuTT** [comment]
> do you think its worth making device track buffers rather than using the gc collect?
I'm trying to narrow down what is causing a hang, it should just be some device init and close thing, because all these tests that "hang" should just be skipped. If this is not going anywhere, then I'll try to have device track buffers

**Comment by aliuTT** [comment]
This was a hack PR, ended up checking DevicePool with bug fixes instead. Closing

**Pull request closed without merging**
