### PR TITLE
#1478: accuracy issues in unary comparison, relu-min/max, power operators

### PR DESCRIPTION
**Pull request by muthutt**
#1478: accuracy issues in unary comparison, relu-min/max, power operators
    - power op seems to mostly just return 1s instead of correct result. Test: Branch aho/new-op-sweeps, command pytest
    - fix

#1478: accuracy issues in unary relational ops
    - solution is to pass right sized exponential size to the function; BF16 = (1,8,7) (s,e,m) format.

#1480: unify naming of "hard_" activation functions
    - we have some inconsistent naming for the hard activations: pytorch doesnt use underscores

#1481: bug in relu_min, relu_max
    - bug identified by @Austin Ho
    - fix relu_min mapping in Python layer
    - fix negative and positive value of relu min, max thresholds
    - add tests and validate coverage

### CODE REVIEW

**Review by tt-aho — CHANGES_REQUESTED** [review]
@muthutt your first commit message is referencing a random github user. My handle is @tt-aho if you want to refer to me in a commit instead of using my full name.

I am seeing with these changes, eqz and nez are now passing for the test cases on my branch, but I still see gtz and lez failing for when input value is 0. Can you confirm if you still see this?

For relu_max, I also still see fails when upper_limit is a negative value when comparing to the pytorch function. I think this is because in `ckernel_sfpu.h`, the relu_max does min(x, upper_limit) then relu, but the pytorch reference function you have does relu, then min(x, upper_limit).

Can we also update the docstring for relu_min and relu_max? These aren't commonly defined functions so a more detailed description would be good, and also since relu min and relu max actually seem to behave different than expected when compared to each other in my opinion. Ex. the pytorch reference function for relu_max does relu, then min, whereas relu min just does max.

**Review by TT-BrianLiu — APPROVED** [review]

**Review by arakhmati — APPROVED** [review]
LGTM!

**Review by tt-aho — CHANGES_REQUESTED** [review]
~~Please remove any changes you pulled in from my branch from this PR (revert back to [67212ef](https://github.com/tenstorrent-metal/tt-metal/commit/67212ef358f8eef458e83f6995251c037b1d5399) and then squash/rebase on main) as they weren't ready to be fully merged yet. My branch was only referenced because it had unit tests that exposed the errors for these specific tests.~~

Discussed and decided to merge only some changes from my branch

**Review by tt-aho — APPROVED** [review]
Otherwise lgtm if pipelines pass. I can resolve the previous comment when I merge my branch if we want to just merge this one as is

**Pull request merged**
