### PR TITLE
Demo Functional Whisper audio classification, add support for batched_input

### PR DESCRIPTION
**Pull request by jayasuryamaganuru**
Demo for Audio classification for ttnn functional whisper is completed and
 Accuracy metric measured for `google/fleurs` validation dataset.
 
 Accuracy: 0.90382

### CODE REVIEW

**Review by boris-drazic — APPROVED** [review]

**Comment by jayasuryamaganuru** [comment]
All post commits CI is passing -[link](https://github.com/tenstorrent/tt-metal/actions/runs/8982768117)

**Comment by tt-rkim** [comment]
Please run passing:

- perf tests
- nightly fast dispatch tests

**Comment by jayasuryamaganuru** [comment]
> Please also confirm that on a local virtual machine your model did not hang after 20 times.

I've run the model (both optimized and unoptimized) for 25 iterations, it didn't hang.

Previously model (only optmized) ran for entire dataset, totaling close to 840 iterations,
it didn't hang in this case aswell.

**Comment by tt-rkim** [comment]
You have not confirmed yet that perf tests and nightly tests are passing, per my previous comment
Please post the links

**Comment by jayasuryamaganuru** [comment]
> Can you pls confirm the name of the machine you're running this on, or is this a local machine MCW has built?

ubuntu@tt-metal-dev-mcw-19 is the VM, nope this isn't local machine

**Comment by jayasuryamaganuru** [comment]
> You have not confirmed yet that perf tests and nightly tests are passing, per my previous comment Please post the links

I've triggered the CI's after rebasing the main today,
- [All post-commit tests](https://github.com/tenstorrent/tt-metal/actions/runs/9093759723) is passing
- [Nightly fast dispatch tests](https://github.com/tenstorrent/tt-metal/actions/runs/9093731992), one job is failing
- [Model perf regressions](https://github.com/tenstorrent/tt-metal/actions/runs/9091989884/job/24988238531) , two are failing

**Comment by tt-rkim** [comment]
Did you look into why those jobs were failing? I see no indication in your comment that you looked into the specifics of the failing tests, or if they matched the failures you saw on mainl.

Looks like you committed git conflict markers by accident but they're now gone for the performance test. Please run the performance test locally on your GS machine to confirm it works, as we currently have an issue on main.

Nightly also has an issue on main, but your branch doesn't introduce further regressions.

**Comment by jayasuryamaganuru** [comment]
> Did you look into why those jobs were failing? I see no indication in your comment that you looked into the specifics of the failing tests, or if they matched the failures you saw on mainl.
> 
> Looks like you committed git conflict markers by accident but they're now gone for the performance test. Please run the performance test locally on your GS machine to confirm it works, as we currently have an issue on main.
> 
> Nightly also has an issue on main, but your branch doesn't introduce further regressions.

Yes, the test_performance.py's running locally on local GS machine,
attached the generated csv reports for optimized and unoptimized versions please check
[perf_ttnn_openai_whisper-base__2024_05_15.csv](https://github.com/tenstorrent/tt-metal/files/15322427/perf_ttnn_openai_whisper-base__2024_05_15.csv)
[perf_ttnn_openai_whisper-base_optimized__2024_05_15.csv](https://github.com/tenstorrent/tt-metal/files/15322428/perf_ttnn_openai_whisper-base_optimized__2024_05_15.csv)

**Pull request closed without merging**
