### PR TITLE
#5137: Cleanups for newer Linux distro / toolchains

### PR DESCRIPTION
**Pull request by olofj**
This is a bunch of cleanups to enable compilation on a newer distro (Debian Bookworm in my case).

In addition to this, there's a couple of small fixes to UMD needed as well, I've queued them separately in that repo.

I have one more remaining thing to debug, `pip install -e` doesn't work as part of the main build. `pip install` does, so this is something finicky due to newer python.

I don't know how you usually prefer to see code split up functionally, this ends up being a pretty large series toucing multiple files. I've split it into separate commits to keep it clean though:

```
Olof Johansson (15):
      common/bfloat16: add missing include
      device.hpp: add missing include of mutex
      tt_stl/concepts.hpp: add missing pragma once
      allocator_types: add missing <functional> include
      llrt/watcher.cpp: add missing <mutex> include
      CoreRange: Remove designated initializers
      CoreCoord: Remove designated initializers
      ShardSpec: Remove designated initializers
      {Reader,Writer}DataMovementConfig: Use ctor instead of initializer
      third_party/fmt: Temporary fixup for newer GCC
      Use memcpy for float conversions
      Fix for possibly uninitialized variable in split_across_cores()
      tt_eager: Fix a few possibly uninitialized variable warnings
      layernorm_multi_core: Fix uninitialized variable
      Enable newer python3 versions
      setup.py: Create directory for library files
      #5137: requirements-dev: allow torchvision-cpu >= 0.14.1, numba >= 0.56.4
```

### CODE REVIEW

**Review by TT-billteng — APPROVED** [review]
Thanks @olofj !

**Comment by TT-billteng** [comment]
We do have plans to move to a new GCC that supports [C++20](https://github.com/tenstorrent-metal/tt-metal/issues/4252)

**Comment by olofj** [comment]
> FYI, we do have plans to move to a newer GCC that supports [C++20](https://github.com/tenstorrent-metal/tt-metal/issues/4252)

Any thoughts of just going straight to LLVM as base compiler? Might not make a ton of difference performance wise but could be worth a try.

**Comment by TT-billteng** [comment]
> > FYI, we do have plans to move to a newer GCC that supports [C++20](https://github.com/tenstorrent-metal/tt-metal/issues/4252)
> 
> Any thoughts of just going straight to LLVM as base compiler? Might not make a ton of difference performance wise but could be worth a try.

I haven't considered it as I was only looking at GCC availability on 20.04. I'll look to see what's available on the LLVM front

**Comment by TT-billteng** [comment]
Seems like clang has great support of [C++20](https://clang.llvm.org/cxx_status.html#cxx20) features as of clang-12, which is available in [20.04](https://packages.ubuntu.com/search?keywords=clang). Seems like its possible to upgrade to a later version fairly easily if needed https://ubuntuhandbook.org/index.php/2023/09/how-to-install-clang-17-or-16-in-ubuntu-22-04-20-04/

**Review by tt-aho — APPROVED** [review]

**Comment by tarafdarTT** [comment]
LGTM, thanks @olofj

**Review by ntarafdar — APPROVED** [review]

**Review by mywoodstock — APPROVED** [review]

**Comment by olofj** [comment]
Rebased due to conflicts. I also added two more patches to deal with the final wheel build -- one to create the subdirectory for the libraries, the second to relax the requirements and allow newer versions of numba and torchvision.

@TT-billteng since you were looking at this, the requirements change might cause regressions but I'm not sure how to run the full regular CI for confidence. Guidance would be appreciated.

**Comment by tt-rkim** [comment]
Do we want to reopen this and try again once Olof has fixes?

For CI confidence, I wanted people's opinions about the following flow since we don't actually have anything codified:

1. external people open a pull request targeting a side branch on our repo
2. we open a PR for that branch targeting main on our repo
3. Run actions on that branch as CI
4. Go back to step 1 if failures
5. Merge PR from step 2

**Pull request merged**
