### PR TITLE
#13088: Cleanup set-1 unary backward ops

### LINKED ISSUE #13088: Cleanup set-1 unary backward ops
Master : https://github.com/tenstorrent/tt-metal/issues/12721
Cleanup the following

- [x] DEFINE_UNARY_BACKWARD_OPERATION_WITH_2_DEFAULT_FLOATS
- [x] DEFINE_UNARY_BACKWARD_OPERATION_WITH_1_DEFAULT_FLOAT
- [x] ExecuteUnaryBackwardRecip
- [x] ExecuteUnaryBackwardFloat (3)

### PR DESCRIPTION
**Pull request by VirdhatchaniKN**
Issue : #13088

[CI](https://github.com/tenstorrent/tt-metal/actions/runs/11031028313) : PASSED

**Test Files :** 

- hardshrink_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_hardshrink.py` - PASSED
- softshrink_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_softshrink.py` - PASSED
- leaky_relu_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_leaky_relu.py` - PASSED
- elu_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_elu.py` - PASSED
- celu_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_celu.py` - PASSED
- logiteps_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_logiteps.py` - PASSED
- rpow_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_rpow.py` - PASSED
- polygamma_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_polygammapy` - PASSED
- div_no_nan_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_div_no_nan.py` - PASSED
- Softplus_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_sofplus.py` - PASSED
- hardtanh_bw : `tests/ttnn/unit_tests/operations/backward/test_backward_hardtanh.py` - PASSED
- reciprocal_bw : 
  - `tests/ttnn/unit_tests/operations/backward/complex_ops/test_backward_recip.py` - PASSED
  - `tests/ttnn/unit_tests/operations/backward/test_backward_reciprocal.py` - PASSED

### CODE REVIEW

**Review by Aswinmcw — APPROVED** [review]
LGTM

**Review by bharane-ab — APPROVED** [review]

**Review by eyonland — APPROVED** [review]

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11035643710

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11036783323

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11044794065 - passed

**Pull request merged**
