### PR TITLE
#6410: Encapsulate tensor attributes inside a shared_ptr

### PR DESCRIPTION
**Pull request by tt-asaigal**
- Asynchronous execution requires worker and main threads to have joint ownership of tensors.
  - Implement joint ownership by placing all tensor (meta)data inside a tensor attribute shared_ptr. Attribute ref count increases each time a tensor is copied, which allows worker to own tensor even if main thread destroys its own copy.
  - Add empty tensor constructor, which allows worker threads to populate tensors post creation. Allows passing empty tensor handles from worker to main.

### CODE REVIEW

**Comment by tt-asaigal** [comment]
Hey @arakhmati @eyonland  @cfjchu, this MR is based on our discussion about placing tensor attributes inside a shared pointer, so that tensors can be safely shared between threads and asynchronously populated.

I've added tests simulating the main --> worker thread path to ensure that this approach allows for tensors in worker threads to be used after the main thread deallocates them. Also testing the worker --> main thread path, where the main thread gets a tensor handle that gets populated by the worker at some point in the future.

**Comment by tt-asaigal** [comment]
Passing CI Pipeline: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8288665456

**Review by eyonland — CHANGES_REQUESTED** [review]
Would you convert these two tests to gtests and make them part of the CI commit pipeline?

**Comment by tt-asaigal** [comment]
> Would you convert these two tests to gtests and make them part of the CI commit pipeline?

They're already part of the Post commit pipeline, but I can make them gtests. Just need to find where the gtests for eager are defined.

**Comment by tt-asaigal** [comment]
Tests for this feature now use gtest fixtures.

**Review by eyonland — APPROVED** [review]

**Pull request merged**
