### PR TITLE
#0: deleting all of dtx

### PR DESCRIPTION
**Pull request by vtangTT**
Taking up space, time to build, and money every time someone pulls from git lfs

Not used anymore, so time to remove

### CODE REVIEW

**Review by tt-rkim — APPROVED** [review]

**Comment by tt-rkim** [comment]
FUCKING FINALLY

**Review by arakhmati — APPROVED** [review]

**Review by tt-aho — APPROVED** [review]

**Comment by vtangTT** [comment]
clean post commit: https://github.com/tenstorrent-metal/tt-metal/pull/7223

**Comment by TT-billteng** [comment]
Are you planning to delete DTX lfs files + submodule bump in a separate PR?

**Review by tt-nshanker — APPROVED** [review]

**Comment by vtangTT** [comment]
clean post commit with lfs updates: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8622807740

**Pull request merged**
