### PR TITLE
#7713: Remove CI model tests for models not in Javelin

### PR DESCRIPTION
**Pull request by boris-drazic**

### CODE REVIEW

**Comment by boris-drazic** [comment]
CI pipeline runs here: https://github.com/tenstorrent/tt-metal/actions?query=branch%3Abdrazic%2Fmodels-ci++
`Nightly multi-chip tests` fails in the same way as on main, rest pass.

**Comment by tt-rkim** [comment]
Why can't delete these models files?

**Comment by boris-drazic** [comment]
We don't want to delete model files as they might be useful in the future when bringing up these models in `ttnn`.

**Comment by tt-rkim** [comment]
Can we move into a deprecated folder, instead of experimental?

**Comment by boris-drazic** [comment]
Yes we can move them into deprecated folder in a separate PR.

**Comment by tt-rkim** [comment]
https://github.com/tenstorrent/tt-metal/issues/7727

**Review by tt-rkim — APPROVED** [review]

**Pull request merged**
