### PR TITLE
#1466: moving perf asserts to a single file at the end!

### PR DESCRIPTION
**Pull request by ashayestehmanesh**
This is to put all the asserts into one file at the end of the perf pipeline. 

I will be running this branch on CI with different numbers to test it. It will take a bit of time to merge it in! I will not run a huge batch of jobs to avoid congestion since we have only one runner!

There is definitely lots of space for improvements, such as making a config file, we can (should) do. Here, I wanted to do the minimum to bring in the feature. 

asserts will be removed before merging to main.

@tt-rkim fyi, and open to your suggestions!

### CODE REVIEW

**Review by boris-drazic — APPROVED** [review]
With understanding that commented out asserts will be removed before merge.

**Review by farbabi — APPROVED** [review]

**Review by tt-rkim — CHANGES_REQUESTED** [review]
will fully review when you're ready

**Review by tt-rkim — CHANGES_REQUESTED** [review]
I have made two comments. Also, please squash your commit messages with a meaningful full commit message. Your intermediate commit messages have too little context, in my opinion.

**Review by tt-rkim — APPROVED** [review]
LGTM, merge as soon as pipelines pass

**Pull request merged**
