### PR TITLE
Adding setter and getter for RT args 

### PR DESCRIPTION
**Pull request by abhullar-tt**
TODO:

- [x]  Add unit tests for initializing and modifying rt args
- [x] Update docs

### CODE REVIEW

**Review by arakhmati — DISMISSED** [review]
LGTM

**Review by mywoodstock — DISMISSED** [review]
bmm, conv lgtm!!

**Review by DrJessop — DISMISSED** [review]
Looks great. This will prevent a lot of potential bugs.

**Review by tt-aho — DISMISSED** [review]

**Review by tt-nshanker — DISMISSED** [review]

**Review by TT-BrianLiu — DISMISSED** [review]
lgtm

**Review by mo-tenstorrent — DISMISSED** [review]

**Review by tt-rkim — DISMISSED** [review]
LGTM but just have to pass all pipes

**Review by davorchap — DISMISSED** [review]

**Review by DrJessop — DISMISSED** [review]
The problem with passing in Kernel pointer over RISCV is that the user may not have a kernel in scope at the time that they want to call this API.

Thus, you'll end up with the following situation
```
SetRuntimeArgs(program, program.kernel_group(core).riscv0, core, args) 
```

when if you use RISCV, it would be as simple as 

```
SetRuntimeArgs(program, RISCV::BRISC, core, args) 
```

**Review by DrJessop — COMMENTED** [review]
So talked to Davor and got some more perspective. RISCV instead of Kernel to SetRuntimeArgs breaks since we may swap which RISCV we're running a kernel on.

However, we need to consider that if we don't have kernel in scope, what is the process of easily figuring out which kernel we're trying to target to set runtime args for.

**Review by TT-billteng — DISMISSED** [review]

**Review by davorchap — DISMISSED** [review]

**Review by arakhmati — DISMISSED** [review]

**Review by tt-aho — DISMISSED** [review]

**Review by TT-BrianLiu — DISMISSED** [review]

**Review by TT-billteng — DISMISSED** [review]
great work :)

**Review by arakhmati — APPROVED** [review]

**Review by mywoodstock — APPROVED** [review]

**Review by davorchap — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]
docs approved

**Review by TT-billteng — APPROVED** [review]

**Pull request merged**
