### PR TITLE
#8428: Update sweep config and doc for polyval

### PR DESCRIPTION
**Pull request by umadevimcw**
### Ticket
#8428 

### Problem description
Inconsistent documentation for polyval op

### What's changed
- Updated sweep config and documentation
- Moved old sweep to new sweep

### Checklist
- [x] [Post commit CI passes](https://github.com/tenstorrent/tt-metal/actions/runs/11101124234)
- [x] [TTNN Sweep test](https://github.com/tenstorrent/tt-metal/actions/runs/11101132354)

### CODE REVIEW

**Review by Aswinmcw — APPROVED** [review]
LGTM

**Review by VirdhatchaniKN — APPROVED** [review]

**Review by eyonland — CHANGES_REQUESTED** [review]
Please move these tests to the new location.

**Comment by umadevimcw** [comment]
> Please move these tests to the new location.

Updated

**Review by eyonland — APPROVED** [review]
Please visually verify the docs before merging.

**Review by jdesousa-TT — APPROVED** [review]

**Comment by jdesousa-TT** [comment]
Please run the new sweeps through the `ttnn - run sweeps` pipeline before merging.

**Review by eyonland — APPROVED** [review]

**Review by ayerofieiev-tt — APPROVED** [review]

**Pull request merged**
