### PR TITLE
#6254: Make program cache per device:

### PR DESCRIPTION
**Pull request by tt-asaigal**
- Add generic program cache class to TT-Metal device object
  
  - Change tt_lib and ttnn APIs to interface with per-device cache:
     - Remove program_cache definition and python exports from tt_lib
     - Remove program_cache definition from ttnn and add exports for device program cache APIs
  
  - Test changes: 
     - conftest.py no longer has a clear_program_cache fixture. Instead cache is cleared when device is closed. 
     - use_program_cache fixture modified to enable program cache for all devices when running multi-device tests 
     - Initialize device fixture before use_program_cache fixture 
     - NEED FEEDBACK: Disabled test_program_cache in test_host_side_api since it now needs device handle for program  
        cache, but the test runs on a machine w/o TT Device.
  
  - When running with 1 thread per device, this allows thread safe access to program cache

### CODE REVIEW

**Review by boris-drazic — APPROVED** [review]

**Review by arakhmati — APPROVED** [review]

**Review by tt-nshanker — APPROVED** [review]

**Comment by tt-asaigal** [comment]
> Device storage struct should be updated to not have device_id as its attribute. So, that the program hash is the same on every device

Got rid of the attribute for the default operation hash. Got rid of all invocations of device_id in the hash function overrides.

**Comment by tt-asaigal** [comment]
@tt-rkim I've replaced `test_program_cache` in `test_host_api`  with `test_global_var_toggle_and_device_eps` to ensure that APIs run correctly on gitlab runners. Can't use the program cache anymore, since it requires a device handle. Please lmk if this is okay. Thanks!

**Review by tt-rkim — APPROVED** [review]
@tt-aho

**Comment by tt-asaigal** [comment]
Latest CI rebased off fairly recent main: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8238023482/job/22528091204

**Pull request merged**
