### PR TITLE
#0: Refactor Resnet files to match other model's folder/file structure and add tg, tgg tests/results

### PR DESCRIPTION
**Pull request by tt-aho**
### Problem description
Resnet file structure did not match other models.
Need to add tg/tgg tests for Resnet.

### What's changed
Refactor Resnet files to match other models.
Added tg/tgg tests for Resnet and add results to README.md

### Checklist
- [x] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [x] Model regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

Passing CI (Fails are same as main):
Post commit (black check is fixed on latest): https://github.com/tenstorrent/tt-metal/actions/runs/10762273676 https://github.com/tenstorrent/tt-metal/actions/runs/10766148657/job/29851436694
Nightly: https://github.com/tenstorrent/tt-metal/actions/runs/10765942615
Single-Card Demo: https://github.com/tenstorrent/tt-metal/actions/runs/10766167947
Model Perf: https://github.com/tenstorrent/tt-metal/actions/runs/10762275892
Device Perf: https://github.com/tenstorrent/tt-metal/actions/runs/10762280487
T3K Frequent: https://github.com/tenstorrent/tt-metal/actions/runs/10762274891
T3K Perf: https://github.com/tenstorrent/tt-metal/actions/runs/10762283389
TG Perf: https://github.com/tenstorrent/tt-metal/actions/runs/10762293419
TG Frequent: https://github.com/tenstorrent/tt-metal/actions/runs/10767269014
TGG Perf: https://github.com/tenstorrent/tt-metal/actions/runs/10762296962
TGG Frequent: https://github.com/tenstorrent/tt-metal/actions/runs/10762296197

### CODE REVIEW

**Review by davorchap — APPROVED** [review]

**Comment by uaydonat** [comment]
Resnet works on TGG? 💪

**Comment by tt-aho** [comment]
> Resnet works on TGG? 💪
Yes 🙂 
TGG Perf: https://github.com/tenstorrent/tt-metal/actions/runs/10762296962
TGG Frequent: https://github.com/tenstorrent/tt-metal/actions/runs/10762296197

**Comment by davorchap** [comment]
> > Resnet works on TGG? 💪
> 
> Yes 🙂 TGG Perf: https://github.com/tenstorrent/tt-metal/actions/runs/10762296962 TGG Frequent: https://github.com/tenstorrent/tt-metal/actions/runs/10762296197

We can 2x once we have 2 CQs ?

**Comment by tt-aho** [comment]
> > > Resnet works on TGG? 💪
> > 
> > 
> > Yes 🙂 TGG Perf: https://github.com/tenstorrent/tt-metal/actions/runs/10762296962 TGG Frequent: https://github.com/tenstorrent/tt-metal/actions/runs/10762296197
> 
> We can 2x once we have 2 CQs ?

Rough projections comparing to current T3K perf seems to be 1.4x, since that's the improvement we see going from single to two cq trace on T3K. T3K single cq trace is 22K, whereas 2CQ trace is 31K fps at the moment.

**Review by tt-rkim — APPROVED** [review]

**Review by mywoodstock — APPROVED** [review]

**Review by uaydonat — APPROVED** [review]

**Pull request merged**
