### PR TITLE
#6443: Update log backward

### PR DESCRIPTION
**Pull request by VirdhatchaniKN**
#6443  Updated logic for backward log op and updated few backward test files

Issues addressed : 
- **Log** : 
   - Updated logic to get nan / inf / -inf based on input. 
   - Checked PCC and All close - both passes
- **Test file Updated for the following ops** : 
   - Log
   - Gelu
   - Bias Gelu
   - Unary Bias Gelu
   - Neg
   - Ceil
   - Unary Sub
   - Ne
   - Binary GE

All post-commit tests - [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8452776697) - PASSED

### CODE REVIEW

**Review by eyonland — APPROVED** [review]

**Review by eyonland — CHANGES_REQUESTED** [review]
Where is the test to handle the nan case?

**Comment by VirdhatchaniKN** [comment]
> Where is the test to handle the nan case?

Hi @eyonland .When both input and grad is zero, the result is nan. I've added a condition for the same
 ```
   grad_tensor.emplace_back( 
            where(eqz(input, output_mem_config),
                       where(eqz(grad, output_mem_config),
                                  t_nan,
                                  mul(t_inf, sign(grad, output_mem_config), std::nullopt, output_mem_config), output_mem_config),
                        grad_a, output_mem_config));
```
I've tested the same with `data_gen_with_val`

**Review by arakhmati — APPROVED** [review]

**Comment by eyonland** [comment]
Hi @VirdhatchaniKN,
Are you referring to this code below in your test?
```
in_data, input_tensor = data_gen_with_range(input_shapes, -100, 100, device, True)
grad_data, grad_tensor = data_gen_with_range(input_shapes, -100, 100, device)
```

Looking at data_gen_with_range I see this...
```
def data_gen_with_range(input_shapes, low, high, device, required_grad=False, is_row_major=False):
    assert high > low, "Incorrect range provided"
    torch.manual_seed(213919)
    pt_tensor = torch.rand(input_shapes, requires_grad=required_grad).bfloat16() * (high - low) + low
    if is_row_major:
        tt_tensor = (
            tt_lib.tensor.Tensor(pt_tensor, tt_lib.tensor.DataType.BFLOAT16)
            .to(tt_lib.tensor.Layout.ROW_MAJOR)
            .to(device)
        )
    else:
        tt_tensor = (
            tt_lib.tensor.Tensor(pt_tensor, tt_lib.tensor.DataType.BFLOAT16).to(tt_lib.tensor.Layout.TILE).to(device)
        )
    return pt_tensor, tt_tensor
```

I don't see how your tests explicitly covers a tensor with zeros.   

My concern with a lot of these tests is that we are not checking any boundary conditions and leaving these edge cases to be discovered by another testing team.

**Comment by umadevimcw** [comment]
@eyonland In this kind of test, we will test the ops with random values for three shapes. We haven't yet created the sweep tests for backward ops (like forward ops). While testing this ops locally, we checked known corner cases and updated the test file. 

We can have writing sweep tests for backward ops in ToDo list and work on it later (once all the P0/P1 tasks are done). 
@eyonland @jliangTT  and @tt-aho Please share ur comments on the same

**Comment by eyonland** [comment]
@umadevimcw and @VirdhatchaniKN , ideally the extreme cases in the range of your arguments would be put on a unit test so that the likelihood of a test passing on the sweep tests is very high.   Sweep tests cover more than just the extreme boundary conditions.   We certainly need to make a todo for sure on the sweep tests though.

The weakness in relying so heavily on the sweep tests is that there is no automatic GH Issue creation from our CI pipeline when a sweep test fails that had passed previously from a prior run.  This means that many of these edge cases wait for the Syrmia team to discover it long after the developer has moved on to the next task.

@boris-drazic and others may have a different view on this, this is just my current view.

 I recognize that asking for these boundary conditions to be included in the unit test rather than just the happy path of random tensors is a departure from how we have been operating.

I'm approving this PR but would like for all of us to consider this change on unit tests moving forward.

**Review by eyonland — APPROVED** [review]

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8563936950 - passed

**Pull request merged**
