### PR TITLE
#0: Add support for multi-device fixture

### PR DESCRIPTION
**Pull request by Sudharsan-V**
### Problem description
The data parallel implementation of the model requires a pytest fixture that is compatible with both n150 and n300 devices. The existing pytest fixtures, device and mesh_device, have compatibility issues with n300 and n150, respectively. To address this, support has been added to the conftest file to automatically select either n150 or n300 based on the available platform.

### What's changed
The fixture multi_device is added to the conftest.py

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by tt-rkim** [comment]
There must be a better way to do this - instead of copy-pasting the code for single-device and mesh device respectively just to fit your use case.

Some other approaches that come to my mind are:

- We can have another fixture like here, however we refactor the code you copy-pasted from their original fixtures into separate functions that we call in all relevant fixtures to reduce copy-paste. BTW Please consider another name, `multi_device` is ambiguous.
- We don't have another real fixture, but instead we can have a "virtual fixture" where tests can request a fixture that doesn't seem like it exists, but in `pytest_generate_tests` there can be extra handling that will search for this fake fixture, attach the relevant fixture depending on if it's N150 or N300 (probably some extra asserts), and assign the right one.

I'm open to other suggestions.

I can see this being a very relevant pattern going forward for models for Blackhole as well.

This seems like you wanted to either avoid touching what others have written to be as non-invasive as possible, or to get your test going as quickly as possible without having to verify other tests are working, or both. Please don't do that. We should be as much common infrastructure as possible to avoid having to maintain less stuff, especially if that stuff is copy-paste.

cc: @SeanNijjar @cfjchu

**Comment by cfjchu** [comment]
Please do not merge this in.

we already have a `mesh_device` pytest fixture that already does this. If you use `mesh_device`, it should already work for N150/N300. For example, using that same fixture you can do something like this on the 8x4 galaxy mesh:

```
@pytest.mark.parametrize("mesh_device", [pytest.param((3, 4), id="3x4_grid")], indirect=True)
def test_feature(mesh_device)
    ...
```

**Comment by cfjchu** [comment]
Can you explain what issues you were hitting with the existing `mesh_device` fixtures?

**Comment by Sudharsan-V** [comment]
@cfjchu , I want to run the DistilBERT model (PR [#13158](https://github.com/tenstorrent/tt-metal/pull/13158)) on both n150 and n300, and I need the model to select and run on the appropriate device automatically. Here’s what I’ve tried so far:

- Using the `mesh_device` fixture, but it throws the error: `RuntimeError: bad_variant_access.` PFA the log below
```
ttnn/ttnn/model_preprocessing.py:325: in move_to_device
    object[name] = move_to_device(value, device)
ttnn/ttnn/model_preprocessing.py:332: in move_to_device
    return ttnn.to_device(object, device)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
```
- Included both the `device` and `mesh_device` fixtures, but the test hangs indefinitely. I believe this is due to device being incompatible with n300 and mesh_device being incompatible with n150.

**Comment by cfjchu** [comment]
Can you provide a small example repro? we already use this `mesh_device` fixture for N150, N300 tests.

**Comment by Sudharsan-V** [comment]
@cfjchu, mesh_device is working fine on both N150 and N300. The issue on N150 was due to an oversight on my part—since mesh_device is (1, 1) on N150, I didn’t wrap it with `ttnn.distribute(Tenn.ReplicateTensorToMesh(mesh_device))`, which caused the earlier error. It’s now resolved and functioning correctly.

However, using both device and mesh_device fixtures in the same test still results in an error. I’ve included the relevant unit test in this [commit](https://github.com/tenstorrent/tt-metal/commit/ce659ba0f9691373e7b848fd407ef9361158a250) for your review.
Thank you, and I apologize for any inconvenience caused.

**Comment by tt-rkim** [comment]
If you no longer need assistance, please close this PR, and delete the branch. Thank you

**Pull request closed without merging**
