### PR TITLE
#5769: Add batch mul support in composite

### PR DESCRIPTION
**Pull request by umadevimcw**
Tried a batch mul support in composite  using repeat 
 (torch.Size([1, 1, 320, 384]), torch.Size([64, 1, 320, 384])), # error w.r.t arg is more than 1kb 
 The above size failed with the issue as mentioned in #6361

### CODE REVIEW

**Comment by kpaigwar** [comment]
@umadevimcw thanks for the fix but I doubt we would be getting the runtime arg error as our sizes of tensor are bigger.

**Comment by umadevimcw** [comment]
> @umadevimcw thanks for the fix but I think we would be getting the same runtime arg error as we are dealing with much bigger tensors.

Yes, @kpaigwar. As I mentioned in the description it throws an error when the repeat count is 64.
 Since it depends on repeat op, if the repeat count exceeds 50 we are not able to run it and ended up in runtime error

**Review by eyonland — CHANGES_REQUESTED** [review]
Can this functionality be merged into the tt_lib.mul instead of creating an additional op?  It looks like we are only supporting broadcasting rules on the batch dimension here.  Why does this need to be a separate op?  @TT-BrianLiu  do you have thoughts here?

**Comment by umadevimcw** [comment]
Closing this PR (The same feature is supported In this PR #6587)

**Pull request closed without merging**
