### PR TITLE
#8531: delete all makefiles

### PR DESCRIPTION
**Pull request by TT-billteng**

### CODE REVIEW

**Review by tt-aho — APPROVED** [review]
lgtm

**Comment by mo-tenstorrent** [comment]
@vtangTT do we still need `tt_metal/tracy.mk`. Should we purge it as part of this commit as well?

**Review by tt-rkim — APPROVED** [review]

**Review by TT-BrianLiu — APPROVED** [review]

**Review by xanderchin — APPROVED** [review]

**Comment by vtangTT** [comment]
> @vtangTT do we still need `tt_metal/tracy.mk`. Should we purge it as part of this commit as well?

No I don't think we need it anymore.

**Review by mo-tenstorrent — CHANGES_REQUESTED** [review]
Can we remove `tracy.mk`

**Comment by tt-rkim** [comment]
@mo-tenstorrent pls check

**Review by mo-tenstorrent — APPROVED** [review]
Thanks

**Pull request merged**
