### PR TITLE
#0: Remove single core implementations of ops which are same as trivial multicore case

### PR DESCRIPTION
**Pull request by tt-aho**
Remove single core implementations of ops which are just trivial cases of the multicore implementation and doesn't support cases that multicore does not.

Fix and enable transpose_cn multi core implementation

### CODE REVIEW

**Review by TT-BrianLiu — APPROVED** [review]
Looks good sir

**Comment by davorchap** [comment]
> Looks good sir

making it real

**Review by davorchap — APPROVED** [review]

**Comment by TT-BrianLiu** [comment]
> > Looks good sir
> 
> making it real

Code reading speedrun any %

**Comment by tt-aho** [comment]
Passing post commit: https://github.com/tenstorrent/tt-metal/actions/runs/9142364279

**Review by davorchap — APPROVED** [review]

**Review by eyonland — APPROVED** [review]

**Pull request merged**
