### PR TITLE
Syrmia/new sweeps

### PR DESCRIPTION
**Pull request by nemanjagrujic**
Testing by Syrmia in this PR enables ops sweeps, for the newly added tt_dnn ops, for GS and WHB0.

### CODE REVIEW

**Review by boris-drazic — APPROVED** [review]

**Review by muthutt — CHANGES_REQUESTED** [review]
Can you delete this file ?

tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/pytorch_eltwise_atan2_test copy.yaml

**Review by muthutt — COMMENTED** [review]
If this test is not working,
tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/pytorch_eltwise_isfinite_test.yaml

why are you adding it in both places  ? Shouldn't we just keep it in the not-working-unit-tests folder and then move it here when the problem is resolved ?

**Comment by nemanjagrujic** [comment]
> Can you delete this file ?
> 
> tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/pytorch_eltwise_atan2_test copy.yaml

@muthutt Deleted

**Comment by nemanjagrujic** [comment]
> If this test is not working, tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/pytorch_eltwise_isfinite_test.yaml
> 
> why are you adding it in both places ? Shouldn't we just keep it in the not-working-unit-tests folder and then move it here when the problem is resolved ?

@muthutt That is sweep for grayskull card and there `isfinite` operation is working. So for grayskull sweep is in working folder and for wormhole sweep is in broken folder.

**Comment by nemanjagrujic** [comment]
> Can you delete this file ?
> 
> tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/pytorch_eltwise_atan2_test copy.yaml

@muthutt Deleted

**Comment by nemanjagrujic** [comment]
> If this test is not working, tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/pytorch_eltwise_isfinite_test.yaml
> 
> why are you adding it in both places ? Shouldn't we just keep it in the not-working-unit-tests folder and then move it here when the problem is resolved ?

@muthutt This file is for Grayskull card. Operation works on Grayskull.

**Review by muthutt — APPROVED** [review]
LGTM - all concerns about duplication are addressed and by work of MCW engineers we have moved the non-working to working tests. thanks @umadevimcw  & team, as well as @nemanjagrujic & team

**Pull request merged**
