### PR TITLE
Modify tt_tensors_to_torch_tensors utility function to untilize on device instead of cpu

### PR DESCRIPTION
**Pull request by skhorasganiTT**
- Modify tt_tensors_to_torch_tensors utility function to untilize on device instead of cpu
- Modify Falcon7b perf test to use tt_tensors_to_torch_tensors instead of tt2torch_tensor
- Improvements in single-chip e2e performance for Falcon7b demo (perf mode): +13% for prefill, +4% for decode
- Improvements in multi-chip (8 chips) e2e performance for Falcon7b demo (perf mode): +45% for prefill, +12% for decode

### CODE REVIEW

**Comment by skhorasganiTT** [comment]
Post-commit models tests: https://github.com/tenstorrent/tt-metal/actions/runs/9024337178
Single-chip perf tests: https://github.com/tenstorrent/tt-metal/actions/runs/9024314252
Multi-chip perf tests: https://github.com/tenstorrent/tt-metal/actions/runs/9024320349

**Comment by skhorasganiTT** [comment]
@cglagovichTT Would you be able to check if this change works for llama2 and yields any e2e improvement since `tt_tensors_to_torch_tensors` is used in `llama_generation.py`?

**Review by arakhmati — APPROVED** [review]

**Review by tt-asaigal — APPROVED** [review]

**Comment by davorchap** [comment]
great!

**Comment by cglagovichTT** [comment]
I'm experimenting with multidevice tensors so my `llama_generation.py` now uses this pattern
```
        logits = ttnn.to_torch(
            tt_logits, device=self.device_mesh, mesh_composer=ConcatMeshToTensor(self.device_mesh, dim=3)
        )
```

Maybe I can explicitly untilize before composing?

**Review by boris-drazic — APPROVED** [review]

**Pull request merged**
