### PR TITLE
fix permission error bug when reading 'demote' file in hugepages setup

### PR DESCRIPTION
**Pull request by changh95**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/11825)

### Problem description
When setting up environment for TT-Buda, users are expected to run setup_hugepages.py.
This should run flawlessly, but an exception arises during the script and there's no way to fix it other than fixing the Python script.

There's a file called 'demote' in '/sys/kernel//mm/hugepages/hugepages-1048576kB/'.
From what I remember, this file does not have read permission.
This causes the python script to fail to read the item size, even with sudo.

### What's changed

I tried giving permission to 'demote', but it just doesn't seem to work.
So instead, we just simply skip reading stuffs about 'demote', and carry on creating hugepages environment.

This is a screenshot after I updated the script.

image

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by JushBJJ** [comment]
Thanks for fixing this, I actually had this issue before but I thought this was just a problem specific to my machine. I had to weirdly use TT-Buda's hugepages script (before it got updated i think) to setup hugepages.

**Comment by tt-rkim** [comment]
Thank you so much!

Could you please describe the system you're testing on locally, especially Ubuntu (I'm assuming that's what you're using) version and linux kernel version?

**Comment by JushBJJ** [comment]
> Thank you so much!
> 
> Could you please describe the system you're testing on locally, especially Ubuntu (I'm assuming that's what you're using) version and linux kernel version?

At that time I was using Linux Mint 21 (which is just based on Ubuntu 22.04) on Kernel 6.5.0-45-generic. My memory is a bit fuzzy on whether running the hugepages script worked at first-time or not, but I have tried running it a couple of times because I had a couple of issues setting up TT-Metal and Buda. I suspect that `/sys/kernel//mm/hugepages/hugepages-1048576kB/` was generated after the first run causing the error if you run setup_hugepages.py again

**Comment by tt-rkim** [comment]
Something with how hugepages interface is implemented in 22.04 and onwards is different. The script we provide here is very locked to how 20.04 does things and is not ideal. It's something on our to-do list to redo this convenience script.

I now see in @changh95 's original issue, the system was 24.04.

@JushBJJ did you get a chance to try this change out?

**Comment by JushBJJ** [comment]
Just tried this change, yeah the original script still has the Permission denied error and when I put the patch in the check passes with no issues.

Is doing only the hugepages check enough? Or do you want me to do the first_pass and second setup as well

**Comment by tt-rkim** [comment]
And let us know how it goes

**Comment by JushBJJ** [comment]
@tt-rkim first pass and enabling works, haven't noticed anything out of the ordinary upfront with the patch. Not sure what your plans are for hugepages but if people are running the script multiple times (either by accident or to verify like me lol) it probably wont break their system.

**Comment by tt-rkim** [comment]
@ttmchiou Just wanted your quick approval, this shouldn't be a problem for 20.04 right?

**Comment by tt-rkim** [comment]
and we should copy it over to MIW?

**Review by tt-rkim — APPROVED** [review]

**Comment by ttmchiou** [comment]
Shouldn't be a problem with this change

**Review by ttmchiou — APPROVED** [review]

**Comment by changh95** [comment]
CI will pass now as the code is formatted using black :+1:

**Comment by TT-billteng** [comment]
thank you for the contribution @changh95 !

**Pull request merged**
