### PR TITLE
#0: Cache program cmds, convert cb configs from write linear to write packed

### PR DESCRIPTION
**Pull request by tt-aho**
TODO here is to get rid of the cb updates, or at least optimize them when we are hitting cache.
Will do this in a separate pr once it's completed.

### CODE REVIEW

**Comment by aliuTT** [comment]
Another TODO: write configs for cbs 0 to MAX_USED, as opposed to 0 to MAX_CBS

**Comment by tt-aho** [comment]
Passing post commit: https://github.com/tenstorrent/tt-metal/actions/runs/9143474826/job/25140559669

**Comment by tt-aho** [comment]
I had to back out a change that changes the CB page size assertion from being a multiple of 4 to a multiple of 16 as it seems like a number of ops are setting cb page sizes < 16. This may be okay if they aren't actually using the sync mechanisms of cbs but I think we should have this assertion since cbs are expected to work on 16B words

**Review by pgkeller — APPROVED** [review]

**Review by pgkeller — APPROVED** [review]

**Comment by abhullar-tt** [comment]
> I had to back out a change that changes the CB page size assertion from being a multiple of 4 to a multiple of 16 as it seems like a number of ops are setting cb page sizes < 16. This may be okay if they aren't actually using the sync mechanisms of cbs but I think we should have this assertion since cbs are expected to work on 16B words

ah yeah #4040 is still open

**Review by aliuTT — APPROVED** [review]

**Review by ntarafdar — APPROVED** [review]

**Review by abhullar-tt — APPROVED** [review]

**Pull request merged**
