### PR TITLE
#5314: Only stall on first scheduled read after commands with side effects

### PR DESCRIPTION
**Pull request by DrJessop**

### CODE REVIEW

**Review by pgkeller — APPROVED** [review]
Hard to tell if all cases were covered, but the concept looks good.

**Comment by DrJessop** [comment]
@pgkeller  Would it be easier if I mark all commands with side effects in some map, and have enqueue_program set the value of the flag based on whether the command is in the map or not?

**Review by pgkeller — APPROVED** [review]

**Review by TT-billteng — CHANGES_REQUESTED** [review]
don't think you need to bump taskflow for this?

**Comment by DrJessop** [comment]
@TT-billteng that was an accidental change, thanks for catching.

**Review by TT-billteng — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Pull request merged**
