### PR TITLE
Fix yolov4 demo

### PR DESCRIPTION
**Pull request by punithsekar**
### Problem description
Fix Yolov4 Demo , a similar PR #13163 

### What's changed
Reshaped with 255 instead of 256.

### Checklist
- [x] Post commit CI passes

### CODE REVIEW

**Review by dvartaniansTT — APPROVED** [review]
LGTM

**Review by dvartaniansTT — CHANGES_REQUESTED** [review]
the changes LGTM. but pls 

1. automate the weights download for the demo as well. 
2. I ran into error trying to run the demo: 
`FAILED models/experimental/yolov4/demo/demo.py::test_yolov4_model[device_params0] - RuntimeError: TT_FATAL @ ../tt_metal/impl/buffers/buffer.cpp:38: valid_page_size`

**Comment by punithsekar** [comment]
Hi @dvartaniansTT,
- The weight automation for demo file is available in PR #13526.
- I didn't face any issues running the demo. I will check it again and get back to this.

**Comment by punithsekar** [comment]
[Link](https://github.com/tenstorrent/tt-metal/actions/runs/11302115657) for CI, in progress .

**Comment by punithsekar** [comment]
Passing CI [Link](https://github.com/tenstorrent/tt-metal/actions/runs/11302115657)!

**Review by dvartaniansTT — APPROVED** [review]
LGTM

**Comment by punithsekar** [comment]
Current CI pipeline link https://github.com/tenstorrent/tt-metal/actions/runs/11331209491 - In progress

**Pull request merged**
