### PR TITLE
#0: remove calls of noc_coordinates in tests

### PR DESCRIPTION
**Pull request by nhuang-tt**
- The noc_coordinates API is replaced with using dram bank id

### Ticket
Link to Github Issue

### Problem description
Provide context for the problem.

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by ntarafdar — APPROVED** [review]
Big change and makes things easier to read. Good job

**Review by SeanNijjar — APPROVED** [review]
nice! Super excited for virtual coords to land. Gunna be huge

**Review by bbradelTT — APPROVED** [review]

**Comment by nhuang-tt** [comment]
Changes were integrated into https://github.com/tenstorrent/tt-metal/pull/15810 and merged

**Comment by tt-asaigal** [comment]
Thanks @nhuang-tt :)

**Pull request closed without merging**
