### PR TITLE
#5147: Update ttnn.clamp_bw

### PR DESCRIPTION
**Pull request by VirdhatchaniKN**
Work Done : 

- Update `clamp_bw` golden function
- Update `rpow_bw`, `polygamma_bw`, `div_no_nan_bw` documentation
- Test File : `tests/ttnn/unit_tests/operations/eltwise/backward/test_backward_clamp.py` : PASSED

### CODE REVIEW

**Review by Aswinmcw — APPROVED** [review]
LGTM

**Review by umadevimcw — CHANGES_REQUESTED** [review]

**Review by umadevimcw — APPROVED** [review]

**Review by eyonland — APPROVED** [review]

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11360152129 - passed

**Review by ayerofieiev-tt — APPROVED** [review]
Do we also have a clip_bw which is the same or alias?

**Comment by VirdhatchaniKN** [comment]
> Do we also have a clip_bw which is the same or alias?

Will work on this here : https://github.com/tenstorrent/tt-metal/issues/13967

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11396934871 - passed

**Pull request merged**
