### PR TITLE
#15079: make ProgramCache::is_enabled_ initialized out-of-line

### LINKED ISSUE #15079: [Bug Report] Inconsistent cache enabling behavior when using Clang-17 with tt-metal
**Describe the bug**
**This appears to be a compiler bug with Clang-17, but can be worked around in TT-Metal**
Please refer to the tt-metalium channel on TT Discord for some further context and compiler/linker combinations used, but the behavior appears to be consistent whenever `clang` is used as the compiler

Under some circumstances (in my case, compiling a project that uses tt-metal as a submodule), there is a bug with `static inline` declaration within the compiler that causes `ProgramCache::is_enabled_` to have two different values at different addresses, despite being marked `static`. This causes part of the final program to believe that cache is enabled while tt-metal sees that it is disabled.

Changing this to be an out-of-line initialization on its own translation unit makes this behavior goes away.

**To Reproduce**
1. Create a project that uses tt-metal as a submodule.
2. Compile with `clang-17`
3. Attempt to enable the program cache on a device
4. Observe the behavior where some part of the program sees cache enabled while other sees it disabled

**Expected behavior**
Cache should be enabled when `enable_program_cache()` is called

**Screenshots**
For the purpose of debugging a Python binding is added to query the cache status. This will result in two different query attempts at the `is_enabled_` variable

<details>
<summary>Clang 17-compiled tt-metal.</summary>
Note how a single object accesses two different `is_enabled_` fields of `ProgramCache`:

Image
</details>

<details>
<summary>GCC 12-compiled tt-metal.</summary>
Note how the object accesses the same `is_enabled_` field of `ProgramCache`:

Image
</details>

<details>
<summary>Clang 17-compiled tt-metal with proposed fix (out of line declaration)</summary>
Note how the object accesses the same `is_enabled_` field of `ProgramCache`:

Image
</details>

**Please complete the following environment information:**
- OS: Ubuntu 22.04.5 & Ubuntu 20.04.3
- Version of software: `main` branch @ 2665f88
- Clang version 17.0.6 (++20231209124227+6009708b4367-1~exp1~20231209124336.77)
- gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0

**Additional context**
Please check the Discord conversation (as mentioned) for more context as to why a buggy compiler was determined to be the cause of the issue

### PR DESCRIPTION
**Pull request by o2buzzle**
### Ticket
Closes #15079

### Problem description
`is_enabled_` being initialized inline causes weird inconsistent behavior when compiled with clang-17

### What's changed
- Create a new translation unit for `program_cache`
- Initialize the static variable out-of-line

### Checklist
- [x] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by razorback3 — APPROVED** [review]

**Review by tt-aho — COMMENTED** [review]
@tt-asaigal there is no reason for is_enabled_ to be static right?  Program cache is per device, so the correct fix here would be to just remove `inline static`?

**Comment by tt-asaigal** [comment]
> @tt-asaigal there is no reason for is_enabled_ to be static right? Program cache is per device, so the correct fix here would be to just remove `inline static`?

Yeah there is no reason for this flag to be static. Program cache is per device and this flag should be managed at an instance level.

**Comment by o2buzzle** [comment]
@tt-aho I have no idea about that since it was committed that way in a commit where the message was "Make program cache per device". I thought that the intention was that the program cache would be per-device, but would be enabled or disabled for all of them when toggled on or off. 

I'll change this PR to just make it an instance variable

**Review by tt-aho — APPROVED** [review]

**Comment by o2buzzle** [comment]
CI build is passing: https://github.com/tenstorrent/tt-metal/actions/runs/11886920624

Since this should not have impacts on operations, I am merging this now

**Pull request merged**
