### PR TITLE
#7712: Update elu, erf variant sweep config and doc

### PR DESCRIPTION
**Pull request by umadevimcw**
### Ticket
#7712 

### Problem description
Documentation missing for few ops with supported params

### What's changed
-Updated doc and corresponding sweep test files
- Moved old sweep to new sweep

### Checklist
- [x] [Post commit CI passes](https://github.com/tenstorrent/tt-metal/actions/runs/11051726367)
- [x] [ELU sweep](https://github.com/tenstorrent/tt-metal/actions/runs/11120038480)
- [x] [erf inv sweep](https://github.com/tenstorrent/tt-metal/actions/runs/11120671857)
- [x] [erf sweep](https://github.com/tenstorrent/tt-metal/actions/runs/11120661762)
- [x] [erfc sweep](https://github.com/tenstorrent/tt-metal/actions/runs/11120667859)

### CODE REVIEW

**Review by Aswinmcw — APPROVED** [review]
LGTM

**Review by bharane-ab — APPROVED** [review]

**Review by ruthreshx — APPROVED** [review]
LGTM

**Review by VirdhatchaniKN — APPROVED** [review]

**Review by mcw-anasuya — APPROVED** [review]

**Review by eyonland — APPROVED** [review]

**Review by eyonland — CHANGES_REQUESTED** [review]
Please move these tests.

**Review by jdesousa-TT — APPROVED** [review]
Please run the new sweeps through the `ttnn - run sweeps` pipeline before merging. Ty

**Review by eyonland — APPROVED** [review]

**Review by ayerofieiev-tt — APPROVED** [review]

**Pull request merged**
