### PR TITLE
Forward op test

### PR DESCRIPTION
**Pull request by umadevimcw**
PR to fix the issue reported here : https://github.com/tenstorrent-metal/tt-metal/issues/6722

Unit test: https://github.com/tenstorrent-metal/tt-metal/blob/cc94f01a548edccfa66483aeabdb6eaee05feb8e/tests/tt_eager/python_api_testing/sweep_tests/pytests/tt_dnn/test_eltwise_unary.py#L808C6-L808C12

Sweep test: https://github.com/tenstorrent-metal/tt-metal/blob/main/tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/pytorch_eltwise_asin_test.yaml

### CODE REVIEW

**Review by eyonland — COMMENTED** [review]
Why were no tests required to be updated on this PR?

**Comment by umadevimcw** [comment]
> Why were no tests required to be updated on this PR?

@eyonland This PR is to fix the reported issue https://github.com/tenstorrent-metal/tt-metal/issues/6722. Hence there is no separate test file

**Comment by umadevimcw** [comment]
@eyonland For this fix we have to copy-paste the code mentioned in the issue #6722 and run. Please find the attached output for your reference.
image


Also we have unit test and sweep test files for the same. Tested those with these changes and it is working

**Review by eyonland — APPROVED** [review]
Please update the description with the reference to the test going forward.

**Review by arakhmati — APPROVED** [review]

**Review by rtawfik01 — APPROVED** [review]

**Comment by eyonland** [comment]
Given that we are building AI hardware, I believe that we would never want an operation to ever create a NaN value.
Once you create a NaN value the entire AI model becomes invalid.   So while this fixes a test that now allows us to match the cpu calculation it sounds like this PR had an unfortunate negative impact on performance.  @umadevimcw, do you have the performance impact?

**Comment by umadevimcw** [comment]
@jliangTT  @eyonland and @rtawfik01 We are collecting perf numbers for the ops that are similar to this PR. Will share the results here once the data is ready. Based on the data will can decide to proceed further.

**Comment by umadevimcw** [comment]
@eyonland @rtawfik01 @jliangTT @razorback3 @hschoi4448 Please find the perf data for the ops were we have added the condition to handle nan/inf cases.

In the image
with condition --> Refer to `v_if` added to handle the nan/inf cases
w/o condition --> Refer to no v_if statement in code

Data includes the average value of 10 iterations for 1x3x384x320

Please share your inputs on the same

Screenshot from 2024-04-23 19-01-39

cc: @Aswinmcw

**Comment by razorback3** [comment]
> @eyonland @rtawfik01 @jliangTT @razorback3 @hschoi4448 Please find the perf data for the ops were we have added the condition to handle nan/inf cases.
> 
> In the image with condition --> Refer to `v_if` added to handle the nan/inf cases w/o condition --> Refer to no v_if statement in code
> 
> Data includes the average value of 10 iterations for 1x3x384x320
> 
> Please share your inputs on the same
> 
> Screenshot from 2024-04-23 19-01-39
> 
> cc: @Aswinmcw

@eyonland 
I think creating nan values for unsuitable input is necessary. I also understand your opinion that performance impact is important.
However, from the user's perspective, it is very important that the framework outputs nan/inf values if their models are incorrectly designed.
If not, it would cause silent data corruption and make it very hard to develop the model.

Question to @umadevimcw,
- Why is performance gap much bigger in Wormhole then Grayksull?
- Do you have data of performance that measures entire program? (start of program ~ end of program)

**Comment by razorback3** [comment]
Any comment or update for this?
@adifrancescoTT

**Comment by eyonland** [comment]
Please look at both #8944 and #8945 and look at what @ttmtrajkovic commented.   Essentially we want to document how NaN, -0.0 and Inf are supported.  If there is a special case where an op has to be developed that we absolutely need then we need to build those ops case by case.  We talked also about the possibility of adding a flag to ops whereby the ops runs on RISC to handle those special cases.

**Pull request closed without merging**
