### PR TITLE
Ngrujic/check sweeps 1

### PR DESCRIPTION
**Pull request by nemanjagrujic**

### CODE REVIEW

**Review by boris-drazic — APPROVED** [review]

**Comment by mo-tenstorrent** [comment]
Thanks for the update Nemanja? How long do these sweeps take? Is there a shorter version of them we can run as part of profiler regression.

**Comment by nemanjagrujic** [comment]
> Thanks for the update Nemanja? How long do these sweeps take? Is there a shorter version of them we can run as part of profiler regression.

@mo-tenstorrent Time varies but its in tens of seconds. like 15-60 seconds. We can make shorter version for regression.

**Comment by mo-tenstorrent** [comment]
15-60 seconds in total or per test? 60 seconds is very reasonable and we should add these tests to regression and do a quick high level sanity check on them similar to here 
https://github.com/tenstorrent-metal/tt-metal/blob/ea1c3db94182805b9503285248357e74de4eaaab/tests/scripts/run_profiler_regressions.sh#L48

**Comment by nemanjagrujic** [comment]
@mo-tenstorrent 60 sec in total. We can add that regression once allocation is fixed so it does not crash.

**Pull request closed without merging**
