### PR TITLE
#6737: Fix erfc

### PR DESCRIPTION
**Pull request by VirdhatchaniKN**
Issue : #6737 
Fix provided for forward erfc op
All post-commit tests - [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8554877546) - PASSED
Test results : [Link](https://github.com/tenstorrent-metal/tt-metal/pull/7106#issuecomment-2044164668)

### CODE REVIEW

**Review by eyonland — CHANGES_REQUESTED** [review]
Do we already have a test (maybe a sweep test?) that is already failing that you can reference in the description before I approve?
If we do not have a test for this, can we please make a unit test?

**Comment by VirdhatchaniKN** [comment]
I ran the following sweeps tests that were already available and have attached their results: 

- File : `tests/ttnn/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/wormhole/ttnn_eltwise_erfc_test.yaml` : [eltwise_erfc_sweep.csv](https://github.com/tenstorrent-metal/tt-metal/files/14913682/eltwise_erfc_sweep.csv)

- File : `tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/wormhole/pytorch_eltwise_erfc_test.yaml` : [eltwise_erfc_sweep.csv](https://github.com/tenstorrent-metal/tt-metal/files/14913697/eltwise_erfc_sweep.csv)

- File : `tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_working/grayskull/pytorch_eltwise_erfc_test.yaml` : [eltwise_erfc_sweep.csv](https://github.com/tenstorrent-metal/tt-metal/files/14913705/eltwise_erfc_sweep.csv)

**Review by eyonland — APPROVED** [review]
Please add the reference to the existing tests in the description going forward.  Thanks

**Review by rtawfik01 — APPROVED** [review]

**Comment by VirdhatchaniKN** [comment]
All post-commit tests : [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8701565023)
Slow Dispatch unit tests : [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8701567950)
Fast Dispatch unit tests : [Link](https://github.com/tenstorrent/tt-metal/actions/runs/8701566475)
All tests passed

**Pull request merged**
