### PR TITLE
#5354: Added separate function for resnet-50.

### PR DESCRIPTION
**Pull request by shwetankTT**

### CODE REVIEW

**Comment by tapspatel** [comment]
Can we add also skip option for resnet18. The error is when run locally
```
Statically allocated circular buffers in program 73 clash with L1 buffers on core range [(x=0,y=0) - (x=11,y=1)]. L1 buffer allocated at 831264 and static circular buffer region ends at 1040420
```

**Comment by shwetankTT** [comment]
> And this passes locally?

yes

**Comment by shwetankTT** [comment]
> Can we also add skip option for resnet18. The error is when run locally
> 
> ```
> Statically allocated circular buffers in program 73 clash with L1 buffers on core range [(x=0,y=0) - (x=11,y=1)]. L1 buffer allocated at 831264 and static circular buffer region ends at 1040420
> ```

That error should be fixed by now after @tt-rkim 's. checkin
.

**Review by tt-rkim — APPROVED** [review]
if you verified locally no need. This runs on nightly anyway. I trust you. Let's get this in

**Comment by shwetankTT** [comment]
@arakhmati and @eyonland Can you guys take a look. I need one code owner's review to merge this.

**Review by arakhmati — APPROVED** [review]

**Review by tapspatel — APPROVED** [review]

**Pull request merged**
