### PR TITLE
Kalaivani/composite oot

### PR DESCRIPTION
**Pull request by KalaivaniMCW**
Add optional output tensor to addalpha op using `std::optional<Tensor>& output_tensor`

### CODE REVIEW

**Comment by davorchap** [comment]
Is this OP a P0 blocker for Moreh MNIST training?

fyi @artem @eyonland

**Comment by KalaivaniMCW** [comment]
> Is this OP a P0 blocker for Moreh MNIST training?
> 
> fyi @artem @eyonland

No @davorchap it is not related to Moreh MNIST training. It is part of output tensor requirement but not MNIST.

**Comment by KalaivaniMCW** [comment]
Add optional output tensor to addalpha op using `std::optional<std::reference_wrapper<Tensor>> output_tensor`
image
Screenshot 2024-06-02 at 3 06 12 AM

**Comment by KalaivaniMCW** [comment]
Keeping this alternate approach for reference.

**Pull request closed without merging**
