### PR TITLE
#2262: Include split kernels in compute_kernel_api

### PR DESCRIPTION
**Pull request by ntarafdar**
This adds the split compute kernels within compute_kernel_api for single source of truth.

Also includes split ckernel_sfpu within ckernel_sfpu for grayskull. Wormhole in subsequent PR.

### CODE REVIEW

**Review by kkwong10 — APPROVED** [review]
This LGTM from a kernel usage perspective, however, the better person to review these changes are @muthutt. He was the one who added most of these new flavors of sfpu.  Do we have a perf/accuracy suite for each of those SFPU that we need to start running for wormhole to ensure accuracy/perf?

**Review by muthutt — COMMENTED** [review]
@tarafdarTT - could you check this branch against the WH tests in my branch ?
https://github.com/tenstorrent-metal/tt-metal/pull/2279

**Review by muthutt — CHANGES_REQUESTED** [review]
I can understand removing the _sfpu_ prefix; however please keep function names with _opt suffix in place.

**Review by muthutt — APPROVED** [review]
LGTM - but - please wait until the WH B0 Python tests and @kkwong10  code for WH B0 are check-in before you merge this;
thanks

**Pull request merged**
