### PR TITLE
Mo/7248 add op to op time

### PR DESCRIPTION
**Pull request by mo-tenstorrent**
Adding the cache option for device information on cached ops. 

Include the op to op column to op report

### CODE REVIEW

**Comment by mo-tenstorrent** [comment]
Sample CSV with op to op column. 

Screenshot 2024-04-12 at 12 23 36 PM
[ops_perf_results_2024_04_12_14_18_45.csv](https://github.com/tenstorrent-metal/tt-metal/files/14961165/ops_perf_results_2024_04_12_14_18_45.csv)

**Comment by mo-tenstorrent** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8666032074 post commit

**Review by eyonland — APPROVED** [review]

**Comment by mo-tenstorrent** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8667704229 profiler reg. after slight mods

**Comment by mo-tenstorrent** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8667696878/job/23771228419 Device Pef

**Comment by mo-tenstorrent** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8690180924 Post commit after rebase

**Pull request merged**
