### PR TITLE
#8174: [WIP] Replace ttlib custom Falcon matmuls with ttnn matmuls

### PR DESCRIPTION
**Pull request by TT-BrianLiu**

### CODE REVIEW

**Comment by TT-BrianLiu** [comment]
I am still debugging PCC drop from the switches and also need to make sure perf isn't impacted, but I want to get some early feedback from Falcon7B model owners.

**Comment by s-jovic** [comment]
Thanks for doing the cleanup! I guess the main diff is that ttnn and legacy falcon cpp functions generate program config in a different way? Prefill-side, I think this should be ok since we already set explicit program config for perf-impacting matmuls.

One note though, there are two paths for prefill currently - optimized and the currently used one. I am preparing a PR for today that will switch to using this optimized version for relevant seq lens (128, 1k and 2k), so it might be good to see the pcc/perf once the switch is made.

**Comment by TT-BrianLiu** [comment]
> Thanks for doing the cleanup! I guess the main diff is that ttnn and legacy falcon cpp functions generate program config in a different way? Prefill-side, I think this should be ok since we already set explicit program config for perf-impactful matmuls.
> 
> One note though, there are two paths for prefill currently - optimized and the currently used one. I am preparing a PR for today that will switch to using this optimized version for relevant seq lens (128, 1k and 2k), so it might be good to see the pcc/perf once the switch is made.

Sounds good. I will rebase and test after your changes.

**Review by bbradelTT — APPROVED** [review]

**Review by skhorasganiTT — APPROVED** [review]
Changes look good, thanks for doing this Brian. FYI @tt-asaigal, matmuls have been changed to ttnn, @TT-BrianLiu will run the multi-chip tests to verify async performance

**Comment by TT-BrianLiu** [comment]
Passing pipelines:
- Models perf pipelines: https://github.com/tenstorrent/tt-metal/actions/runs/9026077973

**Pull request closed without merging**
