### PR TITLE
#0: Make CoreRangeSet thread safe

### PR DESCRIPTION
**Pull request by tt-asaigal**
### Ticket
Link to Github Issue

### Problem description
The `CoreRangeSet` class uses a `std::set` to store the different core ranges, which is not thread-safe by default. In async mode, this object can be passed between readers and writers, as part of the `MemoryConfig` class. This was causing ND segfaults for models such as UNet.

### What's changed
Make the `CoreRangeSet` class thread-safe.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by abhullar-tt — APPROVED** [review]
does the mutex slow things down?

**Comment by tt-asaigal** [comment]
> does the mutex slow things down?
I looked at the perf with 2 worker threads w/ and w/o the mutex and didn't see any noticeable difference. I think the overhead of copying the set is pretty high in comparison.

This is a change to ensure that degenerate cases where folks are copying large objects don't segfault, though they shouldn't be performing this copy in the first place.

**Comment by dmakoviichuk-tt** [comment]
It feels like a little bit overkill to have a mutex in so low level class. Could you point me out how is it passed between different threads?

**Comment by tt-asaigal** [comment]
> It feels like a little bit overkill to have a mutex in so low level class. Could you point me out how is it passed between different threads? For example if its read only object there is chance we can garantee it will be created once and we can pass std::shared_ptr or even regular ptr to it instead of copying.

Hey @dmakoviichuk-tt for an example of a failing use case please take a look at the TTNN op:

`ExecuteUpSample::invoke(const ttnn::Tensor& input_tensor,
    std::variant<int, tt::tt_metal::Array2D, tt::tt_metal::Array3D, tt::tt_metal::Array4D> scale_factor,
    std::optional<MemoryConfig> output_mem_config)`
   
This function is called through the `invoke_composite` decorator, which will pass the `output_mem_config` data structure  between threads.
    
On an n-chip machine, this function will run inside n-worker threads with no guarantee of data structure accesses being ordered when we create a copy, which can lead to a segfault.

I agree with your approach of removing copies entirely by using shared pointers, since its also more performant. However, we can't rely on op writers to always do this (another example is the fold op).  The goal of this PR is to ensure that a workload doesn't crash when  an op writer exercises the less performant copy path.

Having said that, we should inform op writers to not create copies when passing `MemoryConfig` between functions.

**Comment by dmakoviichuk-tt** [comment]
@tt-asaigal why not make output_mem_config threadsafe then instead?
Also even in this example you see that we do unneeded copy of the output_mem_config :(

**Comment by tt-asaigal** [comment]
> @tt-asaigal why not make output_mem_config threadsafe then instead? Also even in this example you see that we do unneeded copy of the output_mem_config :( Reason that I am worried that it is a very simpel class and mitght be moving aroung in. alot of places and people will not ieven think that it might be costly.

Hey Denys, making just the `MemoryConfig` class thread-safe would not be enough to ensure that user code is completely safe. There is nothing stopping a user from, for example, passing another data structure that uses the `CoreRangeSet` class by copy. I understand that users may consider this to be a simple data structure that is cheap to copy, however, even without the mutex this was not the case.

``` quote
Also even in this example you see that we do unneeded copy of the output_mem_config
```

I brought this example to your attention, since it was performing an extra copy, with the point being that we should remove it, regardless of whether or not a mutex is used in the underlying implementation.

**Pull request merged**
