### PR TITLE
#13531: Update ttnn.clip

### LINKED ISSUE #13531: Update `ttnn.clip`
~- To Provide support for clamp_min, clamp_max~
- Update `ttnn.clip` and its dependant op logic

Ref Link : https://github.com/pytorch/pytorch/blob/a569a8ac4c1eaaf1c3f241b0c09a6ed072570a26/torch/_refs/__init__.py#L1903

### PR DESCRIPTION
**Pull request by VirdhatchaniKN**
#13531

Work Done : 

- Update clip with clamp

### CODE REVIEW

**Review by Aswinmcw — APPROVED** [review]
LGTM

**Review by umadevimcw — APPROVED** [review]

**Review by eyonland — APPROVED** [review]

**Review by ayerofieiev-tt — APPROVED** [review]
In my opinion, ideally one is just an alias to the other. 
And no need to have larger set of tests

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11400274665 - passed

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11401963376 - passed

**Pull request merged**
