### PR TITLE
add link from metallium guide to multichip programming guide

### PR DESCRIPTION
**Pull request by SeanNijjar**
### Ticket
Link to Github Issue

### Problem description
Provide context for the problem.

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by davorchap** [comment]
Would be good to add the diagram of the Ethernet stack on Eth core

from top to bottom we have 3 levels:
- EDM 
- Ethernet APIs (sending packets, handshaking)
- Ethernet transfer command queue APIs (direct interfacing to the transfer command queue register interface) 

And then have section for each of these, you already have the text , would be good to have it structured in that way

**Comment by davorchap** [comment]
image

fyi @cfjchu 
- annotate Gateway WH that are not user visible 
- which should annotate our virtual device coordinates , where is (0,0), where is (7,3) (row, col)
- text should say 12.5 GB/s , 25 GB/s - -- GBps is close to Gbps and could be mis-read, it's usually used only for Gbps

**Comment by SeanNijjar** [comment]
> And then have section for each of these, you already have the text , would be good to have it structured in that way

You're right this was something that I wanted to add earlier but never got around to. I can add it.

**Comment by davorchap** [comment]
image


* Add fused Matmul+AllGather to the OP list

* lead with the stack picture EDM/Eth API/Transfer cmd queue
* then with the host side API CCL example 
* then with the list of supported OPs
* then micro-bench
* then all the impl details

**Comment by SeanNijjar** [comment]
Updating here: https://github.com/tenstorrent/tt-metal/pull/12363
(The PR is separate because it's from a direct in browser edit ).

**Comment by SeanNijjar** [comment]
The CCL doc diagram for TG has been saved for broader use/sharding.

@cfjchu if you need to expand on it or build off it, you can pick it up here
https://docs.google.com/document/d/10QKmbfQVBDN0hbOs3KQ_rmOiOrTJk8RBF7HF3G4NRpM/edit?usp=drive_web

**Pull request merged**
