### PR TITLE
#4252: Update to C++20

### PR DESCRIPTION
**Pull request by vtangTT**
Main blocker: our current native Boost 1.71 is not compatible with C++20, need to update to at least 1.76

Solution: using [BCP](https://www.boost.org/doc/libs/1_85_0/tools/bcp/doc/html/index.html) to get all the 1.76 headers we need and put it into `tt_metal/third_party/boost`

Benefit: no longer need Boost as a dependency

Right now it's ~~28M but there's fluff that can be removed (which I will be doing next)~~  ~26M

Otherwise pipelines are green: 
post-commit: https://github.com/tenstorrent/tt-metal/actions/runs/9307635869
device perf: https://github.com/tenstorrent/tt-metal/actions/runs/9307802729
model perf: https://github.com/tenstorrent/tt-metal/actions/runs/9307806541
uBenchmarks: https://github.com/tenstorrent/tt-metal/actions/runs/9280304528
nightly fd: https://github.com/tenstorrent/tt-metal/actions/runs/9307803453
tgg unit: https://github.com/tenstorrent/tt-metal/actions/runs/9310219977

### CODE REVIEW

**Comment by tt-aho** [comment]
Would it be a good idea to put the boost files in a submodule?

**Comment by yan-zaretskiy** [comment]
Why are we vendoring boost? 😢

**Comment by tt-rkim** [comment]
> Would it be a good idea to put the boost files in a submodule?

@tt-aho 
@vtangTT and @TT-billteng discussed, and they thought that the boost submodule itself was a little too large + wanted to ensure that people weren't 

This would mean going through all machines, documentation etc. and fully getting rid of system-installed Boost.

It would also ensure that people can't use boost libs, other than the ones that @vtangTT has checked in.

> Why are we vendoring boost? 😢

@yan-zaretskiy We use boost at some points in the repo. The specific version of boost we need for C++20 (I believe >= 1.76) is not the default that you get for 20.04 when installing it via `apt`. So it's either install the `1.76` version through `apt` and now have this cursed side-by-side installation and deal with the ramifications of that, or do something like this.

Other possibilities include submodule like @tt-aho said or use something like `FetchContent` or https://github.com/cpm-cmake/CPM.cmake .

In any case, I'm personally pushing for getting rid of use Boost use and dependence across our entire stack. I believe @TT-billteng feels similarly.

**Comment by vtangTT** [comment]
Sorry all, closing this PR bc of submodule issues. New PR here https://github.com/tenstorrent/tt-metal/pull/9070

**Pull request closed without merging**
