### PR TITLE
YoloV4 pipeline update 

### PR DESCRIPTION
**Pull request by keerthana-r-mcw**
### Problem description
Updated the pipeline with shard concat and replaced the fallback maxpool with ttnn.maxpool2d, remove skip statements for head,whole model pipeline.  Add input files to the repo.
### What's changed

- Changed the interleaved concat to shared concat in downsample2 and downsample3 as mentiontined in [#12182](https://github.com/tenstorrent/tt-metal/issues/12182). Other submodules were failing with this change as in [#12387](https://github.com/tenstorrent/tt-metal/issues/12387)
- Replaced the fallback maxpool with tthh.Maxpool2d
- Remove skip statements for head, whole model.
- Add input files to run demo.

### CODE REVIEW

**Comment by punithsekar** [comment]
Passing All post-commit tests CI [Link](https://github.com/tenstorrent/tt-metal/actions/runs/10809192148).

**Comment by punithsekar** [comment]
All post commit tests CI pipeline run is in progress https://github.com/tenstorrent/tt-metal/actions/runs/10876570979

**Comment by punithsekar** [comment]
Passing CI [link](https://github.com/tenstorrent/tt-metal/actions/runs/10876570979)

**Review by dvartaniansTT — APPROVED** [review]
LGTM! thanks

**Review by eyonland — APPROVED** [review]

**Comment by punithsekar** [comment]
Passing CI [Link](https://github.com/tenstorrent/tt-metal/actions/runs/10895648868).

**Pull request merged**
