### PR TITLE
[Llama2 Prefill] Model Functionality completed

### PR DESCRIPTION
**Pull request by kevin-mii**
1.  Prefill Model implemented in llama_model_optimized.py
2.  All data interleaved except for attn matmul slices.
3.  All tests passing in test_llama_model.py
- 80 layers prefill 128 seq_len passing with 0.994 PCC, 0.828 Top1, 0.984 Top5
- 80 layers prefill 2k seq_len passing with 0.992 PCC, 0.801 Top1, 0.991 Top5

### CODE REVIEW

**Comment by mikevin920** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8441579683

**Comment by mikevin920** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8441588545 :`freq_multi_device run`

**Comment by mikevin920** [comment]
all post_commit: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8442697378
freq_multi_device_tests: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8442704870

**Review by cglagovich — APPROVED** [review]

**Comment by mikevin920** [comment]
@eyonland @cfjchu @arakhmati Could you guys please take a look at this PR, all post commits passed and related multi-device tests. Thanks!

**Comment by mikevin920** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8472792612: `All post commits`
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8472795641: `multidevice tests`

**Review by cfjchu — APPROVED** [review]

**Pull request merged**
