### PR TITLE
Backward test updates

### PR DESCRIPTION
**Pull request by umadevimcw**
#6443

CI runs : https://github.com/tenstorrent-metal/tt-metal/actions/runs/8392058236

### CODE REVIEW

**Review by eyonland — COMMENTED** [review]
Did we not need a test change for this update?

**Comment by umadevimcw** [comment]
> Did we not need a test change for this update?
https://github.com/tenstorrent-metal/tt-metal/pull/6679 Once this PR is merged will submit the rest of the PR that includes test file changes

**Comment by eyonland** [comment]
Going forward, we really need to have a test included with the underlying change.  I'm approving but this should be the exception.

**Review by eyonland — APPROVED** [review]

**Comment by umadevimcw** [comment]
> Going forward, we really need to have a test included with the underlying change. I'm approving but this should be the exception.

@eyonland I have updated the tests in this PR as the depending PR was merged into the main. Please review those changes as well

**Review by tt-aho — APPROVED** [review]

**Review by eyonland — APPROVED** [review]
Thank you looks good!

**Pull request merged**
