### PR TITLE
Syrmia/ttnn sweeps

### PR DESCRIPTION
**Pull request by nemanjagrujic**
https://github.com/tenstorrent-metal/tt-metal/actions/runs/7542882305: https://github.com/tenstorrent-metal/tt-metal/actions/runs/7542882305

### CODE REVIEW

**Review by boris-drazic — APPROVED** [review]

**Comment by arakhmati** [comment]
I see `import tt_lib as ttl` inside of most of the newly added test files. It should not be used in `ttnn` tests. `tests/ttnn` folder is strictly meant for tests that are written using `ttnn` APIs.

If you look at `ttnn/tensor.py`, you will see that we have all the necessary mappings:
i.e.: `ttnn.bfloat16` for `ttl.tensor.DataType.BFLOAT16`

**Comment by nemanjagrujic** [comment]
> I see `import tt_lib as ttl` inside of most of the newly added test files. It should not be used in `ttnn` tests. `tests/ttnn` folder is strictly meant for tests that are written using `ttnn` APIs.
> 
> If you look at `ttnn/tensor.py`, you will see that we have all the necessary mappings: i.e.: `ttnn.bfloat16` for `ttl.tensor.DataType.BFLOAT16`

@arakhmati (cc @boris-drazic) Our sweeping infrastructure uses tt_lib constants, so in order to re-use testing infrastructure and not duplicate code we re-used existing methods and constants which are later mapped to ttnn constants when creating tensors. Maybe it's good to have a call to clear things out.

**Review by arakhmati — CHANGES_REQUESTED** [review]
Everything looks good but can you please add a folder `tests/ttnn/python_api_testing` and put `non_working_unit_tests` and `sweep_tests` under it?

**Comment by nemanjagrujic** [comment]
> I see `import tt_lib as ttl` inside of most of the newly added test files. It should not be used in `ttnn` tests. `tests/ttnn` folder is strictly meant for tests that are written using `ttnn` APIs.
> 
> If you look at `ttnn/tensor.py`, you will see that we have all the necessary mappings: i.e.: `ttnn.bfloat16` for `ttl.tensor.DataType.BFLOAT16`

@arakhmati Changed now in unit tests. Can you re check?

**Comment by nemanjagrujic** [comment]
Moved

**Review by arakhmati — APPROVED** [review]
Looks good!

**Pull request merged**
