### PR TITLE
#8356: Reduce verbosity on pytest to reduce reading load

### PR DESCRIPTION
**Pull request by tt-rkim**

### CODE REVIEW

**Comment by tt-rkim** [comment]
To show off

https://github.com/tenstorrent/tt-metal/actions/runs/9032887368
https://github.com/tenstorrent/tt-metal/actions/runs/9032885880

**Comment by tt-rkim** [comment]
@mo-tenstorrent @tt-aho  Any issues you see w/ device perf pipeline if we reduce verbosity?

**Comment by tt-aho** [comment]
Don't think so. Device perf isn't really where we should be debugging model errors (should be caught elsewhere) so I don't think the verbosity was too important there.

**Comment by tt-rkim** [comment]
@AleksKnezevic @yieldthought @cglagovich @nsmithtt @kpaigwar 
Any issues with reducing verbosity across all pipelines for pytest from `-vvv` to `-v`?

**Review by nsmithtt — APPROVED** [review]

**Pull request merged**
