### PR TITLE
#5148: Fix sqrt

### PR DESCRIPTION
**Pull request by Aswinmcw**
Handle inf/-inf conditions in sqrt bw op

All post commit test : https://github.com/tenstorrent-metal/tt-metal/actions/runs/8595377440

### CODE REVIEW

**Review by eyonland — CHANGES_REQUESTED** [review]
Do we already have a test (maybe a sweep test?) that is already failing that you can reference in the description before I approve?
If we do not have a test for this, can we please make a unit test?

**Comment by Aswinmcw** [comment]
> Do we already have a test (maybe a sweep test?) that is already failing that you can reference in the description before I approve? If we do not have a test for this, can we please make a unit test?

Hi @eyonland , in this PR i have handled inf cases for sqrt op, initially at some test cases, torch will give inf as output but TT gives nan and it will results as pass so this wont fix any failing tests, just ensure that both outputs will be same

**Comment by eyonland** [comment]
Are you saying that it is not possible to add a unit test that will fail without your change?

**Comment by Aswinmcw** [comment]
> Are you saying that it is not possible to add a unit test that will fail without your change?

@eyonland , if the input is zero, torch will give inf but TT will give nan and the unit test needs to be manually added it is not available in working or non working unit test dir, attaching the output for failing case and this PR will fix it
Screenshot 2024-04-12 at 9 07 05 PM

**Review by eyonland — CHANGES_REQUESTED** [review]
Please provide a test.

**Comment by Aswinmcw** [comment]
> Please provide a test.

@eyonland , i have added the failing unit tests to `tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_backward_sqrt.py`
Kindly review

**Review by eyonland — APPROVED** [review]

**Pull request merged**
