### PR TITLE
Fix s2i op when shard grid is larger than actual used grid

### PR DESCRIPTION
**Pull request by yugaoTT**
### Ticket
https://github.com/tenstorrent/tt-metal/issues/15004#issuecomment-2476975904
https://github.com/tenstorrent/tt-metal/issues/14902

### Problem description
Bug occured when running a matmul + s2i ops test, s2i op does not take account that some cores are unused in the passed in sharding grid, and writes extra data to output tensor, causing L1 corruption.

Fix is to let s2i use the correct num_cores in shard spec, and let mamtul produce the exact shard grid.

### Checklist
- [x] Post commit CI https://github.com/tenstorrent/tt-metal/actions/runs/11894930806
- [x] Blackhole Post commit https://github.com/tenstorrent/tt-metal/actions/runs/11862361147
- [x] nightly https://github.com/tenstorrent/tt-metal/actions/runs/11894947971
- [x] model perf https://github.com/tenstorrent/tt-metal/actions/runs/11894959587
- [x] t3k freq https://github.com/tenstorrent/tt-metal/actions/runs/11894967497

### CODE REVIEW

**Comment by sjameelTT** [comment]
Is this rebased onto Naif's changes for S2I/I2S from yesterday and have you tried BH post-commit with it?

**Comment by yugaoTT** [comment]
@sjameelTT it should have Naif's commit.
Will test BH

**Comment by TT-BrianLiu** [comment]
I think in the future, we should make shard spec store the exact grid. Is it possible to add an assert to s2i op that shard grid is exact? If that doesn't break tests, I think it's better. You would need to update matmul to output exact grid in this case

**Comment by yugaoTT** [comment]
@TT-BrianLiu the grid is not rectangle, I think if we want to make them exact , then there will be multple ranges, so matmul and s2i both needs to read multiple ranges. 
It's also bad for user to use, as in height/width sharded case, use might just want to avoid the trouble specifying the exact grid?

**Comment by TT-BrianLiu** [comment]
> @TT-BrianLiu the grid is not rectangle, I think if we want to make them exact , then there will be multple ranges, so matmul and s2i both needs to read multiple ranges. It's also bad for user to use, as in height/width sharded case, use might just want to avoid the trouble specifying the exact grid?

When ops iterate through the ranges, it's done with a helper which generates the cores so I think that shouldn't be an issue (maybe minor perf hit?). For users, we can still provide option to specify grid as essentially a boundary (which is what it is today), but we internally always store the exact grid. If we don't store exact grid, I have seen some use cases where it's confusing or error prone:
- Two sharded tensors like this: `[2, 1, 32, 64]` and `[10, 1, 32, 64]` sharded onto "same" shard spec with shard shape `[32, 64]` and shard grid `[8,8]`. If we want to check if the two tensors are sharded onto the same cores, we compare the shard spec, which is equal but it shouldn't be if we stored the actual shard grid.
- In cases like which you are fixing today, ops in general assume shard grid always contains data. With how it is today, they should actually always recompute actual shard grid, which is annoying.

**Review by bbradelTT — APPROVED** [review]

**Review by ntarafdar — APPROVED** [review]
great change @yugaoTT

**Review by tt-aho — APPROVED** [review]

**Pull request merged**
