### PR TITLE
migrate ccl dev guide to in repo markdown 

### PR DESCRIPTION
**Pull request by SeanNijjar**
### Ticket
No Issue - just publicizing some documentation

### Problem description
Migrating CCL dev guide from private document format to markdown format on repo.

### What's changed
Migrated CCL dev guide

To see the contents, you may need to open this in a codespace and preview the file in a markdown preview.

WIP:
- Still migrating images over

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by SeanNijjar** [comment]
FYI @mbahnasTT

**Comment by SeanNijjar** [comment]
FYI @davorchap

**Comment by davorchap** [comment]
image

I spoke to @cfjchu about visualizing link. 2 "black lines" per link are a little confusing, it seems as if they are 8 links between two adjacent WHs, or total of 32 links. It would be better to show a single black line for link, but have it arrows on both ends to show it's actually bi-directional 100 Gbps link (good to annotate that as well).

**Review by davorchap — APPROVED** [review]
Just change the visualizing the link as per my comment above.

and then ship it.

**Comment by SeanNijjar** [comment]
I've updated the images now. Cleaner and clearer, slightly less ugly too.

**Pull request merged**
