### PR TITLE
#10682: Generate run/measurement CSVs for Mamba single-card demo test

### PR DESCRIPTION
**Pull request by esmalTT**
### Ticket
#10682 

### Summary of changes
- Remove old prefill-by-decode demo code
- Integrate with BenchmarkProfiler to generate CSV for demo test
- Automatically select chunk sizes based on the input provided
- Use decode mode to fill hidden states if prompt is 32 tokens or less

### Checklist
- [ ] Post commit CI passes
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by kpaigwar — APPROVED** [review]

**Comment by tt-rkim** [comment]
This is for single card right? Haven't instrumented t3k mamba yet?

@skhorasganiTT are we generating falcon7b benchmarks for single card?

**Comment by skhorasganiTT** [comment]
@tt-rkim Yes, Mamba is only on single-card. For Falcon7b we are generating the CSVs but the data is not being sent to the server yet (assuming you haven't gotten to #10691 yet).

**Comment by tt-rkim** [comment]
Sounds good

Can you show in the logs via screenshot that the `run` + `measurement` files are being generated?

**Comment by esmalTT** [comment]
> Sounds good
> 
> Can you show in the logs via screenshot that the `run` + `measurement` files are being generated?

@tt-rkim Here you go:

[N150 demo pipeline log](https://github.com/tenstorrent/tt-metal/actions/runs/10267197287/job/28407619772#step:9:94743
)

Screenshot 2024-08-07 at 10 36 35 AM

[N300 demo pipeline log](https://github.com/tenstorrent/tt-metal/actions/runs/10267197287/job/28407620130#step:9:94743)

Screenshot 2024-08-07 at 10 39 52 AM

**Review by tt-rkim — APPROVED** [review]

**Pull request merged**
