### PR TITLE
#8098: Remove temp buffer copying when reading from hugepage to host buffer

### PR DESCRIPTION
**Pull request by tt-aho**
TODO: Currently we only release pages after processing all of them Should update to release as we go along to unblock device

### CODE REVIEW

**Review by pgkeller — APPROVED** [review]
nice!  any idea if this change affects any of the models we had regressions on?

**Review by davorchap — APPROVED** [review]

**Comment by tt-aho** [comment]
I need to look into it more. Didn't really see much difference on Resnet and there seemed to be some runtime variation on ci so will look at some of them with tracy.

**Comment by davorchap** [comment]
> I need to look into it more. Didn't really see much difference on Resnet and there seemed to be some runtime variation on ci so will look at some of them with tracy.

Some of the noise is due to "ondemand" governor: https://github.com/tenstorrent/tt-metal/issues/5281 ,  we should switch on Monday to "performance".

Another source of the noise could be the completion thread -- we may need set it's affinity to pin it down to a core, and also tune yield/sleep use. 
@tt-asaigal found that pinning down worker threads for the issue queue was a reduction in noise and a perf improvement.

**Comment by tt-aho** [comment]
Yes, on ci for resnet there is a lot of noise. We're able to sometimes get as low as ~0.008s for avg inf time, but it sometimes goes above ~0.016s and we fail the bound check, so I need to relax the check, but this is huge variation.

**Review by arakhmati — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Pull request merged**
