### PR TITLE
Profiling OP base class

### PR DESCRIPTION
**Pull request by mo-tenstorrent**

### CODE REVIEW

**Review by mywoodstock — DISMISSED** [review]
BMM LGTM!

**Review by TT-billteng — CHANGES_REQUESTED** [review]
I think we should start using this library https://github.com/Neargye/magic_enum for string <-> enum conversions @kkwong10 @tt-rkim @arakhmati

**Review by TT-BrianLiu — COMMENTED** [review]
Layernorm and softmax have also been uplifted. Can you rebase and add profiling for these as well?

**Review by arakhmati — DISMISSED** [review]

**Review by TT-billteng — DISMISSED** [review]

**Review by ashayestehmanesh — DISMISSED** [review]

**Review by mywoodstock — DISMISSED** [review]

**Review by tt-rkim — APPROVED** [review]
my files lgtm

* LICENSE in magic_enum
* lfs update

**Review by arakhmati — APPROVED** [review]

**Review by TT-BrianLiu — APPROVED** [review]

**Review by tt-aho — APPROVED** [review]

**Review by abhullar-tt — APPROVED** [review]

**Review by ashayestehmanesh — APPROVED** [review]

**Review by mywoodstock — APPROVED** [review]

**Review by TT-billteng — APPROVED** [review]

**Review by davorchap — APPROVED** [review]

**Review by farbabi — APPROVED** [review]

**Pull request merged**
