### PR TITLE
Remove do while(0) from assert.hpp

### PR DESCRIPTION
**Pull request by ayerofieiev-tt**
### Ticket
None

### Problem description
We use do while in TT_FATAL and TT_ASSERT
This is to ensure that macro correctly acts as a single statement even inside other if statements.

Imagine
```
if (condition)
    TT_FATAL(some_condition, "Error occurred");
else
    do_something();
```
without it, macro expands into
```
if (condition)
    if (!(some_condition)) {
        tt::assert::tt_throw(...);
        __builtin_unreachable();
    }
else
    do_something();
```

### What's changed
Replace do while with { } block to not confuse clang tidy.
This makes macro expand into its own block, isolating it from the outside context

```
if (condition)
{
    if (!(some_condition)) {
        tt::assert::tt_throw(...);
        __builtin_unreachable();
    }
}
else
    do_something();
```

### Checklist
https://github.com/tenstorrent/tt-metal/actions/runs/11370868935
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by dmakoviichuk-tt — APPROVED** [review]

**Comment by dmakoviichuk-tt** [comment]
@blozano-tt  it is some oldschool thing :)
Overall in more complex macroses (which we don't need to have at all in modern c++) it is a good way to leave the macros scope using break anywhere inside.

**Comment by blozano-tt** [comment]
For some reason compiler doesn't like it here:

```
../ttnn/cpp/ttnn/operations/kv_cache/device/update_cache_op.cpp:67:9: error: expected expression
   67 |         else TT_FATAL(this->batch_offset == 0, "Error");
      |         ^
1 error generated.
```

**Comment by ayerofieiev-tt** [comment]
> @ayerofieiev-tt your fix is so simple here, it makes me wonder why anyone ever used do-while?

I have the same question, concerns me too.

**Comment by ayerofieiev-tt** [comment]
Ok, lets close then

**Pull request closed without merging**
