### PR TITLE
Add support for watcher noc sanitization in noc_nonblocking_api.h

### PR DESCRIPTION
**Pull request by tt-dma**
Had to do a bit of cleanup/rearranging in the headers to get around some circular dependencies + multiple definitions, let me know if anything looks off.

Passing CI: https://github.com/tenstorrent/tt-metal/actions/runs/9024330478

### CODE REVIEW

**Comment by tt-dma** [comment]
One bugfix, new CI here: https://github.com/tenstorrent/tt-metal/actions/runs/9024995737

**Review by pgkeller — COMMENTED** [review]
The noc checking was done at the dataflow layer because these noc layer are routines that may be shared w/ buda at some point.  Please ping Milos on his plans before pushing this down to that layer.  Otherwise, I'm ok w/ this.

**Comment by tt-dma** [comment]
Conclusion per Milos is to leave Metal-specific things out of `noc_nonblocking_api.h`, so remove that in this PR. New passing CI: https://github.com/tenstorrent/tt-metal/actions/runs/9037973534

I've added in the missing `DEBUG_SANITIZE_*` calls in front of all relevant `noc_nonblocking_api.h` calls, we'll need to be careful about these in the future - left a comment in that file mentioning this as well.

**Review by pgkeller — APPROVED** [review]
be sure to squash these commits so we don't have the changes in noc_* file histories

**Review by aliuTT — APPROVED** [review]

**Pull request merged**
