### PR TITLE
#11883: use fixed_string.size() instead of sizeof to ensure compatiablity with newer versions of reflect

### PR DESCRIPTION
**Pull request by marty1885**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/11883)

### Problem description
Operator registration fails if a newer version of reflect is used due to bad size calculation. This can occur in out-of-tree compilations.

### What's changed
Use `.size()` to read size of string instead of sizeof.

### Checklist
- [x] Checked the change locally (Artem)

### CODE REVIEW

**Review by ayerofieiev-tt — APPROVED** [review]
Thank you!

**Comment by ayerofieiev-tt** [comment]
Checked the change locally

**Comment by marty1885** [comment]
@ayerofieiev-tt Can you help merge this PR?

**Comment by ayerofieiev-tt** [comment]
@marty1885 , I was sure I did merge. My bad. Merging now. Thank you!

**Pull request merged**
