### PR TITLE
#10471: Fixed GCC13 compile time issue

### PR DESCRIPTION
**Pull request by dmakoviichuk-tt**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/10471)

### Problem description
Provide context for the problem.

### What's changed
1) First compile error is no comments:
```
   return ttnn::multiply(nr_term, scalar, std::nullopt);
   scalar.deallocate();
```

2) Second compile error fixed:
Describe the approach used to solve the problem.
Summarize the changes made and its impact.
`return {std::move(program), .override_runtime_arguments_callback = override_runtime_arguments_callback};` doesn't compile.
This `return {.program = std::move(program), .override_runtime_arguments_callback = override_runtime_arguments_callback};` or `return {std::move(program), override_runtime_arguments_callback};` will.

3) added a few casts from int to the uint32_t. I don't like that we need that casts, better to fix it in the function parameter but it might require to fix it in a lot of places which depend on this functions.

### Checklist
- [X] Post commit CI passes
- [X] Model regression CI testing passes (if applicable)
- [X] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by marty1885** [comment]
Thanks for the help! Based on your branch, I also need the following diff to make it compile. May you add it to your PR?

```diff
diff --git a/tt_eager/tt_dnn/op_library/moreh_norm_backward/moreh_norm_backward.cpp b/tt_eager/tt_dnn/op_library/moreh_norm_backward/moreh_norm_backward.cpp
index d03acdffdc..e99e8b339c 100644
--- a/tt_eager/tt_dnn/op_library/moreh_norm_backward/moreh_norm_backward.cpp
+++ b/tt_eager/tt_dnn/op_library/moreh_norm_backward/moreh_norm_backward.cpp
@@ -211,7 +211,7 @@ operation::ProgramWithCallbacks moreh_norm_backward_(
         "writer_moreh_norm_backward.cpp";
 
     std::vector<uint32_t> reader_compile_time_args =
-    { static_cast<uint32_t>(is_dram(input)), static_cast<uint32_t>(is_dram(output)), static_cast<uint32_t>(is_dram(output_grad)), input_grad_rank };
+    { static_cast<uint32_t>(is_dram(input)), static_cast<uint32_t>(is_dram(output)), static_cast<uint32_t>(is_dram(output_grad)), static_cast<uint32_t>(input_grad_rank) };
     std::vector<uint32_t> writer_compile_time_args =
     { static_cast<uint32_t>(is_dram(input_grad)) };
     const auto reader_kernels_id = CreateReadKernel(program, reader_kernel_file, all_cores, reader_compile_time_args);
diff --git a/tt_metal/third_party/umd b/tt_metal/third_party/umd
index 80cd1705c5..a0ace0dd68 160000
--- a/tt_metal/third_party/umd
+++ b/tt_metal/third_party/umd
@@ -1 +1 @@
-Subproject commit 80cd1705c5a9d259ce87a6c9949aea1080760236
+Subproject commit a0ace0dd6878e22e718b8de2bd47407ef8158fe4
diff --git a/ttnn/cpp/ttnn/operations/normalization/groupnorm/groupnorm.hpp b/ttnn/cpp/ttnn/operations/normalization/groupnorm/groupnorm.hpp
index b0abd7d266..81104793cf 100644
--- a/ttnn/cpp/ttnn/operations/normalization/groupnorm/groupnorm.hpp
+++ b/ttnn/cpp/ttnn/operations/normalization/groupnorm/groupnorm.hpp
@@ -73,7 +73,7 @@ struct ExecuteGroupNorm {
         return operation::run(
             GroupNorm{
                 .eps=epsilon,
-                .num_groups=num_groups,
+                .num_groups=static_cast<uint32_t>(num_groups),
                 .output_mem_config=output_mem_config,
                 .program_config=program_config},
                 {input_tensor},
```

**Comment by dmakoviichuk-tt** [comment]
@marty1885  thanks for the quick reaction. Will do it.

**Review by ayerofieiev-tt — APPROVED** [review]

**Review by eyonland — APPROVED** [review]

**Comment by dmakoviichuk-tt** [comment]
@marty1885  done. Please confirm it works and we will merge it tomorrow.

**Review by cfjchu — APPROVED** [review]

**Comment by marty1885** [comment]
@dmakoviichuk-tt I did a clean build on my side and can confirm this branch compiles on my machine. Thanks for the help!

**Pull request merged**
