### PR TITLE
#14257: few more optimization for yolo

### PR DESCRIPTION
**Pull request by shwetankTT**
### Ticket
#14257: 

### Problem description
YoloV4 Optimization. 
Improvement:--> Getting 200fps from 170fps. 

### What's changed
Adding conv optimization flag for few layers. Removed few sharding which are not needed.

### Checklist
- [x] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by shwetankTT** [comment]
Nightly Regression:https://github.com/tenstorrent/tt-metal/actions/runs/12103838737

**Review by pavlejosipovic — COMMENTED** [review]
Is there any perf impact of this change?
Does trace size needs to be adjusted?

**Comment by shwetankTT** [comment]
> Is there any perf impact of this change? Does trace size needs to be adjusted?

Yes. The current perf is 200fps from 170. I ran the nightly CI no need for trace size adjastment.

**Comment by pavlejosipovic** [comment]
> > Is there any perf impact of this change? Does trace size needs to be adjusted?
> 
> Yes. The current perf is 200fps from 170. I ran the nightly CI no need for trace size adjastment.

We don't have a perf CI in place for yolo ATM?

**Comment by shwetankTT** [comment]
> > > Is there any perf impact of this change? Does trace size needs to be adjusted?
> > 
> > 
> > Yes. The current perf is 200fps from 170. I ran the nightly CI no need for trace size adjastment.
> 
> We don't have a perf CI in place for yolo ATM?

Yeah we don't hv perf CI for yolo. I am getting the numbers from IRD machines(1st sheet with final name.).  
https://docs.google.com/spreadsheets/d/1MRNswbQJeF-v9vzA_ajSRlBRHFTY8dAdDlnN6FiMRHQ/edit?gid=174224023#gid=174224023

**Comment by pavlejosipovic** [comment]
> > > > Is there any perf impact of this change? Does trace size needs to be adjusted?
> > > 
> > > 
> > > Yes. The current perf is 200fps from 170. I ran the nightly CI no need for trace size adjastment.
> > 
> > 
> > We don't have a perf CI in place for yolo ATM?
> 
> Yeah we don't hv perf CI for yolo. I am getting the numbers from IRD machines(1st sheet with final name.). https://docs.google.com/spreadsheets/d/1MRNswbQJeF-v9vzA_ajSRlBRHFTY8dAdDlnN6FiMRHQ/edit?gid=174224023#gid=174224023

Ok than, document the perf diff in PR description/commit message.
Btw I would prioritise adding perf CI before doing any perf optimisations.

**Review by pavlejosipovic — APPROVED** [review]

**Comment by shwetankTT** [comment]
To calculate the FPS we take the sum of  device kernel duration(ns) Column divided by 10^9 (sec --> nano sec conversion).

**Review by punithsekar — APPROVED** [review]

**Review by keerthana-r-mcw — APPROVED** [review]

**Comment by shwetankTT** [comment]
> Please run:
> 
> * Nightly fast dispatch

https://github.com/tenstorrent/tt-metal/actions/runs/12103838737

**Review by tt-rkim — APPROVED** [review]

**Review by mywoodstock — APPROVED** [review]

**Comment by mywoodstock** [comment]
@shwetankTT Lets get this on the perf CI so that this does not regress.

**Comment by shwetankTT** [comment]
@mywoodstock Yeah. Added the perf. Running the CI to validate.

**Pull request merged**
