### PR TITLE
Update perf and latest features for llm models (Aug 26)

### PR DESCRIPTION
**Pull request by skhorasganiTT**
### Ticket
N/A

### Problem description
N/A

### What's changed
- Updated perf and stable release versions for llm models on front page README
- Updated MODEL_UPDATES with latest model features

### Checklist
- [x] Post commit CI passes
- [x] Blackhole Post commit (if applicable)
- [x] Model regression CI testing passes (if applicable)
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by tt-rkim** [comment]
We really wanna cut a release... is there not a common release candidate that works for all the models, like rc33?

**Comment by skhorasganiTT** [comment]
> We really wanna cut a release... is there not a common release candidate that works for all the models, like rc33?

Rc33 works for all models except Llama8B (perf regression). Does it have to be perfectly aligned with the table?

**Comment by tt-rkim** [comment]
No, but if it all works on rc33, let's cut a release for rc33.

**Comment by tt-rkim** [comment]
@ayerofieiev-tt looks like rc33 is going to be our golden goose soon.

**Review by uaydonat — APPROVED** [review]

**Comment by tt-rkim** [comment]
@skhorasganiTT We'll put notes in the release that rc33 is functional for all models except Llama8B. Can you confirm?

Otherwise, confirming this is to-do for @uaydonat . I will let my management know.

**Comment by skhorasganiTT** [comment]
@tt-rkim Based on the [rc33 workflow](https://github.com/tenstorrent/tt-metal/actions/runs/10500260327), yes, and Llama8B is also functional but not performant (perf is lower than what is in the table).

**Review by tt-rkim — APPROVED** [review]

**Comment by skhorasganiTT** [comment]
@tt-rkim What did we agree to write? If you are referring to re-measuring the performance of all models on that release commit that is not easy to do.

**Comment by tt-rkim** [comment]
Then what should we do about reporting the numbers for the release that will use candidate `v0.50.0-rc33`?

This is your product. One solution is to put yet another warning in the release notes that saying the performance numbers displayed in the table are only at the measured release candidates, and may not be reflected in the release. Perhaps only a guarantee of functionality within the release.

This is why I urge models team to treat regressions as P0s, because the rc number in the tables aren't all the same, that makes it difficult to update the READMEs to be accurate.

**Pull request merged**
