### PR TITLE
#0: remove extra arch-wormhole labels for single-card workflows

### PR DESCRIPTION
**Pull request by ttmchiou**
### Ticket
Link to Github Issue https://github.com/tenstorrent/tt-metal/issues/11038

### Problem description
New workflows merged recently didn't capture new runner-label PR

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by TT-billteng** [comment]
there's many more `arch-wormhole_b0` references in the code than this?

**Comment by ttmchiou** [comment]
@tt-rkim mentioned that t3k/tg/tgg would eventually have different types of cards and it would be better to track the specific product line (ie grayskull,wormhole,blackhole) for these multi-card systems.

perhaps not an immediate problem , but this could make future changes to our labelling system smaller.
any thoughts on this?

**Comment by TT-billteng** [comment]
> @tt-rkim mentioned that t3k/tg/tgg would eventually have different types of cards and it would be better to track the specific product line (ie grayskull,wormhole,blackhole) for these multi-card systems.
> 
> perhaps not an immediate problem , but this could make future changes to our labelling system smaller. any thoughts on this?

I'd rather name them `t3k-wh`, `t3k-bh`, `tg-bh` ... then

**Comment by tt-rkim** [comment]
> I'd rather name them t3k-wh, t3k-bh, tg-bh ... then

Why? That's gonna make matrixing across platforms a little more difficult, ie.

```
matrix:
  config: ["tg", "tgg"]
  arch: ["arch-wormhole_b0", ...]
```

In general, not a fan of encoding separate pieces of info in the same label

**Comment by tt-rkim** [comment]
Also more handling for any management utils, since now we have to derive more labels

**Comment by TT-billteng** [comment]
are they even called TG systems when the time comes?

**Review by TT-billteng — APPROVED** [review]

**Comment by tt-rkim** [comment]
> would they even be called TG systems when the time comes?

Is that not the plan?

Anyway, the galaxy concept itself should still exist. I think we should still split out arch

**Pull request merged**
