### PR TITLE
#3960: add support for multichip tracy profiler and ethernet profile dump

### PR DESCRIPTION
**Pull request by aliuTT**
I'm trying to enable tracy profiler dump for remote devices, as well as ethernet cores. I'm still collecting data for some tests to make sure things make sense.

### CODE REVIEW

**Comment by aliuTT** [comment]
fyi @TT-billteng

**Comment by aliuTT** [comment]
@TT-billteng any chance we can get this approved to main without Mo? Andrew is starting work on ethernet cores, and this would help with profiling the kernel times. I've made some changes to the profiler scope names in ttmetal. Aside from syntax, there is no functional change

**Comment by TT-billteng** [comment]
sure shouldn't be a problem, let me review today

**Review by TT-billteng — APPROVED** [review]
LGTM

**Pull request merged**
