### PR TITLE
#11314: reduce eth dispatch scratch db size to account for erisc barrier

### PR DESCRIPTION
**Pull request by aliuTT**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/11314)
### Problem description
Eth dispatch hitting assert.

### What's changed
reduce scratch db buffer size by 32

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by abhullar-tt** [comment]
Should eth l1 size on host be uplifted to `max eth size - barrier size`. I notice we do this in `dev_mem_map`

**Comment by aliuTT** [comment]
> Should eth l1 size on host be uplifted to `max eth size - barrier size`. I notice we do this in `dev_mem_map`

Where is eth l1 size on host? Isn't host pulling it from dev_mem_map?

**Comment by abhullar-tt** [comment]
> > Should eth l1 size on host be uplifted to `max eth size - barrier size`. I notice we do this in `dev_mem_map`
> 
> Where is eth l1 size on host? Isn't host pulling it from dev_mem_map?

I think from the soc desc

**Comment by aliuTT** [comment]
> > > Should eth l1 size on host be uplifted to `max eth size - barrier size`. I notice we do this in `dev_mem_map`
> > 
> > 
> > Where is eth l1 size on host? Isn't host pulling it from dev_mem_map?
> 
> I think from the soc desc

Hmm, makes sense to me to reduce that by 32 as well. It seems like we assume L1 is usable up to MAX. @pgkeller thoughts?

**Review by pgkeller — APPROVED** [review]
This is a simple change w/ big implications, should be ok but feels a little risky.  The biggest dependency that may be hidden is that scratch_db get's split in half and 32/2=16 bytes doesn't align well w/ DRAM alignment of 64 bytes, wonder if we should reduce the size by 128 bytes, so 128/2=64.

**Comment by aliuTT** [comment]
> This is a simple change w/ big implications, should be ok but feels a little risky. The biggest dependency that may be hidden is that scratch_db get's split in half and 32/2=16 bytes doesn't align well w/ DRAM alignment of 64 bytes, wonder if we should reduce the size by 128 bytes, so 128/2=64.

I had the same thought. I was wondering if it made sense to shift the start down by 32, but I think that leaves lots of start addrs being different on eth core. I can try CI with 128 and see how that looks. We have some long term plan to move eth barrier back to the beginning right?

**Comment by pgkeller** [comment]
> > This is a simple change w/ big implications, should be ok but feels a little risky. The biggest dependency that may be hidden is that scratch_db get's split in half and 32/2=16 bytes doesn't align well w/ DRAM alignment of 64 bytes, wonder if we should reduce the size by 128 bytes, so 128/2=64.
> 
> I had the same thought. I was wondering if it made sense to shift the start down by 32, but I think that leaves lots of start addrs being different on eth core. I can try CI with 128 and see how that looks. We have some long term plan to move eth barrier back to the beginning right?

Yes, ish.  I'm planning to migrate eth memory handling to match the mechanism of tensix/idle eth as part of the ongoing memory map/hal work.  I suspect when that is done that this will get easier

**Comment by aliuTT** [comment]
> > > This is a simple change w/ big implications, should be ok but feels a little risky. The biggest dependency that may be hidden is that scratch_db get's split in half and 32/2=16 bytes doesn't align well w/ DRAM alignment of 64 bytes, wonder if we should reduce the size by 128 bytes, so 128/2=64.
> > 
> > 
> > I had the same thought. I was wondering if it made sense to shift the start down by 32, but I think that leaves lots of start addrs being different on eth core. I can try CI with 128 and see how that looks. We have some long term plan to move eth barrier back to the beginning right?
> 
> Yes, ish. I'm planning to migrate eth memory handling to match the mechanism of tensix/idle eth as part of the ongoing memory map/hal work. I suspect when that is done that this will get easier

Nice.. I'll add some comments to wherever the max is getting patched. 32 bytes less was getting all sorts of hangs on post commit :( Trying 128 now

**Pull request closed without merging**
