### PR TITLE
#9490: TTNN eltwise/unary migration

### LINKED ISSUE #9490: Move Unary ops to ttnn
Consolidate eltwise unary in ttnn

### Ops
https://docs.google.com/spreadsheets/d/1W5wVTj0a1nXgaOcbXWJbyJDGnQeOm9X-Y2RSUZ95yWY/edit?gid=1874132307#gid=1874132307

### Plan
We propose to breakdown the work into smaller pieces:
- [x] Replace usage of unary ops in C++ with ttnn analogs ([example](https://github.com/tenstorrent/tt-metal/pull/9368/files#diff-3d9c8f1458a236487c85d72277c5e98ea5060cb889efae6e60e85baa124b9791))
- [x] Replace usage in python Models, Demos, Examples, tests ([example](https://github.com/tenstorrent/tt-metal/pull/9368/files#diff-3decefc796146122ace7337ba1f3f717e90c19f1d24e4304dc690460fb77b3a1))
- [x] Remove tt_lib bindings and entries from docs ([bindings](https://github.com/tenstorrent/tt-metal/pull/9368/files#diff-e8ae187c678c01424392f0efc63ac8c450686b4ccaf74aaed790941984e957e7), [docs](https://github.com/tenstorrent/tt-metal/pull/9368/files#diff-236cfcb211efba0ed290148fa450ca89f7b11dec8223b8cfb02afda350c9392d))
- [x] Remove other dependencies of `tt_eager/tt_dnn/op_library/eltwise_unary`  ( UnaryWithParam, UnaryOpType) #10257
- [x] Restructure `tt_eager/tt_dnn/op_library/eltwise_unary` and `ttnn/cpp/ttnn/operations/unary.hpp` ([see new structure](https://github.com/tenstorrent/tt-metal/issues/9322))

Because there are lots of unary ops, consider splitting this work per op or a group of ops.

#### Replacing usage in C++
Each usage of unary op should be replaced with a ttnn analog. For example `abs` --> `ttnn::abs`.
Missing operations should be added to ttnn.
  - lots of usage in composite_ops.cpp, complex_ops.cpp, backward_ops.cpp 
  - lots of usage in tests, [example 1](https://github.com/tenstorrent/tt-metal/pull/9368/files#diff-f76070a3ff201ba6930e1fc34c698a486a3222a202e75841119661f5e7754ba4), [example 2](https://github.com/tenstorrent/tt-metal/pull/9368/files#diff-69c5eb0de84833ea5640c7da937d0145b3186a62d82cb3faaa6afae045a489daR123)

#### Replacing usage in Python
For every unary op, look for next entries in Tests/Sweeps, Demos, Models, Examples:
* `ttl.tensor.abs`
* `tt_lib.tensor.abs`
* `ttnn.primary.tensor.abs`
* `eltwise_abs`
and replace them with `ttnn.abs`. [Example](https://github.com/tenstorrent/tt-metal/pull/9368/files#diff-8a506d85107ff348dcb57916f47b780a4413e26a7e9094e66cea5a560da04fb4)

⚠️ tt_lib operations might sometimes have a slightly different interface
- arguments may be in different order
- arguments may be positional when ttnn arguments may be kw only
- output_mem_config --> memory_config
- optional_output_tensor --> optional_tensor
- output_dtype --> dtype

### Background
We got a lot of duplication.

We register unary ops in C++ in both tt_lib and ttnn:
- `ttnn/cpp/ttnn/operations/unary.hpp` provides scaffold for unary ops and registers them in `ttnn`
- `tt_eager/tt_dnn/op_library/eltwise_unary/eltwise_unary_op.hpp` registers unary ops in tt_eager

We bind these ops in both:
- `ttnn/cpp/pybind11/operations/unary.hpp`
- `tt_eager/tt_lib/csrc/tt_lib_bindings_tensor_xary_ops.cpp`

We have tt_eager sweep tests, but they are not run on CI.

Duplication should go away. TTNN C++ and binding should remain and everything should get switched.

Docs related to this issue listed here: 
- To track list of unary ops in tt-eager and ttnn :  [Unary op Migration Tracker](https://docs.google.com/spreadsheets/d/1W5wVTj0a1nXgaOcbXWJbyJDGnQeOm9X-Y2RSUZ95yWY/edit?usp=sharing)

### Testing
For the best coverage, I recommend to run these workflows. If some of them fails, check if it is the same fail as on main:
-  Post commit CI
-  [post-commit] models tests
-  Device perf regressions and output report
-  Model perf regressions and output report
-  Nightly fast dispatch model regression CI
-  T3000 frequent tests
-  T3000 demo tests

### PR DESCRIPTION
**Pull request by KalaivaniMCW**
### Ticket
Link to Github Issue #9490 

### Problem description
Move unary ops from tt_eager to ttnn library as mentioned in #9322 

### What's changed

- Established eltwise/unary structure with #9368 as reference
- Added optional_output_tensor and queue_id support
- Migrated square op from tt_eager to ttnn library, replacing all references to ttnn::square / ttnn.square  in cpp, test and model files. 
- Moved the below mentioned dataflow kernel files from tt_eager to ttnn and updated the path in related files as per review comments.
1. reader_unary_interleaved_start_id.cpp
2. reader_unary_sharded.cpp
3. writer_unary_interleaved_start_id.cpp

### Checklist
- [x] Post commit CI passes https://github.com/tenstorrent/tt-metal/actions/runs/9708335178
- [x] post-commit models tests CI testing passes https://github.com/tenstorrent/tt-metal/actions/runs/9708852376
- [x] Nightly fast dispatch passess https://github.com/tenstorrent/tt-metal/actions/runs/9708342934
- [x] Model perf regressions and output report pass https://github.com/tenstorrent/tt-metal/actions/runs/9709266836
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by eyonland — APPROVED** [review]

**Review by ayerofieiev-tt — APPROVED** [review]

**Comment by ayerofieiev-tt** [comment]
> Migrated square op from tt_eager to ttnn library, replacing all references to ttnn::square / ttnn.square in cpp, test and model files.

This ideally should have been a separate PR, which would be a great example for others migrating specific unary ops.

**Review by tt-aho — APPROVED** [review]

**Review by TT-BrianLiu — COMMENTED** [review]
For the files that are moved and renamed (the reader/writer and compute kernels + create_program code), the old code shouldn't be used anymore and should be deleted right?

**Comment by ayerofieiev-tt** [comment]
> For the files that are moved and renamed (the reader/writer and compute kernels + create_program code), the old code shouldn't be used anymore and should be deleted right?

Yes. Will happen as a separate PR.

**Comment by TT-BrianLiu** [comment]
> > For the files that are moved and renamed (the reader/writer and compute kernels + create_program code), the old code shouldn't be used anymore and should be deleted right?
> 
> Yes. Will happen as a separate PR.

Why can't it be in the same PR? It's a simple rename for the kernels at least. Instead, we will have two massive commits adding and deleting files.

**Comment by ayerofieiev-tt** [comment]
@TT-BrianLiu  Lots of C++ code like composite ops, including tt_lib bindings still depend on tt_dnn impl. MCW team will help to remove those deps bit by bit. And only then we can remove.

**Comment by TT-BrianLiu** [comment]
> @TT-BrianLiu Lots of C++ code like composite ops, including tt_lib bindings still depend on tt_dnn impl. MCW team will help to remove those deps bit by bit. And only then we can remove.

At the very least, the kernels should just be renamed and a simple search and replace for strings should help convert all use cases of these kernels. I am worried that we will have duplicate kernels existing without an explicit freeze on development for the old one.

**Comment by ayerofieiev-tt** [comment]
@TT-BrianLiu can you share more details/guidance. This will @KalaivaniMCW to complete this fast?

**Comment by TT-BrianLiu** [comment]
It's very simple (for kernels at least). Just switch the file path whereever you have code like this (lines 64 and 70): 
image

**Comment by ayerofieiev-tt** [comment]
@TT-BrianLiu I see. Good thinking. 
Kernel reuse is trivial. 
Program reuse hopefully is also trivial. But because ttnn and tt_eager kind of depend on each other - it is possible that include of .h with .cpp will be problematic. Not sure.

**Comment by TT-BrianLiu** [comment]
> @TT-BrianLiu I see. Good thinking. Kernel reuse is trivial. Program reuse hopefully is also trivial. But because ttnn and tt_eager kind of depend on each other - it is possible that include of .h with .cpp will be problematic. Not sure.

I would give it a try. If a simple switch of namespace doesn't work, then just leave the duplicate `create_program` code. But kernels should not be duplicated for sure.

**Review by arakhmati — APPROVED** [review]

**Review by bbradelTT — APPROVED** [review]

**Pull request merged**
