### PR TITLE
Shwetank tt/lpanos/conv weight prepare

### PR DESCRIPTION
**Pull request by shwetankTT**
### Ticket
#14179

Old PR from Lpanos https://github.com/tenstorrent/tt-metal/pull/14566

### Problem description
Follow up commit from lpanos. 

We have ops prepare_conv_weights_for_ttnn and prepare_conv_bias_for_ttnn that will pre-format convolution weights and biases for conv2d (without pushing them to device). In the previous implementation, you would pass the NHWC weights to ttnn.conv2d and ttnn.conv2d would return the formatted weights/bias on device for you to use in subsequent calls. The two aforementioned ops do this beforehand now.

TASKS

ttnn.conv2d is now pybinded to conv2d_host_weights which is the previous conv2d implementation. This needs use conv2d now
All tests that use ttnn.conv2d must use ttnn.prepare_conv_weights_for_ttnn and ttnn.prepare_conv_bias_for_ttnn to format weights/biases beforehand.

### Checklist
- [x] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [x] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by shwetankTT** [comment]
All commit:- https://github.coAm/tenstorrent/tt-metal/actions/runs/12072461678

Single card run: https://github.com/tenstorrent/tt-metal/actions/runs/12066442411/job/33647708269

**Review by LPanosTT — APPROVED** [review]
Looks good to me

**Comment by bbradelTT** [comment]
@shwetankTT Please fill in the description to be more descriptive.

**Review by ayerofieiev-tt — APPROVED** [review]
approving non-key elements of the PR around ttnn tests/cmake.

**Review by mywoodstock — APPROVED** [review]

**Review by bbradelTT — APPROVED** [review]

**Pull request merged**
