### PR TITLE
#13790: Fix CMake arguments to enable ccache

### PR DESCRIPTION
**Pull request by jerrysky3**
### Ticket
#13790

### Problem description
The CMake arguments to enable ccache should be passed as a list of two strings instead of a single string. Otherwise it will use incorrect ccache command to build and results in errors like below:
```
FAILED: _deps/nanomsg-build/CMakeFiles/nng.dir/src/core/sockfd.c.o
"ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache" /usr/bin/clang-17 -DNNG_ENABLE_COMPAT -DNNG_ENABLE_IP...
```

### What's changed
Append ccache arguments as a list of two strings

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by blozano-tt — APPROVED** [review]
@afuller-TT please double check, but I think this makes sense.

**Comment by tt-rkim** [comment]
Is this a bash syntax thing?

**Comment by jdh8** [comment]
@tt-rkim, yes, this is a bash array.

**Review by tt-rkim — APPROVED** [review]

**Comment by afuller-TT** [comment]
Thanks @jerrysky3 .  More changes are required for `ccache` since PCH are used in some parts of the build.  I'm currently doing work in this area and will make the two mutually exclusive for the first pass.

Have you been running with this change?  Did you not encounter issues with PCH and no sloppiness overrides?

**Comment by afuller-TT** [comment]
Oh awesome, @jerrysky3 !  I didn't know that the newest `ccache` is handling that gracefully now.

Let's merge this in.  It's clearly an improvement over the status-quo.  We can keep iterating.  As you saw, the first cut is going to be mutually exclusive w/ PCH (focused on our CI/CD so we can get more juice out of our build checks).  Later I'll follow it up with sloppiness as req'd, but I don't want to make everything sloppy; only the pieces where PCH make a notable improvement.

**Pull request merged**
