### PR TITLE
#6343: Demo for functional bloom

### PR DESCRIPTION
**Pull request by kkeerthana0573**
This PR contains end to end demo for ttnn_functional_bloom, ttnn_optimized_functional_bloom for CausalLM.

### CODE REVIEW

**Review by arakhmati — APPROVED** [review]

**Comment by kkeerthana0573** [comment]
CI passed. Link [here](https://github.com/tenstorrent-metal/tt-metal/actions/runs/8322528809)

**Review by eyonland — COMMENTED** [review]
Why not move to the models/demo?

**Comment by Sudharsan-V** [comment]
> Why not move to the models/demo?

@eyonland, In the current file setup, the demos for the functional models are placed within their corresponding functional model folders.  Hence following the same file organization.

**Review by boris-drazic — APPROVED** [review]

**Comment by kkeerthana0573** [comment]
CIs passed. Links here : Nightly [fast](https://github.com/tenstorrent/tt-metal/actions/runs/8787666457) and [slow](https://github.com/tenstorrent/tt-metal/actions/runs/8787669582) dispatch, [all post commit](https://github.com/tenstorrent/tt-metal/actions/runs/8787678343) tests.

**Pull request merged**
