### PR TITLE
#0: Add clang-format to pre-commit check for metal repo

### PR DESCRIPTION
**Pull request by tt-aho**

### CODE REVIEW

**Review by ayerofieiev-tt — APPROVED** [review]
Will you run format-all as a separate PR?

**Comment by tt-aho** [comment]
> Will you run format-all as a separate PR?

I'll add it in this pr. I had to undo it after rebasing due to conflicts so need to reapply.

I'd like to add it to the static checks as well in ci but haven't looked into how to do that yet. Will probably do this later/separate pr.

**Review by bbradelTT — APPROVED** [review]

**Comment by SeanNijjar** [comment]
Hey @tt-aho, can you please confirm that this is purely a clang format commit? I've got some allgather changes in flight and dealing with conflicts will be a pain and I'd prefer if I can just accept mine when I do my rebase ontop of this and then format my new changes

**Comment by tt-aho** [comment]
I discussed this with @tt-rkim , we will back out the formatting changes done to the files and let devs format as they go along to minimize disruptions. However we will announce a date later on when we will just format all files. This should give devs enough time/warning to deal with potential conflicts.

**Comment by tt-aho** [comment]
@abhullar-tt @arakhmati @eyonland just wanted to get your signoff for adding clang-format check to all c++ files in the repo, as you guys work on / own different parts of the stack (ex metal, ttnn).

**Review by abhullar-tt — APPROVED** [review]

**Review by rtawfik01 — APPROVED** [review]

**Review by arakhmati — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Pull request merged**
