### PR TITLE
#6184: sharded row major silu support.

### PR DESCRIPTION
**Pull request by shwetankTT**

### CODE REVIEW

**Comment by davorchap** [comment]
@apalaguha this is sharded unary

**Comment by shwetankTT** [comment]
> @apalaguha this is sharded unary

https://github.com/tenstorrent-metal/tt-metal/pull/6459
@davorchap this is Row major sharded layout needed for Stable diffusion. We have merged the above PR which covers Tiledlayout with height and block sharded.

**Review by AleksKnezevic — APPROVED** [review]

**Review by eyonland — APPROVED** [review]
Would it make sense to generalize this get_shard_grid_from_num_cores() function and reuse outside of the test in other contexts?

**Comment by shwetankTT** [comment]
> Would it make sense to generalize this get_shard_grid_from_num_cores() function and reuse outside of the test in other contexts?

Yes, This function has been used at couple of places. I will try to put this into some helper fuctions.

**Pull request merged**
