### PR TITLE
#0:  polygamma, isclosenan, nextafter, rpow, rdiv, rsub, bitwise fallback ops fix Integration mcw-main/1006

### PR DESCRIPTION
**Pull request by muthutt**
It includes
- Implementation of `rpow, rdiv, rsub `
- unary and binary assign: aka `copy`, `clone`
- bitwise fall back ops: unary and binary `AND, OR, XOR, NOT`
- `Polygamma`, `isclosenan` and `nextafter` op support

### CODE REVIEW

**Review by tt-aho — CHANGES_REQUESTED** [review]
~A couple of questions I have are why we need to bind clone/copy ops as unary/binary assign? Is this naming scheme from a different library than pytorch and do we need to have 2 names for the same function?~ Resolved
Other question is if we do want to keep the two naming schemes, assign and copy/clone, why do we need to wrap them as composite ops? If there is no difference/change between them should we not just directly alias them and not pay for the composite wrapper overhead?

**Review by TT-BrianLiu — COMMENTED** [review]
LGTM

**Review by mywoodstock — APPROVED** [review]

**Review by tt-aho — COMMENTED** [review]
lgtm. Will approve after assign is moved out of composite

**Review by tt-aho — CHANGES_REQUESTED** [review]
@muthutt your latest merge has reverted changes from other commits. Please remove commits `bec724f` and `7c24f19`.
For commit `411670a` remove all changes related to assign op as well as removing the addition of this line in `tt_lib_ops.py`
`eltwise_bias_gelu = make_binary_op(ttl.tensor.bias_gelu)`

**Review by tt-aho — CHANGES_REQUESTED** [review]
Other comments are minor but these two are main blockers:

- Fix commit messages
- I do not see an approx mode test for exp

**Review by tt-aho — CHANGES_REQUESTED** [review]
- There are still commit messages with incorrect format
- I think you reverted your addition of exp unit test, however we want unit tests for exp in approx mode. That test just added an additional input range check. The ranges we currently test in `test_run_eltwise_exp_ops` covers the cases where we were seeing positive output, so we should use these ranges to verify approx mode output

**Review by tt-aho — CHANGES_REQUESTED** [review]
You still haven't fixed all of the git commit messages. Please review your commits in the commits tab to verify they have all been updated to our contribution standards before saying it has been addressed. You've stated they've all been addressed numerous times yet they have not.
image

Additionally, BBE also had similar issues with approx mode exp, and has their own fix. I believe our current fix degrades non-approx mode perf when there was no issue, and that the approx mode changes have re-introduced additional corner case bugs that were previously handled so I think we should pull in the fix from BBE instead. We can discuss this mode separately but to move forward with this PR I suggest we remove the commits related to exp changes and merge them separately after reviewing so that it doesn't block this PR.
This means reverting/removing these two commits:

- https://github.com/tenstorrent-metal/tt-metal/pull/3111/commits/21a2661df8c0cc64304e573134d5094f61a84871
- https://github.com/tenstorrent-metal/tt-metal/pull/3111/commits/8a6f775e58a4bca061596fa073ca87a4b49964d6

**Review by tt-aho — APPROVED** [review]
lgtm

**Pull request merged**
