### PR TITLE
#0: Update to gcc-12.x

### PR DESCRIPTION
**Pull request by nathan-TT**
Update to gcc-12.x

a few compile time limits needed relaxing

### Ticket
Link to Github Issue

### Problem description
gcc 10 is old

### What's changed
Update from gcc-10 to gcc-12
ETA: updated binaries in sfpi component

### Checklist
- [Yes] Post commit CI passes
- [Yes] Blackhole Post commit (if applicable)
- [Yes] Model regression CI testing passes (if applicable)
- [NA ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by ayerofieiev-tt** [comment]
I see an sfpi update and some tests tweak, but I don't see update to gcc-12

**Comment by nathan-TT** [comment]
> I see an sfpi update and some tests tweak, but I don't see update to gcc-12

The sfpi update contains new binaries.  What were you expecting to see?

**Review by tt-aho — APPROVED** [review]
I recommend being lax and giving the compile time threshold more margin if the passing ci runs are very close to it. It's not a metric we care too much about.

**Comment by nathan-TT** [comment]
> I recommend being lax and giving the compile time threshold more margin if the passing ci runs are very close to it. It's not a metric we care too much about.

Thanks for the info.  I gave a bit of headroom, so should be good.  I'll remember this if it becomes a problem.

**Comment by nathan-TT** [comment]
rebased to fix merge conflict

**Review by yan-zaretskiy — APPROVED** [review]

**Review by abhullar-tt — APPROVED** [review]

**Pull request merged**
