### PR TITLE
Enable bert perf tests for wormhole b0

### PR DESCRIPTION
**Pull request by rtawfik01**

### CODE REVIEW

**Comment by tt-rkim** [comment]
Please run perf pipelines https://github.com/tenstorrent/tt-metal/actions/workflows/perf-models.yaml

**Comment by tt-rkim** [comment]
Sorry I'm an idiot - ignore above comment

**Comment by tt-rkim** [comment]
run nightly FD: https://github.com/tenstorrent/tt-metal/actions/workflows/fast-dispatch-full-regressions-and-models.yaml

**Comment by rtawfik01** [comment]
@davorchap fyi, the perf of bert batch 8 on 1GHz, 8x8 grid with row_major shards is ~340 samples/sec.
With col_major its ~330 samples/sec. I think there is low-hanging fruit to investigate here, but this PR would make sure the test is regressed on for whb0

**Comment by davorchap** [comment]
> @davorchap fyi, the perf of bert batch 8 on 1GHz, 8x8 grid with row_major shards is ~340 samples/sec. With col_major its ~330 samples/sec. I think there is low-hanging fruit to investigate here, but this PR would make sure the test is regressed on for whb0

great!!
to start we are adding row-major 8x8 @ 1 GHz, 340 sent/sec into device regression CI?

**Comment by rtawfik01** [comment]
> 
> great!! to start we are adding row-major 8x8 @ 1 GHz, 340 sent/sec into device regression CI?

Yes just to have the test consistently passing.

**Review by tt-rkim — APPROVED** [review]

**Review by arakhmati — APPROVED** [review]

**Pull request merged**
