### PR TITLE
#8367: Add docopt to dev-requirements

### PR DESCRIPTION
**Pull request by ihamer-tt**

### CODE REVIEW

**Comment by tt-rkim** [comment]
You don't foresee users installing via binaries/wheels needing to use this, correct?

**Comment by ihamer-tt** [comment]
> You don't foresee users installing via binaries/wheels needing to use this, correct?

It is needed for a standalone debug script (dump-consts). If we want to run it cleanly everywhere perhaps we should add it to other requirements.txt-s. Otherwise a pip install docopt fixes it. Let me know what you think.

**Comment by tt-rkim** [comment]
Sounds good.

I'll write here for history: For future packaging purposes, because users are expected to provide the filepath to the tensix elf, this would usually be done only in a srcdir development context.

Approved.

**Comment by tt-rkim** [comment]
I have started a post-commit run just to ensure we have no issues with Python environment conflicts.

**Comment by tt-rkim** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/9194635564

**Review by tt-rkim — APPROVED** [review]

**Pull request merged**
