### PR TITLE
#7242: Add tools installation scripts for developers

### PR DESCRIPTION
**Pull request by tapspatel**

### CODE REVIEW

**Comment by tapspatel** [comment]
Issue: https://github.com/tenstorrent-metal/tt-metal/issues/7242

**Review by tt-rkim — APPROVED** [review]
Looks good, a couple of things I think you should consider creating as future issues
- We're putting all of the syseng stuff into people's $HOME dirs. You could give people the option to override, or put it all in a folder like `$HOME/tt-install` or something like that
- `tt-kmd` install method is suspect, not because of what you wrote, but there seem to be cases where their instructions don't work and need to clean out all of dkms. I'm wondering if it's bothersome enough that we should make an issue on our side to track progress or even contribute to fixingcc: @ttmchiou 
- Are `TT_FIRMWARE_VERSION` and `TT_FLASH_VERSION` supposed to be empty? Will the checkout work?
- Change `pip install` to `pip3 install` for future compatibility with python versions

**Comment by tapspatel** [comment]
`TT_FIRMWARE_VERSION` and `TT_FLASH_VERSION `: yes they are supposed to be empty. They do not have proper tags for them. Filing issues on their end to add that in. Blank checkout works, I tested all files
pip3 install: done

**Comment by ttmchiou** [comment]
if we are noticing an issue with tt-kmd installation instructions, lets make an issue to track that we've noticed it and keep an eye on it.

**Pull request merged**
