### PR TITLE
Add mistral-7b correctness test to CI

### PR DESCRIPTION
**Pull request by mtairum**
Adds full mistral-7b test to CI.

This test runs both on host CPU and on device and compares PCC for all 32 layers.

### CODE REVIEW

**Comment by tt-rkim** [comment]
Please post a run of fast dispatch nightly run here, and we will check that new mistral is being run in the logs

**Comment by mtairum** [comment]
> Please post a run of fast dispatch nightly run here, and we will check that new mistral is being run in the logs

I can see it running but it got killed after loading the weights, and before start loading the cache stored in `/mnt/MLPerf/ttnn/models/demos/mistral7b` but I don't see any other error message?


```
2024-03-28T10:34:47.0594455Z models/demos/mistral7b/tests/test_mistral_model.py::test_mistral_model_inference[17-generative] [38;2;000;128;000m                 Device[0m | [1m[38;2;100;149;237mINFO    [0m | Opening user mode device driver
2024-03-28T10:34:48.1335775Z [44m[30mCHECKING: [0, 0, 0, 0][0m
2024-03-28T10:34:48.1336483Z [44m[30mCHECKING: [1, 0, 0, 0][0m
2024-03-28T10:34:48.2564193Z [32m2024-03-28 10:34:48.256[0m | [1m[38;2;100;149;237mINFO    [0m | [36mSiliconDriver  [0m - Detected 1 PCI device : {0}
2024-03-28T10:34:48.2808664Z [32m2024-03-28 10:34:48.280[0m | [1m[38;2;255;165;000mWARNING [0m | [36mSiliconDriver  [0m - init_detect_tt_device_numanodes(): Could not determine NumaNodeSet for TT device (physical_device_id: 0 pci_bus_id: 0000:07:00.0)
2024-03-28T10:34:48.2810883Z [32m2024-03-28 10:34:48.280[0m | [1m[38;2;255;165;000mWARNING [0m | [36mSiliconDriver  [0m - Could not find NumaNodeSet for TT Device (physical_device_id: 0 pci_bus_id: 0000:07:00.0)
2024-03-28T10:34:48.2832276Z [32m2024-03-28 10:34:48.282[0m | [1m[38;2;255;165;000mWARNING [0m | [36mSiliconDriver  [0m - bind_area_memory_nodeset(): Unable to determine TT Device to NumaNode mapping for physical_device_id: 0. Skipping membind.
2024-03-28T10:34:48.2835401Z [0;33m---- ttSiliconDevice::init_hugepage: bind_area_to_memory_nodeset() failed (physical_device_id: 0 ch: 0). Hugepage allocation is not on NumaNode matching TT Device. Side-Effect is decreased Device->Host perf (Issue #893).
2024-03-28T10:34:48.2867500Z [0m[32m2024-03-28 10:34:48.286[0m | [1m[38;2;255;165;000mWARNING [0m | [36mSiliconDriver  [0m - bind_area_memory_nodeset(): Unable to determine TT Device to NumaNode mapping for physical_device_id: 0. Skipping membind.
2024-03-28T10:34:48.2869939Z [0;33m---- ttSiliconDevice::init_hugepage: bind_area_to_memory_nodeset() failed (physical_device_id: 0 ch: 1). Hugepage allocation is not on NumaNode matching TT Device. Side-Effect is decreased Device->Host perf (Issue #893).
2024-03-28T10:34:48.3903568Z [0m[32m2024-03-28 10:34:48.390[0m | [1m[38;2;100;149;237mINFO    [0m | [36mSiliconDriver  [0m - Software version 6.0.0, Ethernet FW version 6.9.0 (Device 0)
2024-03-28T10:34:48.3915172Z [32m2024-03-28 10:34:48.391[0m | [1m[38;2;100;149;237mINFO    [0m | [36mSiliconDriver  [0m - Software version 6.0.0, Ethernet FW version 6.9.0 (Device 1)
2024-03-28T10:34:48.3950494Z [38;2;000;128;000m                  Metal[0m | [1m[38;2;100;149;237mINFO    [0m | Initializing device 0
2024-03-28T10:34:48.4309513Z [38;2;000;128;000m                  Metal[0m | [1m[38;2;100;149;237mINFO    [0m | AI CLK for device 0 is:   800 MHz
2024-03-28T10:34:49.9124155Z 2024-03-28 10:34:49.911 | INFO     | models.demos.mistral7b.tests.test_mistral_model:test_mistral_model_inference:68 - Loading weights...
2024-03-28T10:35:09.2025899Z 2024-03-28 10:35:09.202 | INFO     | models.demos.mistral7b.tests.test_mistral_model:test_mistral_model_inference:78 - Finished loading weights...
2024-03-28T10:36:00.6114225Z ./tests/scripts/run_models.sh: line 22: 2928243 Killed                  env pytest models/demos/mistral7b/tests/test_mistral_model.py::test_mistral_model_inference[17-generative]
2024-03-28T10:36:00.6275067Z ##[error]Process completed with exit code 137.
```

**Comment by mtairum** [comment]
> Exit code 137 - out of memory.
> 
> The nightly fast dispatch pipelines use a lower amount of memory - 48GB. This is a different runner than the large bare metal for perf pipeline and the T3000 for the multi-nebula pipeline.
> 
> Are we still only running on single WH?

Yes, single WH.

**Comment by tt-rkim** [comment]
No, we are very short on runners with more memory.

Do you not have a correctness check in perf pipeline?

**Comment by mtairum** [comment]
The perf pipeline we only check for perf differences, not PCC. If its not against the perf pipeline goal I can add a second correctness test to the perf pipeline.

**Comment by tt-rkim** [comment]
Unfortunately we cannot support higher-RAM capacity on the nightly models wormhole pipelines as of now. @tenstorrent-metal/buda-devinfra will look into what we can do as a temporary measure to have higher RAM on wormhole models to have nicely defined pipelines.

The way I see it, you can do one or more of the following to unblock yourself:

- optimize your model for memory usage
- add a PCC check to your mistral perf test that you will be checking manually on GitHub Actions logs
- break down your impl of Mistral7b into smaller, lower-memory "unit tests" in a pytest files that we can call on the nightly wormhole models pipeline

I believe these are 3 viable options and the current unavailability of higher RAM runners should not be blocking further Mistral work.

**Review by eyonland — APPROVED** [review]

**Comment by tt-rkim** [comment]
@mtairum Have you made a decision on what to do?

**Comment by mtairum** [comment]
Option 1 and 3 is a no go.

We do have smaller PCC tests, but the problem is that some issues might require most of all the model layers to show up.

Option 2 seems good to me (adding PCC test to existent perf test).
This test asserts if PCC is lower than expected 0.99. So the manual workflow will show if this particular test passed or not.

**Comment by tt-rkim** [comment]
Sounds good to me.

Please then put this check in the `llm_javelin wormhole_b0` pipeline branch for perf models pipeline.

Note that you and your team will be responsible for checking if it passes on a regular basis. It will be also be your responsibility to chase down anyone who breaks it and fix the test.

**Comment by mtairum** [comment]
@tt-rkim 
I've added the large PCC test to the perf pipeline and smaller tests to nightly. The PR is ready for merge.

The nightly pipeline is passing all 5 mistral tests here: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8527129549/job/23357861633

the full model PCC test is passing in the perf workflow here:
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8527133197/job/23357874600

```
2024-04-02T17:57:27.4103112Z 2024-04-02 17:57:27.409 | INFO     | models.demos.mistral7b.tests.test_mistral_model:test_mistral_model_inference:241 - All 17 Mistral decode iterations Passed!
```

**Comment by mtairum** [comment]
@tt-rkim Can I go ahead and rebase&merge this PR?

**Review by tt-rkim — APPROVED** [review]

**Comment by tt-rkim** [comment]
Great work, yes please do so as well as answer my following questions:

- Did you make any changes to reduce memory usage? We did not change anything on runner side
- Are you planning to add a PCC check to perf pipeline, or will you just be using the models run here?
- Going forward, will part of your teams' tasks include checking the nightly models pipeline for whisper?

**Comment by mtairum** [comment]
> Did you make any changes to reduce memory usage? We did not change anything on runner side
No. Instead I added the smaller correctness tests we already had for Mistral, to the nightly run. These fit the memory requirements without a problem.


> Are you planning to add a PCC check to perf pipeline, or will you just be using the models run here?
I added this by adding the `@pytest.mark.models_performance_bare_metal` to the relevant test in `models/demos/mistral7b/tests/test_mistral_model.py`. It's working as intended and I can see it's passing on the perf runner.

> Going forward, will part of your teams' tasks include checking the nightly models pipeline for mistral7b?
I'm not sure what you mean by this. The nightly tests I've added (small correctness tests) will fail if there's any change to tt-metal that might affect correctness. Similarly to the other models tests already there, we don't want any future change to mess these up.
We can and should be flagged up if one of these fails in the future, to help identify the cause of the regression and help the person/team that introduced the regression on a fix. Is there a directory of model owners within the repository?

Regarding the large full model correctness test added to the perf pipeline. Does this pipeline run only manually or is also scheduled from time to time? I find this one a bit trickier, since this test won't be run as often as the nightly ones, so a regression might be detected later on. I would expect a similar approach as the nightly tests, but with a bit longer time-to-fix due to the nature of the test.

**Comment by tt-rkim** [comment]
I'm happy with your answers to 1 and 2.

> 3. Going forward, will part of your teams' tasks include checking the nightly models pipeline for mistral7b?
> I'm not sure what you mean by this. The nightly tests I've added (small correctness tests) will fail if there's any change to tt-metal that might affect correctness. Similarly to the other models tests already there, we don't want any future change to mess these up.
> We can and should be flagged up if one of these fails in the future, to help identify the cause of the regression and help the person/team that introduced the regression on a fix. Is there a directory of model owners within the repository?

However, I believe we have a disconnect in ownership. In general, you should be checking that the tests you wrote pass, especially when we're working on a project like this.

Yes, if mistral tests fail in nightly and someone other than your team notices, they should flag and let you know. However, I still believe you and your team should be owning and checking the status of these tests on a regular basis. @uaydonat and @jliangTT can provide comment, especially if they don't agree with what I said here.

> Does this pipeline run only manually or is also scheduled from time to time?

Perf models run once a day, at 2AM GMT, per its definition in `.github/workflows/perf-models.yaml`. We can definitely increase its frequency if you'd like. However, you would still be manually checking test status. GitHub does not support functionality to email multiple people in case of failure, unfortunately.

Let me know if that doesn't work.

**Comment by mtairum** [comment]
> However, I still believe you and your team should be owning and checking the status of these tests on a regular basis.
I understand and agree with this. We will look regularly into these status moving forward and fix if needed.

My worry is scalability. As more models and tests are added it will become increasingly cumbersome to manually check the pipeline status every so often. Automatic user flagging would be best, but some sort of central dashboard that would update with every failing scheduled tests would be good, if it's something that can be implemented in github.

> Perf models run once a day, at 2AM GMT
This is great. Thanks for the info. That's more than enough for the mistral test.

**Pull request merged**
