### PR TITLE
Cleanup compiler errors for newer versions of GCC and Clang

### PR DESCRIPTION
**Pull request by esmalTT**
This PR contains several minor fixes to reduce the amount of compiler errors/warnings on newer versions of Clang and GCC. This should improve the experience for those trying to use a language server like `clangd` during development. 

I also removed some unused headers where possible.

Let me know if you prefer a multiple commits or a single squashed commit.

### CODE REVIEW

**Comment by esmalTT** [comment]
Post commit jobs are all passing except for one wormhole perf test.

https://github.com/tenstorrent-metal/tt-metal/actions/runs/7893149591/job/21541991571

**Review by cfjchu — APPROVED** [review]
My preference is to squash your commits in this case

**Comment by esmalTT** [comment]
> My preference is to squash your commits in this case

Commits squashed. Let me know if there's anything else I need to take care of.

**Review by xanderchin — APPROVED** [review]
Squash is also my preference here

**Review by TT-billteng — APPROVED** [review]

**Review by arakhmati — APPROVED** [review]

**Pull request closed without merging**
