### PR TITLE
#0: Add 2 CQ Resnet 50 functional and trace tests

### PR DESCRIPTION
**Pull request by tt-asaigal**
### Ticket
Link to Github Issue

### Problem description
2 CQ TGG Functional Tests are missing from CI.

### What's changed
Add 2 CQ Functional Resnet tests for TGG and 2 CQ Trace Unit tests. Perf tests staged in a separate PR.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by tt-asaigal** [comment]
Passing TGG Frequent: https://github.com/tenstorrent/tt-metal/actions/runs/11267999985

**Review by tt-aho — APPROVED** [review]

**Comment by tt-rkim** [comment]
Does one TGG take longer than the other?

**Comment by tt-asaigal** [comment]
> Does one TGG take longer than the other?

Yeah thats what it seemed like. The trace unit tests are a sweep over different runtime configs and shapes. Resnet tests just run 4 configs

**Comment by tt-rkim** [comment]
Yeah we need to get to the bottom of that. We'll need someone to tracy a run on both and compare or something like that

**Review by tt-rkim — APPROVED** [review]

**Review by TT-BrianLiu — APPROVED** [review]

**Pull request merged**
