### PR TITLE
#0: swin_s conv params

### PR DESCRIPTION
**Pull request by punithsekar**
Added swin_s conv unit_test to test_new_conv2d.py file.

### Checklist
- [x] Post commit CI passes

### CODE REVIEW

**Comment by punithsekar** [comment]
CI link for post-commit: [Link]( https://github.com/tenstorrent/tt-metal/actions/runs/10733051062)

**Comment by punithsekar** [comment]
Passing CI [link](https://github.com/tenstorrent/tt-metal/actions/runs/10765963866).

**Review by sankarmanoj-tt — APPROVED** [review]

**Comment by sankarmanoj-tt** [comment]
This is good. Please add unit tests from other models so that regressions don't happen in the future.

**Comment by punithsekar** [comment]
Yeah Sure @sankarmanoj-tt !

**Pull request merged**
