### PR TITLE
#4801: Implement Unet 2D Condition model using ttnn for stable_diffus…

### PR DESCRIPTION
**Pull request by punithsekar**
This PR contains the Unet2DconditionModel sub-module implemented using ttnn for the stable diffusion model.

### CODE REVIEW

**Comment by punithsekar** [comment]
We get the following Results for the Unet2DConditionModel,

Shape 1: 256x256

sample: [2, 4, 32, 32]
PCC : ~ 0.77

Shape 2: 512x512

sample: [2, 4, 64, 64]
PCC: ~ 0.88

**Review by boris-drazic — APPROVED** [review]

**Review by arakhmati — APPROVED** [review]

**Comment by boris-drazic** [comment]
@punithsekar can you please merge this branch to main for tomorrow?

**Comment by punithsekar** [comment]
> @punithsekar can you please merge this branch to main for tomorrow?

Sure @boris-drazic ,
We will merge this PR to main. Once the sub-modules(#5086 , #5089 , #5093) PR's are merged.
And CI's passes.

**Comment by punithsekar** [comment]
We get the following Results for the Unet2DConditionModel,

Shape 1: 256x256

sample: [2, 4, 32, 32]
PCC > 0.99

Shape 2: 512x512

sample: [2, 4, 64, 64]
PCC > 0.99

**Comment by punithsekar** [comment]
CI Link:

[post-commit] Run all post-commit workflows [Link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/7883289490)

**Pull request merged**
