### PR TITLE
#0: Update example version from 0.35.0 to working version with HTTPS checkout in README because we changed cloning to use HTTPS

### PR DESCRIPTION
**Pull request by tt-rkim**
…

### CODE REVIEW

**Comment by tt-rkim** [comment]
@TTDRosen this tag should be gucci.

**Comment by TTDRosen** [comment]
I tried with 0.43.0 and hit the same error. It looks like 0.44.0-rc1 is the earliest branch which supports https on all submodules.

**Comment by tt-rkim** [comment]
Ah shoot - looks like fix went it after that tag.

0.44.0-rc1 has compile errors.

I'll keep this PR open until the next working RC is generated.

**Comment by tt-rkim** [comment]
How does v0.44.0 work for you now?

**Comment by TTDRosen** [comment]
Yep! Looks like 44 fixes the issue :)

**Pull request merged**
