### PR TITLE
#3721: type-2 complex tensor support without split/concat

### PR DESCRIPTION
**Pull request by muthutt**
#3721: type-2 complex tensor support without split/concat
docs:
image

### CODE REVIEW

**Review by tt-aho — CHANGES_REQUESTED** [review]
I think we should only keep one complex tensor implementation around. Having two that supports different things makes things confusing

**Review by tt-aho — CHANGES_REQUESTED** [review]
Are we planning to remove the old implementation of complex tensor, and make this the new one without "type2" in the naming?

**Review by mywoodstock — APPROVED** [review]

**Review by TT-BrianLiu — APPROVED** [review]
Minor formatting requests

**Review by tt-aho — COMMENTED** [review]
Mostly lgtm, remaining comments are minor. Most important is to make the member const/private

**Review by tt-aho — APPROVED** [review]
approving now, but would be good to get these two addressed before merge
https://github.com/tenstorrent-metal/tt-metal/pull/3412#discussion_r1388571156
https://github.com/tenstorrent-metal/tt-metal/pull/3412#discussion_r1388572033

**Review by arakhmati — APPROVED** [review]

**Review by eyonland — COMMENTED** [review]
I noticed a lot of tests that had portions that skipped wormhole within the test.  It would be nice if we all followed the same convention of using the annotation @skip_for_wormhole_b0 and separated out the tests if necessary.  Can this be something we move toward?

**Pull request merged**
