### PR TITLE
#4858: typecast float <-> {uint16, uint32} objects

### PR DESCRIPTION
**Pull request by muthutt**
- support typecast float -> {uint16, uint32} using numeric ladder
- support typecast {uint16, uint32} -> float using numeric ladder
- support for both GS and WHB0

### CODE REVIEW

**Review by TT-billteng — CHANGES_REQUESTED** [review]
UMD

**Review by TT-billteng — APPROVED** [review]

**Review by mywoodstock — APPROVED** [review]

**Review by rtawfik01 — APPROVED** [review]

**Comment by bharane-ab** [comment]
@ttmtrajkovic, could you provide some guidance on typecasting in WHB0? Although WH has functions for typecasting like "float_to_uint16", we are encountering difficulties in utilizing them.

**Comment by bharane-ab** [comment]
Reference document for the issue we are currently facing regarding the use of pre-existing typecast conversion instead of the ladder method in WHB0 : [link](https://docs.google.com/document/d/1Ovj0oF-0el4TJxrGRhtn0kFSWvn4Ymk-GDFEAXs7tmc/edit)

**Comment by umadevimcw** [comment]
@jliangTT We have drafted the issue in the document as we have some screenshots to share. Please find the doc link here https://github.com/tenstorrent-metal/tt-metal/pull/5203#issuecomment-1990661713

**Pull request closed without merging**
