### PR TITLE
#2056: Add support for xlogy op

### PR DESCRIPTION
**Pull request by VirdhatchaniKN**
Please find the xlogy op implementation (developed against version v0.31.0-rc2)
- Pre,post commit test : [link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/5817810714) (passed)
- Schedule build : [link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/5817843064) (passed)
- Post commit models : [link](https://github.com/tenstorrent-metal/tt-metal/actions/runs/5817849964) (passed)

### CODE REVIEW

**Review by tt-aho — CHANGES_REQUESTED** [review]
Can you rebase, and add output_mem_config support to this op?

**Review by muthutt — APPROVED** [review]
LGTM - please address the comments from me and most of the ones by @tt-aho

**Review by muthutt — APPROVED** [review]
LGTM - thanks @VirdhatchaniKN

**Review by tt-aho — APPROVED** [review]
lgtm. minor comment on unnecessary deallocates

**Pull request merged**
