### PR TITLE
#13720 Make reshape-view 0 cost when possible

### PR DESCRIPTION
**Pull request by jvegaTT**
### Ticket
Link to Github Issue
https://github.com/tenstorrent/tt-metal/issues/13720

### Problem description
Want to have reshape have 0 cost when the memory does not actually change

### What's changed
On paper I have proved that for both tile with or without padding and with row major for both interleaved and shared, if the size of the pages does not change then no memory has to be moved in order to perform reshape. We simply perform the metadata changes in these cases without calling any other OPs or kernel functions.

Impact: Sweep pass rate went up by 78% to 86.06%
Average op duration over the 2159 sweeps went up from 17.196 to 0.655 each. A significant performance gain as most use cases have no page change.

### Checklist
- [x] Post commit CI passes https://github.com/tenstorrent/tt-metal/actions/runs/11916104705
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable) https://github.com/tenstorrent/tt-metal/actions/runs/11916099149 Had compile time failure but extremely close to target, all other tests passed
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by ntarafdar — APPROVED** [review]
This is fuckin amazing, good job @jvegaTT

**Comment by JushBJJ** [comment]
Nice job

**Comment by marty1885** [comment]
Lovely! Can't wait for the merge.

**Comment by davorchap** [comment]
Great job Camilo, joining the TM team with a true banger!

**Pull request merged**
