### PR TITLE
Integration of mcw-main/0825 branch 

### PR DESCRIPTION
**Pull request by umadevimcw**
- Holds implementation of following ops,
- logical and, or, not xor, andi, ori, noti and xori 
- Binary pre-scaling implementation for logaddexp, ldexp, and logaddexp2
- isnan, isposinf/isneginf, biasgelu, logit and addalpha
- implementation of *glu*, *geglu*, *reglu*, *swiglu*
- implementation of isfinite

### CODE REVIEW

**Review by tt-rkim — CHANGES_REQUESTED** [review]
Please redo your commit messages.
image

**Review by muthutt — APPROVED** [review]
LGTM

**Review by mywoodstock — APPROVED** [review]

**Review by tt-nshanker — APPROVED** [review]

**Review by arakhmati — APPROVED** [review]

**Review by tt-aho — CHANGES_REQUESTED** [review]

**Review by tt-aho — APPROVED** [review]
lgtm

**Review by tt-rkim — APPROVED** [review]
commits msgs look good. thanks for fixing.

**Pull request merged**
