### PR TITLE
Refactor backward tests

### PR DESCRIPTION
**Pull request by umadevimcw**
- Created a module to generate data and compare results
- compare_results modules calculate all close also since few ops are failing due to small differences across all elements hence use rtol and atol param to pass those tests (e.g div variants, fill, log )

### CODE REVIEW

**Comment by umadevimcw** [comment]
@muthutt and @tt-aho Do we have any HW-specific generic seed value for random data generation? Because while refactoring observed for different seeds yields different pcc value. If we have any generic seed we can use it across all the tests

**Comment by tt-aho** [comment]
We have `function_level_defaults` fixture defined in conftest.py with default seeds

**Comment by umadevimcw** [comment]
Thanks @tt-aho. Will update code accordingly

**Review by muthutt — APPROVED** [review]
LGTM - thanks @umadevimcw

**Pull request merged**
