### PR TITLE
#0: Increase multi-device post-commit and nightly to every 3 and 4 hours respectively to get models more feedback on main

### PR DESCRIPTION
**Pull request by tt-rkim**
…

### CODE REVIEW

**Review by kevinmi-TT — COMMENTED** [review]
Could you comment out these lines for now in `run_frequent_regressions_multi_device.sh`
```
pytest models/demos/ttnn_falcon7b/tests/multi_chip -k test_falcon_attention
pytest models/demos/ttnn_falcon7b/tests/multi_chip -k test_falcon_decoder
pytest models/demos/ttnn_falcon7b/tests/multi_chip -k test_falcon_causallm
```

**Comment by tt-rkim** [comment]
Are you skipping them - or we no longer want them?

**Comment by kevinmiTT11** [comment]
> Are you skipping them - or we no longer want them?

Could we skip them until Joseph is back? might be a minor fix in the ttnn api

**Comment by tt-rkim** [comment]
Yes assigned https://github.com/tenstorrent/tt-metal/issues/7664 to @cfjchu

**Pull request merged**
