### PR TITLE
Fix Llama rope scaling factor, improve accuracy

### LINKED ISSUE #15737: [LLama3] Seqlen 128k for Llama3.2 1B and 3B - Reproduce on reference GPU
For the 2 smallest llama3 models, 1B and 3B, we see bad output when prefill seqlen is very large, i..e > 64K.

We've debug extensively and cannot find a reason why this happens for these 2 small models, when it works fine for 8B up to 70B models.

Our best guess is that due to the small size of these models, long context lengths become very sensitive to accuracy.

## TODO
- Test the reference 1B / 3B model on CPU or GPU, using the same prompt  and look at the output. If the reference is also weak, we can close this issue.  Otherwise we'll revisit this.

### PR DESCRIPTION
**Pull request by yieldthought**
### Ticket
Fixes #15737, improves accuracy.

### Problem description
Meta's reference model incorrectly used a rope scale_factor of 8 for the 1B and 3B models, it should be 32 as fixed after release in a patch to their HF repo that was not reflected in their GitHub.

### What's changed
This applies a fix to our clone of their repo and to our own code. We regenerate all reference outputs and update our accuracy figures, which are now improved.

Performance was degraded on main on 4th December, the updated tables here reflect those performance figures but this patch does not degrade performance itself.

### Checklist
- [x] [Post commit CI passes](https://github.com/tenstorrent/tt-metal/actions/runs/12280926524)
- [x] [Single-card](https://github.com/tenstorrent/tt-metal/actions/runs/12280961800)
- [x] [T3K](https://github.com/tenstorrent/tt-metal/actions/runs/12280975631)

### CODE REVIEW

**Comment by yieldthought** [comment]
Tests pass

**Review by cglagovichTT — APPROVED** [review]
Thanks Mark!

**Comment by mtairum** [comment]
I'm rebasing this locally and testing if it still works. If it passes we can merge 👍

**Review by mtairum — APPROVED** [review]
Rebased ✅ Working locally and updated the perf table.

**Pull request merged**
