### PR TITLE
Enforce all-post-commit passes before merge

### PR DESCRIPTION
**Pull request by blozano-tt**
https://github.com/tenstorrent/tt-metal/actions/runs/11984878432

### CODE REVIEW

**Comment by ttmchiou** [comment]
Could this just not be achieved with merge trains/queues?

**Comment by tt-rkim** [comment]
This would be

This is just a less invasive check for now

**Comment by blozano-tt** [comment]
> Could this just not be achieved with merge trains/queues?

I have no background on merge trains / queues. Should they be on our team's road map?

**Comment by blozano-tt** [comment]
This check will always fail when someone creates a PR, or adds a commit.

They will have to run APC and get it passing. Then come back here, and rerun the failed static check...

Whats worse is people may have to scroll in that list, to see the failed static check.

This might achieve blocking merges without passing APC, but the use model is pretty annoying.

I might just close this. As trusting people to do the right thing + easier workflow might be best.

**Pull request closed without merging**
