### PR TITLE
OPT convs in RN50 to get better device perf

### PR DESCRIPTION
**Pull request by yugaoTT**
### Ticket
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/10277)

### Problem description
WH device perf is low, especially on first layer. new perf at 5500fps (main is 4700)

### What's changed
three OPTs: padding on subblock size, uneven split reader for in0, double buffer in0

### Checklist
- [x] Post commit CI pass https://github.com/tenstorrent/tt-metal/actions/runs/9944145069/job/27471478816

### CODE REVIEW

**Review by boris-drazic — APPROVED** [review]

**Comment by davorchap** [comment]
great!

this is b=16, correct?

**Comment by yugaoTT** [comment]
> great!
> 
> this is b=16, correct?

@davorchap yes, b=16 lofi

**Review by TT-BrianLiu — APPROVED** [review]
Question about the new flags:
- `enable_act_doule_buffer`: Spelling
- `enable_subblock_padding`: Can this not be inferred from the input shapes?

Otherwise, I think code looks good other than the fact that we are adding even more flags to convs. It would be great if we can clean them up and document them at some point.

**Comment by yugaoTT** [comment]
> Question about the new flags:
> 
> * `enable_act_doule_buffer`: Spelling
> * `enable_subblock_padding`: Can this not be inferred from the input shapes?
> 
> Otherwise, I think code looks good other than the fact that we are adding even more flags to convs. It would be great if we can clean them up and document them at some point.

@TT-BrianLiu ya the padding can't be inferred because not all layers share the same benefit, for later layers the perf are worse somehow. We should expose it for later exploration.

**Review by mywoodstock — APPROVED** [review]

**Comment by davorchap** [comment]
> Question about the new flags:
> 
> - `enable_act_doule_buffer`: Spelling
> 
> - `enable_subblock_padding`: Can this not be inferred from the input shapes?
> 
> 
> 
> Otherwise, I think code looks good other than the fact that we are adding even more flags to convs. It would be great if we can clean them up and document them at some point.

Yes!

**Pull request merged**
