### PR TITLE
#7547: Bring tracy fix for ttlib import hang

### PR DESCRIPTION
**Pull request by mo-tenstorrent**

### CODE REVIEW

**Review by tt-rkim — APPROVED** [review]

**Comment by tt-rkim** [comment]
lol how long did this take you to figure out and how did you figure out

**Review by TT-billteng — APPROVED** [review]
wow nice find

**Comment by mo-tenstorrent** [comment]
Lol sweat and tears guys. Getting over the self-doubt phase and accepting tracy is the issue was the hardest part lol.

Luckily running smallest pytest test with `import tt-lib` hung in less than 20-30 attempts.

**Comment by mo-tenstorrent** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/8757262605 post commit
https://github.com/tenstorrent/tt-metal/actions/runs/8757267172/job/24035542456 device perf with only known FPS reg on resnet GS
https://github.com/tenstorrent/tt-metal/actions/runs/8757272898 micro benchmarks

**Pull request merged**
