### PR TITLE
#11187: yolov4 in WH

### PR DESCRIPTION
**Pull request by punithsekar**
This Pr contains yolov4 implementation in WH device.

### CODE REVIEW

**Comment by punithsekar** [comment]
Demo inference for the WH  yolov4 implementation is done.
Please find the results [here](https://docs.google.com/document/d/1Ufhw5TQoItqZDVJ2a1LgOpmHmSmH2u_S_THxBEwnnHc/edit).

**Comment by dvartaniansTT** [comment]
@punithsekar please attach the perf sheet per module as well as for the end to end model for the WH implementation here.

**Review by sankarmanoj-tt — COMMENTED** [review]
I think it would be better to create a separate folder for the tests

**Comment by punithsekar** [comment]
@sankarmanoj-tt, I have kept test file separately. Please take a look on the structure now. 
Should we have the folder name as functional_yolov4 instead of yolov4 in models/experimental?

Please find the perf sheets of individual sub_modules and whole model here:

Downsample1 : [downsample1.csv](https://github.com/user-attachments/files/16443062/downsample1.csv)

Downsample2 : [downsample2.csv](https://github.com/user-attachments/files/16443064/downsample2.csv)

Downsample3 : [downsample3.csv](https://github.com/user-attachments/files/16443067/downsample3.csv)

Downsample4 : [downsample4.csv](https://github.com/user-attachments/files/16443070/downsample4.csv)

Downsample5 : [downsample5.csv](https://github.com/user-attachments/files/16443072/downsample5.csv)

Neck : [neck.csv](https://github.com/user-attachments/files/16443075/neck.csv)

Head : [head.csv](https://github.com/user-attachments/files/16443077/head.csv)

Yolov4 module: [yolov4.csv](https://github.com/user-attachments/files/16443079/yolov4.csv)

Note: Still fallback maxpool is used in the Neck sub_module but it is not listed in perf sheet. And if anyone wants to run the profiler for this PR files please comment loop in the test file which calls sub_modules N-times. 

CC: @dvartaniansTT

**Review by sankarmanoj-tt — APPROVED** [review]

**Comment by punithsekar** [comment]
Passing CI Links:
All post-commit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/10297134215)
Nightly fast dispatch tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/10297148174)

**Review by eyonland — APPROVED** [review]

**Comment by punithsekar** [comment]
Passing CI Links:
All post-commit tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/10344322465)
Nightly fast dispatch tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/10344327790)

**Pull request merged**
