### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by johanna-rock-tt**
Add .bin (fractured, cached weights for multi chip demos) and .png files to .gitignore file.

### CODE REVIEW

**Comment by tt-rkim** [comment]
We use *.png in `docs/` - is this for models?

@arakhmati

**Comment by johanna-rock-tt** [comment]
You're right. Maybe we don't need .png in outside of docs. I had some files after running tracy. But I think the .bin files within the models/demos dataset cache should definitely be in the .gitignore

**Comment by tt-rkim** [comment]
Yep `.bin` is good

Please delete `.png` and we will approve

**Comment by tt-rkim** [comment]
Are we still doing this?

**Pull request merged**
