### PR TITLE
#12935: Refactor sweep_framework file structure and naming

### PR DESCRIPTION
**Pull request by arminaleTT**
### Ticket
#12935 

### Problem description
This is purely a renaming/reorganizing change. No functional changes expected 

### What's changed
- Moved internal files into framework/
- Renamed externally invoked files and updated GitHub Actions + ReadMe
- Updated import paths in sweep files
- Excluded @jdesousa-TT @xanderchin @sjameelTT from `tests/sweep_framework/sweeps` code ownership. Op owners can claim their own subdirectories of tests and we will no longer need to review PRs for new tests going in.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by bbradelTT** [comment]
Why are there so many changes to tests/tt_metal/tt_metal/perf_microbenchmark/old/pcie/test_enqueue_rw_buffer.cpp ? Is there a basing issue?

**Comment by arminaleTT** [comment]
> Why are there so many changes to tests/tt_metal/tt_metal/perf_microbenchmark/old/pcie/test_enqueue_rw_buffer.cpp ? Is there a basing issue?

Yes, sorry! Not sure how that happened. Let me fix that

**Comment by arminaleTT** [comment]
> Why are there so many changes to tests/tt_metal/tt_metal/perf_microbenchmark/old/pcie/test_enqueue_rw_buffer.cpp ? Is there a basing issue?

It was a basing issue. Fixed now

**Review by bbradelTT — APPROVED** [review]

**Review by jdesousa-TT — APPROVED** [review]

**Comment by jdesousa-TT** [comment]
Pls squash some of these commits if you can :)

**Review by xanderchin — COMMENTED** [review]
Please squash history. Maybe 1-3 commits would be sufficient.

**Comment by bbradelTT** [comment]
> Pls squash some of these commits if you can :)

Why not just squash and merge, which puts everything into a single commit in main?

**Comment by arminaleTT** [comment]
I will squash and merge, there's no commit history worth keeping in this PR

**Review by xanderchin — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Review by ttmchiou — APPROVED** [review]

**Pull request merged**
