### PR TITLE
Add microbenchmarks covering SoW (Moreh, TT)

### PR DESCRIPTION
**Pull request by tt-rkim**
@razorback3 @dongjin-na My apologies about closing the previous PR. I believe it was closed when we were doing sanitization last night by default. I am unsure why. I am reopening this for you.

Our team has been unfortunately busy. Sometimes PRs take a while to get approved. I have brought up this issue to the team. I am good with the build changes you have made. I defer to the others for microbenchmark and kernel review.

Let's discuss whether to prioritize reviewing and approving this PR. Moreh has been waiting for a week. @davorchap @mywoodstock @yugaoTT 

---

Microbenchmarks covering SoW between Moreh and TT should be added.

List of microbenchmarks listed in SoW are:

1. Primary compute performance (matrix multiplication, convolution)
2. NOC performance (adjacent, random-to-random)
3. Host <-> device data transfer
4. P2P ethernet bandwidth
5. Allreduce on Galaxy
6. DRAM bandwidth
7. Program launch overhead

This PR covers all microbenchmarks above except 1-convolution, 4, and 5.

Each microbenchmark code has its description at the top of the source code including available input arguments.
Also, we move old microbenchmarks to 'old' directory because they are obsolete and the above microbenchmarks are the superset of them. We do not mind if Metal team remove them.

Below is the sample script that should be added to CI for testing:

```
# 1-a. Primary compute performance - matrix multiplication
./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 11264 --n 3072 --k 768 --bypass-check
./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 11264 --n 768 --k 3072 --bypass-check
#./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 34816 --n 768 --k 52000 --bypass-check # only available for Wormhole due to the chip L1 size
./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 24576 --n 64 --k 1024 --bypass-check
./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 24576 --n 1024 --k 64 --bypass-check
./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 32768 --n 64 --k 512 --bypass-check
./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 32768 --n 512 --k 64 --bypass-check
./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 3328 --n 10240 --k 4096 --bypass-check
./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 3328 --n 4096 --k 10240 --bypass-check
./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 576 --n 4096 --k 41825 --bypass-check
./build/test/tt_metal/perf_microbenchmark/1_compute_mm/test_compute_mm --m 576 --n 41825 --k 4096 --bypass-check

# 2-a. NOC performance - adjacent NOC transfer
./build/test/tt_metal/perf_microbenchmark/2_noc_adjacent/test_noc_adjacent --noc-index 0 --noc-direction 1 --bypass-check
./build/test/tt_metal/perf_microbenchmark/2_noc_adjacent/test_noc_adjacent --noc-index 0 --noc-direction 2 --bypass-check
./build/test/tt_metal/perf_microbenchmark/2_noc_adjacent/test_noc_adjacent --noc-index 1 --noc-direction 0 --bypass-check
./build/test/tt_metal/perf_microbenchmark/2_noc_adjacent/test_noc_adjacent --noc-index 1 --noc-direction 3 --bypass-check

# 2-b. NOC performance - random-to-random transfer
./build/test/tt_metal/perf_microbenchmark/2_noc_rtor/test_noc_rtor --noc-index 0 --bypass-check
./build/test/tt_metal/perf_microbenchmark/2_noc_rtor/test_noc_rtor --noc-index 1 --bypass-check

# 3. Host <-> device data transfer
./build/test/tt_metal/perf_microbenchmark/3_pcie_transfer/test_rw_buffer --bypass-check

# 6. DRAM bandwidth
./build/test/tt_metal/perf_microbenchmark/6_dram_offchip/test_dram_offchip --bypass-check

# 7. Program launch overhead
./build/test/tt_metal/perf_microbenchmark/7_kernel_launch/test_kernel_launch --bypass-check
```

Above sample script has "--bypass-check" option at the end of each command. This is because current Metal implementation cannot meet all the performance criteria to pass the test. The "--bypass-check" option bypasses checking performance criteria fulfillment.

The default way of measuring the performance is using the host-side timer. However, these microbenchmarks have "--use-device-profiler" option which uses device profiler to measure the performance. To give and use the "--use-device-profiler" option, one must build Metal library and test code with "ENABLE_PROFILER=1" flag.

Each microbenchmark provide much more options than explained above. Please see each file for more options.

### CODE REVIEW

**Review by yugaoTT — CHANGES_REQUESTED** [review]

**Review by yugaoTT — APPROVED** [review]

**Comment by dongjin-na** [comment]
Dear @tt-rkim,

I rebased the main branch locally with the latest code and checked that all test codes ran well with the WH_B0 device.
There is one thing to check before force pushing.
I noticed that the `dispatch/test_pgm_dispatch.cpp` and `noc/test_noc_unicast_vs_multicast_to_single_core_latency.cpp` test code was added recently. 
Should I also move these test codes to the old path?

**Comment by tt-rkim** [comment]
@dongjin-na No - please leave those as is

**Comment by dongjin-na** [comment]
> @dongjin-na No - please leave those as is
Okay. Rebased to latest main now.

**Comment by tt-rkim** [comment]
@dongjin-na Could you please supply some more example invocations of all the new benchmarks so we can add them into the CI pipeline?

Furthermore, they should be all working for both GS and WH, correct?

**Comment by dongjin-na** [comment]
@tt-rkim,
> Furthermore, they should be all working for both GS and WH, correct?

As far as I know, this microbenchmark-suite is implemented for WH_B0. But it also works well on GS.

> Could you please supply some more example invocations of all the new benchmarks so we can add them into the CI pipeline?

Sure, I will share some example invocations of all microbenchmarks below.
- For a detailed explanation of the arguments, please refer to the comments in each microbenchmark source code.
- I will share the example of 1_compute_mm soon.


### GS
2_noc_adjacent
```
--noc-index : 0 or 1
--noc-direction : 0 or 1 or 2 or 3
--access-type : 0 or 1

./test_noc_adjacent --cores-r 9 --cores-c 12 --num-tiles 204800 --tiles-per-transfer 1  --noc-index 0  --noc-direction 0 --access-type 0
```

2_noc_rtor
```
--noc-index : 0 or 1
--access-type : 0 or 1

./test_noc_rtor --cores-r 9 --cores-c 12 --num-tiles 204800 --noc-index 0 --access-type 0
```

3_pcie_transfer
```
./test_rw_buffer --buffer-type 0 --transfer-size 536870912
./test_rw_buffer --buffer-type 1 --transfer-size 4194304
```

6_dram_offchip
```
--access-type : 0 or 1
./test_dram_offchip --input-size 536870912 --access-type 0
```

7_kernel_launch
```
--core-groups : one of the integers 1 to 9
./test_kernel_launch  --cores-r 9 --cores-c 12 --core-groups 4
```

### WH_B0

2_noc_adjacent
```
--noc-index : 0 or 1
--noc-direction : 0 or 1 or 2 or 3
--access-type : 0 or 1

./test_noc_adjacent --cores-r 7 --cores-c 8 --num-tiles 204800 --tiles-per-transfer 1  --noc-index 0  --noc-direction 0 --access-type 0
```

2_noc_rtor
```
--noc-index : 0 or 1
--access-type : 0 or 1

./test_noc_rtor --cores-r 7 --cores-c 8 --num-tiles 204800 --noc-index 0 --access-type 0
```

3_pcie_transfer
```
./test_rw_buffer --buffer-type 0 --transfer-size 536870912
./test_rw_buffer --buffer-type 1 --transfer-size 8388608
```

6_dram_offchip
```
--access-type : 0 or 1
./test_dram_offchip --input-size 536870912 --access-type 0
```

7_kernel_launch
```
--core-groups : one of the integers 1 to 7
./test_kernel_launch  --cores-r 7 --cores-c 8 --core-groups 4
```

**Comment by dongjin-na** [comment]
- Added patches to ensure the microbenchmark runs issue-free in the latest main code.
- Updated the sample scripts in the above comment for running on GS and WH_B0.
-- The shape used for matrix multiplication was defined based on 64 Tensix (grid 8x8) in the case of WH_B0.
-- But WH_B0 cloud VM provides nebula_x2, which has 56 Tensix cores (grid 8x7). So, I made two versions for WH_B0.
-- We can use `device.compute_with_storage_grid_size` function in the Python script.

If you have any other questions, please let me know at any time.

**Comment by dongjin-na** [comment]
@tt-rkim, I rebased this branch onto latest main.
How about merging this PR and then continuing further work?

**Review by mywoodstock — APPROVED** [review]

**Pull request merged**
