### PR TITLE
#14001: Rename noc_params -> metal_noc_params

### PR DESCRIPTION
**Pull request by afuller-TT**
### Ticket
#14001 

### Problem description
`noc/noc_parameters.h` is available by both UMD and `tt_metal/hw`.  The files are not interchangeable, but obtaining the correct one relies on the order of include directories.  When the build structure changes, the include paths may change and this results in surprising errors.

### What's changed
Rename the file so we are assured which one we'll receive when we `#include` it.

### Checklist
- [x] Post commit CI passes https://github.com/tenstorrent/tt-metal/actions/runs/11647533783
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by tt-rkim — APPROVED** [review]

**Comment by tt-rkim** [comment]
This is a very unfortunate potential trap...
Thank you King Fuller!

Can you please explain with examples how you found this potential issue, even if it was just glazing over the build with a watchful eye?

Thanks

**Comment by afuller-TT** [comment]
From @tt-rkim:
> Can you please explain with examples how you found this potential issue, even if it was just glazing over the build with a watchful eye?

I was tidying up some CMake files (PR not up yet -- I chose to break this piece out into its own PR), when suddenly the build started failing.  Not with "I couldn't resolve this `#include`" as one would expect if I goofed something up.  Instead it was "I got all my includes, but I have a few undefined references."  The technical term for my situation is: waitwhat?

**Review by blozano-tt — CHANGES_REQUESTED** [review]
My preference would be to delete `noc/noc_parameters.h` from UMD.

noc/noc_parameters.h is the only file that needs to be considered for tt-metal compilation.

**Comment by afuller-TT** [comment]
Closing in favour of the UMD changes that just merged and are being pulled into tt-metal.

**Pull request closed without merging**
