### PR TITLE
#6720: Fix recip

### PR DESCRIPTION
**Pull request by Aswinmcw**
Fix recip forward op

All post commit test : https://github.com/tenstorrent-metal/tt-metal/actions/runs/8522121150

@umadevimcw & @Aswinmcw , I'm asking for this description to include what  @nemanjagrujic  gave in the comments here:

tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_eltwise_recip.py

and sweep test:

tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests_broken/grayskull/pytorch_eltwise_recip_test.yaml

Described in bug for recip: https://github.com/tenstorrent-metal/tt-metal/issues/3561

### CODE REVIEW

**Review by eyonland — COMMENTED** [review]
Why were no tests required to be updated on this PR?

**Comment by Aswinmcw** [comment]
> Why were no tests required to be updated on this PR?

Hi @eyonland , this PR will fix the issue #6720 , there is no need to change any existing test file as it is passing already

**Review by eyonland — CHANGES_REQUESTED** [review]
Do we already have a test (maybe a sweep test?) that is already failing that you can reference in the description before I approve?
If we do not have a test for this, can we please make a unit test?

**Comment by Aswinmcw** [comment]
> Do we already have a test (maybe a sweep test?) that is already failing that you can reference in the description before I approve? If we do not have a test for this, can we please make a unit test?

Hi @eyonland , i have attached the screenshot of the given unit test and csv file of the sweep test, kindly review it
Screenshot 2024-04-09 at 9 10 02 PM
[eltwise_recip_sweep.csv](https://github.com/tenstorrent-metal/tt-metal/files/14920948/eltwise_recip_sweep.csv)

**Review by eyonland — APPROVED** [review]

**Comment by nemanjagrujic** [comment]
Will we have this merged soon?

**Comment by umadevimcw** [comment]
> Will we have this merged soon?

@nemanjagrujic This PR is not merged because handling inf/nan affects performance. If we are okay with performance hit we can Reem to approve the PR.
Please find the comments from Reem below 

` These checks also affect performance, are the users alright with a performance hit? `

**Comment by rtawfik01** [comment]
> > Will we have this merged soon?
> 
> @nemanjagrujic This PR is not merged because handling inf/nan affects performance. If we are okay with performance hit we can Reem to approve the PR. Please find the comments from Reem below
> 
> `These checks also affect performance, are the users alright with a performance hit?`

I'll approve, but just let the downstream users know that it will impact performance if they are measuring performance regressions for these ops

**Review by rtawfik01 — APPROVED** [review]

**Pull request closed without merging**
