### PR TITLE
#4255: Fix `Release` build

### PR DESCRIPTION
**Pull request by vtangTT**
clean post-commit w `Release` config: https://github.com/tenstorrent/tt-metal/actions/runs/8987430566

### CODE REVIEW

**Review by TT-billteng — APPROVED** [review]
Great work!

**Comment by TT-billteng** [comment]
Do we still get noticeable perf benefits in the current state? @vtangTT @pgkeller

**Comment by vtangTT** [comment]
Still need to run the perf tests that Coleman gave me. Doing so today.

**Review by arakhmati — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Comment by vtangTT** [comment]
device perf in `Release`: https://github.com/tenstorrent/tt-metal/actions/runs/8987453667
models perf in `Release`: https://github.com/tenstorrent/tt-metal/actions/runs/8987456170

There was a slight improvement in models perf on `Release` build.

**Comment by tt-rkim** [comment]
I see a couple of pros of switching to release as default and for CI:

- matching what our customers would be using on dev and CI
- higher perf (obviously)
- ever so slightly faster building / smaller artifacts

One con would be:

- our assertion safeguards go away. For example, we could run into seg faults on expected values that are normally checked with `TT_ASSERT`. This would make CI debug harder

Thoughts? @pgkeller @TT-billteng

**Comment by tt-rkim** [comment]
Hope I'm not stating the blatantly obvious here

**Comment by TT-billteng** [comment]
> I see a couple of pros of switching to release as default and for CI:
> 
> * matching what our customers would be using on dev and CI
> * higher perf (obviously)
> * ever so slightly faster building / smaller artifacts
> 
> One con would be:
> 
> * our assertion safeguards go away. For example, we could run into seg faults on expected values that are normally checked with `TT_ASSERT`. This would make CI debug harder
> 
> Thoughts? @pgkeller @TT-billteng

Think we would need a scheduled regression runs with assert/ci build for better coverage

**Comment by pgkeller** [comment]
> > I see a couple of pros of switching to release as default and for CI:
> > 
> > * matching what our customers would be using on dev and CI
> > * higher perf (obviously)
> > * ever so slightly faster building / smaller artifacts
> > 
> > One con would be:
> > 
> > * our assertion safeguards go away. For example, we could run into seg faults on expected values that are normally checked with `TT_ASSERT`. This would make CI debug harder
> > 
> > Thoughts? @pgkeller @TT-billteng
> 
> Think we would need a scheduled regression runs with assert/ci build for better coverage

Perf runs should be release.  In past, I've done release for everything and asserts were just what developers used, but there's a fair argument for enabling asserts in non-perf CI.  I'm open either way

**Comment by pgkeller** [comment]
Have to say, this PR just confirms that our SW is a mess.  Many of these should remain asserts IMHO.  Our error checking methodology was never designed and is basically just broken.  I don't see this getting fixed any time soon, so will approve this to move forward.  Ugh.

**Review by pgkeller — APPROVED** [review]

**Comment by TT-billteng** [comment]
> > I see a couple of pros of switching to release as default and for CI:
> > 
> > * matching what our customers would be using on dev and CI
> > * higher perf (obviously)
> > * ever so slightly faster building / smaller artifacts
> > 
> > One con would be:
> > 
> > * our assertion safeguards go away. For example, we could run into seg faults on expected values that are normally checked with `TT_ASSERT`. This would make CI debug harder
> > 
> > Thoughts? @pgkeller @TT-billteng
> 
> Think we would need a scheduled regression runs with assert/ci build for better coverage

Keyword is scheduled, meaning  every day/week/6 hours

Every action that devs use will use to verify their code + what gets run on each commit will be done with a release build

**Comment by TT-billteng** [comment]
> > > I see a couple of pros of switching to release as default and for CI:
> > > 
> > > * matching what our customers would be using on dev and CI
> > > * higher perf (obviously)
> > > * ever so slightly faster building / smaller artifacts
> > > 
> > > One con would be:
> > > 
> > > * our assertion safeguards go away. For example, we could run into seg faults on expected values that are normally checked with `TT_ASSERT`. This would make CI debug harder
> > > 
> > > Thoughts? @pgkeller @TT-billteng
> > 
> > 
> > Think we would need a scheduled regression runs with assert/ci build for better coverage
> 
> Perf runs should be release. In past, I've done release for everything and asserts were just what developers used, but there's a fair argument for enabling asserts in non-perf CI. I'm open either way

Keyword is scheduled, meaning every day/week/6 hours

Every action that devs use will use to verify their code + what gets run on each commit will be done with a release build

**Pull request merged**
