### PR TITLE
#8967: fix padded shape for ttnn multidevice tensors created via from_torch

### PR DESCRIPTION
**Pull request by sraizada-tt**
multidevice tensors are reshaped to tensor.shape.with_tile_padding()

### CODE REVIEW

**Comment by cfjchu** [comment]
Hey @sraizada-tt, did you run the T3K unit test pipeline and the demos pipeline? I think there were issues last time we tried to remove this so just wanted to make sure that all existing regression tests are still passing.

**Comment by sraizada-tt** [comment]
Running now, thanks!

**Comment by sraizada-tt** [comment]
unit tests pass, but falcon7b demo times out (due to a hang?). We have a workaround for now, will investigate further or close this

**Comment by TT-BrianLiu** [comment]
> unit tests pass, but falcon7b demo times out (due to a hang?). We have a workaround for now, will investigate further or close this

Is this PR being closed or needs further approval?

**Comment by sraizada-tt** [comment]
closing for now

**Pull request closed without merging**
