### PR TITLE
#5044: Add optional output for repeat backward

### PR DESCRIPTION
**Pull request by bharane-ab**
Add optional output tensor support for backward repeat op.
Primary issue : https://github.com/tenstorrent/tt-metal/issues/5044

### CODE REVIEW

**Comment by tt-aho** [comment]
What's the reason for having an `are_required_outputs` argument that makes this a no-op?

**Comment by bharane-ab** [comment]
> What's the reason for having an `are_required_outputs` argument that makes this a no-op?

As we introduced are_required_outputs in the backward ops of addcdiv and and addcmul [PR-link](https://github.com/tenstorrent/tt-metal/pull/8592) so we follow the same infra.

**Comment by tt-aho** [comment]
I see, should this be a vector then for consistency with other bw ops where `are_required_outputs` is a vector?

I'm not familiar with the use case, @dongjin-na would you be able to comment on if it should be vector?

**Comment by dongjin-na** [comment]
> I'm not familiar with the use case, @dongjin-na would you be able to comment on if it should be vector?

Hi @tt-aho, here are the reasons I think using a bool vector is necessary.
I understand that the TT's manner creates an output tensor when std::nullopt is passed.
If correct, we must choose one of two options when a std::nullopt Tensor is passed in the backward operation.
1. Whether to create a tensor according to the TT's manner
2. Or ignore it because the tensor's `requires_grad` is false.

Without a bool vector, we can't tell.
It is not necessary to use vectors. Individual variables or other data structures can also be used. 
But bool vectors are used in many codes.

CC. @eyonland, @seunghwan100.

**Review by eyonland — APPROVED** [review]

**Pull request closed without merging**
