### PR TITLE
Add less and emacs by request

### PR DESCRIPTION
**Pull request by afuller-TT**
### Ticket
#15869 

### Problem description
Users of IRD want some extra tools

### What's changed
Added less
Added emacs
Sorted the list

### CODE REVIEW

**Comment by pgkeller** [comment]
can we also make localdev present by default?

**Comment by tavis-TT** [comment]
@pgkeller thats an IRD change not docker image change.  I can look into that.

**Review by ttmchiou — APPROVED** [review]

**Comment by pgkeller** [comment]
looks like this hasn't merged - how about boost?  that is needed to build syseng tools

**Comment by afuller-TT** [comment]
@pgkeller do you mean `libboost-dev`?  Or a different piece of Boost?

**Pull request merged**
