### PR TITLE
#0: Fix an intermittent launch message transfer error

### PR DESCRIPTION
**Pull request by tt-dma**
Issue here is that the launch.run field could be read as true before the launch.enable_brisc and launch.enable_ncrisc fields.

This fixes the intermittent issues with the DPrint RaiseWait test (passes 500 consecutive iterations, previously would fail within 100)

### CODE REVIEW

**Comment by tt-dma** [comment]
@aliuTT

**Comment by aliuTT** [comment]
@tt-dma can you provide repro instructions for your original issue? I'd like to try another experiment. I've confirmed with Umair, the good news is that I 16 byte aligned should be committed in order so long as the start address is 32-byte aligned. So maybe the proper fix is to 32-byte align this mailbox

**Comment by tt-dma** [comment]
@aliuTT Steps to reproduce original issue:

- Revert change in this PR
- Run `TT_METAL_SLOW_DISPATCH_MODE=1 ./build/test/tt_metal/unit_tests --gtest_filter=*.TestPrintRaiseWait --gtest_repeat=500 --gtest_break_on_failure`

**Comment by tt-dma** [comment]
Going to close this and open a new one, since it's gotten quite messy

**Pull request closed without merging**
