### PR TITLE
#6957: Upload artifacts regardless of the device perf results

### PR DESCRIPTION
**Pull request by mo-tenstorrent**
Generate csv report artifact even if samples/sec are out of bound as long as op reports are generated correctly.

### CODE REVIEW

**Comment by tt-rkim** [comment]
Do you mind doing this for regular models pipeline too?

**Comment by tt-rkim** [comment]
also can you post an example run here

**Comment by mo-tenstorrent** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8511045915 

This is a good example actually. 

First attempt fails on test issue which make `Check Device Perf Report Exist` to fail which causes a skip on artifact gen step. 

Second attempt has a FPS out of bound fail, `Check Device Perf Report Exist` passes and it allows artifact to also be generated.

**Comment by tt-rkim** [comment]
Thanks Mo, looks great

I rebased for you and added a commit for perf models and this is the pipeline: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8523084787

Let's see if it passes. If the changes seem no good, I will revert and we can just merge in your change.

**Review by tt-rkim — APPROVED** [review]

**Comment by mo-tenstorrent** [comment]
Great so model perf behaved as expected. `GS other` test failed and thus no artifacts were generated while `llm grayskull `was just out of bound and artifacts were generated. I am good to merge this, if you are. Unless we should wait for a green device perf CI run. I don't think so though

**Comment by tt-rkim** [comment]
Good w me - pls rebase and merge!

**Pull request merged**
