### PR TITLE
#12919: Cleanup set-2 Unary Backward ops

### LINKED ISSUE #12919: Cleanup set-2 Unary Backward ops
- [x] ExecuteUnaryBackwardFill
- [x] ExecuteUnaryBackwardPow
- [x] ExecuteUnaryBackwardWoFloat (10)
- [x] ExecuteUnaryBackward

### PR DESCRIPTION
**Pull request by VirdhatchaniKN**
Issue : #12919
[CI](https://github.com/tenstorrent/tt-metal/actions/runs/11051099498) :

### CODE REVIEW

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11045821545 - passed

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11047328994 - passed

**Review by Aswinmcw — APPROVED** [review]
LGTM

**Review by bharane-ab — APPROVED** [review]

**Review by eyonland — APPROVED** [review]

**Review by mcw-anasuya — APPROVED** [review]

**Review by mouliraj-mcw — APPROVED** [review]

**Comment by VirdhatchaniKN** [comment]
https://github.com/tenstorrent/tt-metal/actions/runs/11064458628 - passed

**Pull request merged**
