### PR TITLE
#8717: ttnn segformer implementation

### PR DESCRIPTION
**Pull request by saichandax**
This PR contains reference and ttnn implementation of segformer model. 
unit tests branch for the failing convs: [here](https://github.com/tenstorrent/tt-metal/compare/main...harini/segformer_unit_test)

### CODE REVIEW

**Comment by HariniMohan0102** [comment]
The performance sheets of the following submodules are added herewith:

- Attention: [ops_perf_results_attention_2024_06_05_16_16_41.csv](https://github.com/user-attachments/files/15594492/ops_perf_results_attention_2024_06_05_16_16_41.csv)
- Efficient_selfattention: [ops_perf_results_efficient_selfattention_2024_06_05_16_21_06.csv](https://github.com/user-attachments/files/15594506/ops_perf_results_efficient_selfattention_2024_06_05_16_21_06.csv)
- Encoder: [ops_perf_results_encoder_2024_06_05_16_24_05.csv](https://github.com/user-attachments/files/15594523/ops_perf_results_encoder_2024_06_05_16_24_05.csv)
- Layer: [ops_perf_results_layer_2024_06_05_16_28_01.csv](https://github.com/user-attachments/files/15594524/ops_perf_results_layer_2024_06_05_16_28_01.csv)
- Mix_ffn: [ops_perf_results_mix_ffn_2024_06_05_16_30_06.csv](https://github.com/user-attachments/files/15594525/ops_perf_results_mix_ffn_2024_06_05_16_30_06.csv)
- Model: [ops_perf_results_model_2024_06_05_16_32_51.csv](https://github.com/user-attachments/files/15594526/ops_perf_results_model_2024_06_05_16_32_51.csv)
- Overlap_path_embeddings: [ops_perf_results_overlap_path_embeddings_2024_06_05_16_39_04.csv](https://github.com/user-attachments/files/15594528/ops_perf_results_overlap_path_embeddings_2024_06_05_16_39_04.csv)
- Selfoutput:[ops_perf_results_selfoutput_2024_06_05_16_09_57.csv](https://github.com/user-attachments/files/15594532/ops_perf_results_selfoutput_2024_06_05_16_09_57.csv)
- DWconv:[ops_perf_results_DWconv_2024_06_05_16_13_32.csv](https://github.com/user-attachments/files/15594534/ops_perf_results_DWconv_2024_06_05_16_13_32.csv)

**Comment by punithsekar** [comment]
Initially the model, encoder sub-modules PCC ~ 0.96, after adding dtype=bfloat_8, memory_config=L1 and core_grid to the pipeline the PCC dropped to ~0.91. 

Currently, the PCC of encoder and model sub-module ~0.91.

**Comment by punithsekar** [comment]
The Performance sheet of segformer semantic segmentation model: 
[ops_perf_results_semantic_segmentation_2024_06_13_15_41_55.csv](https://github.com/user-attachments/files/15825274/ops_perf_results_semantic_segmentation_2024_06_13_15_41_55.csv)

**Comment by punithsekar** [comment]
Demo Results for segformer semantic segmentation: [Link](https://docs.google.com/document/d/1Kwup2DfiuOfXc_rHyh2c_TZyydgNyw97k_QdNAObjwI/edit)

**Comment by punithsekar** [comment]
Torch interpolate is used in segformer semantic segmentation sub-module.

**Comment by punithsekar** [comment]
-  The PCC of sub-modules are as below:

                SegformerOverlapPatchEmbeddings : Pcc is >0.99 for all test cases
                SegformerEfficientSelfAttention :  Pcc is >0.99 for 7 tests and ~0.98 for one test
                SegformerSelfOutput :   Pcc is >0.99 for all 8 tests
                SegformerAttention : Pcc is >0.99 for 6 tests and ~0.98, ~0.96 for two tests. 
                SegformerDWConv : Pcc is >0.99 for all test cases
                SegformerMixFFN : Pcc is >0.99 for all test cases
                SegformerLayer : Pcc is >0.99 for all test cases
                SegformerEncoder :  Pcc is ~0.89
                SegformerModel : Pcc is ~0.89
                SegformerForImageClassification : Pcc is ~0.94
                SegformerMLP : Pcc is >0.99 for all test cases
                SegformerDecodeHead : Pcc is >0.99 for all test cases
                SegformerForSemanticSegmentation : Pcc is ~0.97

- For Evaluation we have used mIoU and accuracy metrics, The results are as below(Torch output vs ttnn output):

                Sample input 1:
                Mean IoU: 0.7512, Accuracy: 82.88%
                Sample input 2:
                Mean IoU: 0.8823, Accuracy: 98.05%

- Currently the following op is in torch:

  1. Conv as there is no support for kernel>3 and group>1(#8868).
  2. One torch permute is used(#9009 ).
  3. Torch interpolate is used as Ttnn interpolate is not available.

**Review by TT-BrianLiu — APPROVED** [review]

**Review by arakhmati — APPROVED** [review]

**Review by TT-BrianLiu — APPROVED** [review]

**Review by ayerofieiev-tt — APPROVED** [review]

**Review by eyonland — APPROVED** [review]

**Pull request closed without merging**
