### PR TITLE
[Mixtral8x7B] Increase demo max context length to 32k

### PR DESCRIPTION
**Pull request by mtairum**
### Ticket
https://github.com/tenstorrent/tt-metal/issues/10934

### What's changed
Previously the Mixtral8x7B demo with prefill would run for inputs with 128 tokens. We now provide in CI a large input file (A copy of the novel tale of two cities) to enable prefilling up to 16k tokens (and decoding up to 32k).

Summary of changes:
- Mixtral demo with prefill now defaults to input of 16k tokens and decodes 120 tokens.
  - Added new large input (around 130k tokens) of a `tale of two cities` novel. We clip it to 16k tokens for the demo.
- On T3k demo CI pipeline we now run `demo_with_prefill.py` for sequence length of 128 and 16k, hence the timeout increase (was seeing running out of time in some of the tests during bringup). FYI @tt-rkim @ttmchiou @TT-billteng .
- Commented out output token match, due to recent variability issues identified both in Llama3.1-8B and Mixtral. Issue #11850 .
- Updated the README to reflect the above changes.

### Checklist
- [ ] [Post commit CI passes](https://github.com/tenstorrent/tt-metal/actions/runs/10537811469)
- [x] [T3k demo pipeline](https://github.com/tenstorrent/tt-metal/actions/runs/10529824320)

### CODE REVIEW

**Comment by mtairum** [comment]
Demo t3k pipeline passed for just mixtral. Re-running full pipeline here:
[ ] https://github.com/tenstorrent/tt-metal/actions/runs/10537807029

**Comment by yieldthought** [comment]
> Demo t3k pipeline passed for just mixtral. Re-running full pipeline here:
> 
> * [ ]  https://github.com/tenstorrent/tt-metal/actions/runs/10537807029

```
TypeError: cache_attention() takes 6 positional arguments but 8 were given
```

Will investigate

**Comment by tt-rkim** [comment]
@yieldthought 
thank you

**Review by uaydonat — APPROVED** [review]

**Comment by uaydonat** [comment]
Does it makes sense to add a test with input prompt size: 16384+100 (or similar) such that we test prefill + prefill_as_decode together? Do we have such a test already?

**Review by TT-billteng — APPROVED** [review]

**Comment by mtairum** [comment]
> TypeError: cache_attention() takes 6 positional arguments but 8 were given

I fixed that one and re-running pipeline. Should pass now.
- [ ] [New t3k demo pipeline](https://github.com/tenstorrent/tt-metal/actions/runs/10576117952)

**Pull request merged**
