### PR TITLE
#978 : eltwise composite ops for TT Metal Operators

### PR DESCRIPTION
**Pull request by muthutt**
[Composite Ops] composite ops for TT Metal Operators

composite ops:
1.   silu
2.  neg
3.  add1
4.  log1p
5.  softplus
6.  mish
7.  square
8.  selu
9.  swish
10. clip
11. hard_sigmoid
12. hard_swish
13. min
14. max
15. relu_max
16. relu_min
17. sin
18. cos
19. polyval
20. Mac
21. power = y = x^(const exponent)

Compare ops

1.    - LTZ ( < 0 )
2.    - GTZ ( > 0 )
3.    - EQZ ( = 0 )
4.    - NEZ (!= 0)
5.    - LEZ (<= 0)
6.    - GEZ (>=0)

### CODE REVIEW

**Review by tt-aho — CHANGES_REQUESTED** [review]

**Review by tt-aho — CHANGES_REQUESTED** [review]

**Review by tt-rkim — CHANGES_REQUESTED** [review]
I'm conditioning my approval on a couple things:

- Resolution of my comments
- Passing scheduled all
- Discussion with @tt-aho / @TT-BrianLiu on these changes
- Approval by one or both of the above (preferably both)
- KM's review on SFPU GS changes
- Create an issue to address adding coverage for WH for ops sweeps

I'd also recommend review from @arakhmati , for at least the libs/ part.

**Review by tt-aho — CHANGES_REQUESTED** [review]

**Review by tt-aho — CHANGES_REQUESTED** [review]

**Review by tt-rkim — DISMISSED** [review]
Needs to
- pass post commit
- approved by FW owners
- pass Austin's review

**Review by arakhmati — DISMISSED** [review]

**Review by tt-aho — CHANGES_REQUESTED** [review]

**Review by kkwong10 — DISMISSED** [review]

**Review by tt-aho — COMMENTED** [review]
Run black on touched python files

**Review by tt-aho — APPROVED** [review]
Looks good to me, just remove the merge commit before merge to main

**Review by DrJessop — APPROVED** [review]

**Review by kkwong10 — APPROVED** [review]

**Pull request merged**
