### PR TITLE
Llama2 functional bringup

### PR DESCRIPTION
**Pull request by cglagovich**
Issue for PR: #5151 

Llama2 functionality on 4-chip is ready for merge. 

`llama2_70b/tt` contains all model code specific to TT.
`llama2_70b/reference` contains a few reference files from [Meta's Llama repo](https://github.com/facebookresearch/llama). Reviewers, please advise on how to license these files.
`llama2_70b/tests` contains all relevant tests. We plan on integrating a few of these into CI.

@arakhmati I know we enforce a linear history. This branch contains merge commits. Should we squash into one commit for the rebase?

post-commit pipeline: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8176287563

### CODE REVIEW

**Review by arakhmati — APPROVED** [review]

**Comment by arakhmati** [comment]
> Issue for PR: #5151
> 
> Llama2 functionality on 4-chip is ready for merge.
> 
> `llama2_70b/tt` contains all model code specific to TT. `llama2_70b/reference` contains a few reference files from [Meta's Llama repo](https://github.com/facebookresearch/llama). Reviewers, please advise on how to license these files. `llama2_70b/tests` contains all relevant tests. We plan on integrating a few of these into CI.
> 
> @arakhmati I know we enforce a linear history. This branch contains merge commits. Should we squash into one commit for the rebase?
> 
> post-commit pipeline: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8176287563

@cglagovich if each commit is okay on its own and runs without breaking anything, then it's okay to keep multiple commits. Otherwise, please squash them

**Comment by tt-rkim** [comment]
@warthog9 has sent this off to vOSPO for more comment

We'll unfortunately have to hold off on merging until then @cglagovich

**Comment by cglagovich** [comment]
Okay @tt-rkim I'll hold off. I'll see if I can get a timeline for vOSPO comment

**Review by davorchap — APPROVED** [review]

**Comment by davorchap** [comment]
> Okay @tt-rkim I'll hold off. I'll see if I can get a timeline for vOSPO comment

Can the model demo use llama2 meta reference code as git sub module ?

**Comment by davorchap** [comment]
> @warthog9 has sent this off to vOSPO for more comment
> 
> 
> 
> We'll unfortunately have to hold off on merging until then @cglagovich 

Having models that have low risk of breaking infra sit for 2+ days on branches just adds to to retest ,rebase, API change loop

Why can't we merge this , have it in CI (ie 1 decoder) , and then resolve open issues?
Let's merge and File a case.

**Review by tt-rkim — APPROVED** [review]

**Comment by tt-rkim** [comment]
@davorchap 

I'm good with these changes. I've been good with them for a while.

I have nothing to block @cglagovich . Us two + @warthog9 had a call yesterday and we have a plan to add a forked version of meta llama as a submodule. @warthog9 is good with the plan to merge with a forked submodule version of llama. You can ask him any questions about it directly.

The CI point is diff discussion. @cglagovich let us know if you'd like to put anything into 2x4 X2 CI. Maybe a part of it (like @davorchap suggested 1 decoder) would be good.

**Comment by cglagovich** [comment]
@tt-rkim Once these changes are merged in, we should talk about adding to CI. We'll have to figure out where to put model weights and whatnot

**Comment by tt-rkim** [comment]
Sounds good, we have some ideas + would like some feedback on potential alternatives we'd like to move to the future.

Let's open an issue to take up llama CI after we merge?

**Comment by cglagovichTT** [comment]
Please take one last look. I moved Llama reference code to submodule.

Please also confirm that you want all of these commits in the git history, not squashed.

**Pull request merged**
