### PR TITLE
[Mistral-7B] Add flags for weight paths

### PR DESCRIPTION
**Pull request by mtairum**
- Added a flag system for choosing the weights path, similar to Mixtral8x7b and Llama2/3.
- Updated Mistral-7B readme with the new run instructions.
- Updated all relevant Mistral-7B tests.
- Added an optional `get_mistral_weights.py` script to download the weights, for ease of use. In case of Mistral we are not using HuggingFace weights but instead the Mistral-AI weights (shared in a tarfile).

### CODE REVIEW

**Review by yieldthought — APPROVED** [review]

**Comment by mtairum** [comment]
All Mistral tests passing:

https://github.com/tenstorrent/tt-metal/actions/runs/9399604362
https://github.com/tenstorrent/tt-metal/actions/runs/9399605738
https://github.com/tenstorrent/tt-metal/actions/runs/9399606701

**Comment by tt-rkim** [comment]
Please review
@dvartaniansTT @mbahnasTT 

This was all in response to your feedback.

**Review by dvartaniansTT — COMMENTED** [review]
Inspecting all the changes visually LGTM. Thanks a lot @mtairum & @tt-rkim . I will re-test the demo once our lab machines are back up and running.

**Review by dvartaniansTT — APPROVED** [review]
tested on N150 and passed. approved! thanks for the prompt great work! @mtairum

**Review by tt-rkim — APPROVED** [review]

**Pull request merged**
