### PR TITLE
simpler hugepage check

### PR DESCRIPTION
**Pull request by TT-billteng**
Python hugepages script was erroring out despite hugepages being setup correctly on IRD machines. This bash command replacement *should* be a good enough check

### CODE REVIEW

**Review by abhullar-tt — APPROVED** [review]

**Comment by tt-rkim** [comment]
@TT-billteng should we just let this in?
Right now, the specification is

GS: 1 HP
WH: 1 HP per mmio (pcie)

**Comment by TT-billteng** [comment]
> @TT-billteng should we just let this in? Right now, the specification is
> 
> GS: 1 HP WH: 1 HP per mmio (pcie)

Do you mean I should make the check more specific?

**Comment by tt-rkim** [comment]
Perhaps - right now it's just not equal to 0

For our current spec, this will always be right for GS.

For WH, not so much. @abhullar-tt might as well just check manually or with the script to see what the correct number should be. Because if it's just 1 hugepage on a multi WH system, this will pass but that's technically wrong, and something will fail down the line.

I'm wondering if we should actually make this check completely optional, and then put better messages in code / UMD.

**Comment by TT-billteng** [comment]
Once we get Olof's package, I assume the number of hugepages would be set correctly. This check could be a way to just check if something has been set ( and if it is, assume it's correct )

**Comment by tt-rkim** [comment]
If that's the goal then sure , I'm fine with that
Also for "Olof's package", we need to make sure we can give input on that. Blindly 4 pages per MMIO will hang our stuff

**Review by tt-rkim — APPROVED** [review]

**Comment by tt-rkim** [comment]
@TT-billteng just rebased it for you and approved
@abhullar-tt Just note that the build will no longer ensure 2 x # of mmios

**Comment by abhullar-tt** [comment]
> If that's the goal then sure , I'm fine with that Also for "Olof's package", we need to make sure we can give input on that. Blindly 4 pages per MMIO will hang our stuff

4 pages per MMIO hanging out stuff -> was that the OOM issues that model pipelines were seeing?

**Pull request merged**
