### PR TITLE
#8943: Clean up profiler python_env build flow

### PR DESCRIPTION
**Pull request by vtangTT**
https://github.com/tenstorrent/tt-metal/actions/runs/9290285817

### CODE REVIEW

**Comment by mo-tenstorrent** [comment]
Could you run the following CIs on top of post commit:

T3K: https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-profiler-tests.yaml
Device perf: https://github.com/tenstorrent/tt-metal/actions/workflows/perf-device-models.yaml
uBenchmark: https://github.com/tenstorrent/tt-metal/actions/workflows/metal-run-microbenchmarks.yaml

Thanks

**Comment by tt-rkim** [comment]
will approve once pass

**Comment by vtangTT** [comment]
@mo-tenstorrent @tt-rkim 
t3k profiler: https://github.com/tenstorrent/tt-metal/actions/runs/9292833396
device perf: https://github.com/tenstorrent/tt-metal/actions/runs/9292833854
uBenchmarks: https://github.com/tenstorrent/tt-metal/actions/runs/9291691586

**Review by mo-tenstorrent — APPROVED** [review]
Thanks

**Review by tt-rkim — APPROVED** [review]

**Comment by vtangTT** [comment]
clean post-commit: https://github.com/tenstorrent/tt-metal/actions/runs/9307826923

**Pull request merged**
