### PR TITLE
update threshold times to be consistent with other tests

### PR DESCRIPTION
**Pull request by ntarafdar**
Updated threshold in test_perf_resnet, forgot to do it in test_perf_accuracy_resnet

### CODE REVIEW

**Comment by tt-rkim** [comment]
I think you'll need to update 16 batch as well?

**Comment by tt-rkim** [comment]
mm actually wait one sec

**Comment by tarafdarTT** [comment]
> I think you'll need to update 16 batch as well?

batch 16 was untouched in my prev PR

**Comment by tt-rkim** [comment]
KK

**Review by TT-billteng — APPROVED** [review]

**Review by boris-drazic — APPROVED** [review]

**Review by tt-rkim — APPROVED** [review]

**Comment by tt-rkim** [comment]
Why is this not yet merged? Did I miss a new development? @TT-billteng @tarafdarTT

**Comment by tarafdarTT** [comment]
> Why is this not yet merged? Did I miss a new development? @TT-billteng @tarafdarTT

sorry its merged now

**Pull request merged**
