### PR TITLE
Auto-download weights of yolov4

### PR DESCRIPTION
**Pull request by punithsekar**
### Problem description
Auto download weights of yolov4 if it's not available.

### What's changed
Added `yolov4_weights_download.sh` file, This file will check if gdown is available or it will download gdown package and then download yolov4.pth from google drive.

```
if model_path == "models":
        if not os.path.exists("tests/ttnn/integration_tests/yolov4/yolov4.pth"):  # check if yolov4.th is availble
            os.system(
                "tests/ttnn/integration_tests/yolov4/yolov4_weights_download.sh"
            )  # execute the yolov4_weights_download.sh file

        weights_pth = "tests/ttnn/integration_tests/yolov4/yolov4.pth"
```
The model_path will contain the path to the weights file if weka is available or it will contain "models" as its the model_version which is passed to model_location_generator API. 

If weka path is not available,  We initially check if yolov4.th is available in the path `tests/ttnn/integration_tests/yolov4/yolov4.pth`,  If not available we execute the `yolov4_weights_download.sh` file which downloads the yolov4.pth file.

Note: The feature is given only while running the model from pwd `/home/ubuntu/tt-metal/`. It will not work if we are inside some other folder inside tt-metal repo.

### Checklist
- [x] Post commit CI passes

### CODE REVIEW

**Review by dvartaniansTT — CHANGES_REQUESTED** [review]
@punithsekar I am getting an error trying to run the demo. see the attached pls: 
Screenshot 2024-10-11 at 11 10 23 AM

**Comment by punithsekar** [comment]
Hi @dvartaniansTT ,
The Fix for demo issue is available in pr #13528.

**Comment by punithsekar** [comment]
CI tests in progress - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/11302133984).

**Comment by punithsekar** [comment]
CI tests Links
All post commits tests - [Link](https://github.com/tenstorrent/tt-metal/actions/runs/11302133984). - All passed
Nightly fast dispatch tests- https://github.com/tenstorrent/tt-metal/actions/runs/11302189354 - Some are failing  but not due to this PR.

**Review by dvartaniansTT — APPROVED** [review]
LGTM

**Comment by punithsekar** [comment]
Current CI pipelines, in progress,
All post commits tests - https://github.com/tenstorrent/tt-metal/actions/runs/11331237165
Nightly fast dispatch tests - https://github.com/tenstorrent/tt-metal/actions/runs/11331246730

**Review by TT-BrianLiu — APPROVED** [review]

**Pull request merged**
