### PR TITLE
#6183: Skip SD matmul tests on GS

### PR DESCRIPTION
**Pull request by mtatsumiTT**
- skip the unit-test for SD matmul ops on GS (fix the pipeline: https://github.com/tenstorrent-metal/tt-metal/actions/runs/8238397737/job/22529345314)

### CODE REVIEW

**Review by eyonland — CHANGES_REQUESTED** [review]
I think we need a clear reason for why we are skipping tests on grayskull.  Also, there is no issue number for this request.

**Comment by mtatsumiTT** [comment]
We need the test for matmul perf investigation targeting B0, so I believe it is ok to skip it on GS for now. I'm pushing that to patch the pipeline broken by my previous commit (correlated to #6183), in that case should I keep using the issue ID for original commit? I saw that some commits about bugfix in main also use #0 so I just used it following that.

**Review by arakhmati — APPROVED** [review]
Approving it because the pipelines are failing but please enable the tests on GS (at least the ones that can work on GS)

And please either use the original issue number or create a new issue next time

**Comment by mtatsumiTT** [comment]
sorry, I'll follow that next time. For now, I'll merge it with all GS disabled (with ID #6183) and open another issue for enabling the same test for GS as well.

**Comment by mtatsumiTT** [comment]
@eyonland could you re-review the latest change?

**Review by arakhmati — APPROVED** [review]

**Pull request closed without merging**
