### PR TITLE
#0: ported interleaved ccls to sharded version

### PR DESCRIPTION
**Pull request by kpaigwar**
### Ticket
Link to Github Issue

### Problem description
Provide context for the problem.

### What's changed
Describe the approach used to solve the problem.
Summarize the changes made and its impact.

### Checklist
- [ ] Post commit CI passes
- [ ] Blackhole Post commit (if applicable)
- [ ] Model regression CI testing passes (if applicable)
- [ ] Device performance regression CI testing passes (if applicable)
- [ ] New/Existing tests provide coverage for changes

### CODE REVIEW

**Review by yieldthought — APPROVED** [review]
Looks good, does it work for 1b, 3b, 8b on all models?

**Comment by kpaigwar** [comment]
> Looks good, does it work for 1b, 3b, 8b on all models?

Checked for 8b, running now for all

**Comment by sraizada-tt** [comment]
> Let me know when this is done and ready for review. Don't forget to run all pipelines related to llama3 - including single card FD nightly.

It's not merging to main

**Comment by mtairum** [comment]
@tt-rkim This is PR for a branch, not main, so it won't be needing any tests for now.

I'm currently finishing off a mega PR that this will eventually feed on.

**Review by uaydonat — APPROVED** [review]

**Pull request merged**
