### PR TITLE
#1681: Added the SFPU implementation of signbit op

### PR DESCRIPTION
**Pull request by bharane-ab**
Please find the implementation of signbit op.

- we have updated the docs
- we ran the CI test as well

### CODE REVIEW

**Review by muthutt — APPROVED** [review]
is this the expectation of the operator ? https://en.cppreference.com/w/c/numeric/math/signbit 

we should expect input in form of bfloat16 and use (1,8,7) format and read the sign bit.

for example using the **Conversion** union and read the float value as uint and check out the final bit 1; return it.

We should not be using the if-elseif-else and floating point compare ops

Update test to check compare_equal

**Review by muthutt — CHANGES_REQUESTED** [review]
request changes as per my review comments

**Review by tt-aho — CHANGES_REQUESTED** [review]

**Review by muthutt — APPROVED** [review]
LGTM - just move doc into experimental section if its not already done; thank you @bharane-ab

**Review by tt-aho — APPROVED** [review]
Approving so you don't have to wait for my approval after but please move signbit to experimental ops section

**Review by mywoodstock — APPROVED** [review]

**Review by tt-nshanker — APPROVED** [review]

**Review by muthutt — APPROVED** [review]
LGTM

can you also generate a plot of this data ?

**Pull request merged**
