### PR TITLE
#12690: Port moreh_softmax and moreh_softmax_backward to ttnn

### PR DESCRIPTION
**Pull request by thanhnguyen1512**
### Ticket
Link to Github Issue: https://github.com/tenstorrent/tt-metal/issues/12690

### Problem description
moreh_softmax and moreh_softmax_backward were deprecated alongside tt_dnn. This PR ports it to ttnn using its operation format.

### What's changed
Move device code to ttnn
Create new wrapper code for ttnn with new modules

### Checklist
- [x] Post commit CI passes
+ [All post-commit tests #15741](https://github.com/tenstorrent/tt-metal/actions/runs/10882420674)
+ [All post-commit tests #15807](https://github.com/tenstorrent/tt-metal/actions/runs/10897300347)
+ [All post-commit tests #15824](https://github.com/tenstorrent/tt-metal/actions/runs/10901204393)
+ [All post-commit tests #16322](https://github.com/tenstorrent/tt-metal/actions/runs/10997283128)

- [x] Blackhole Post commit (if applicable) - NA
- [x] Model regression CI testing passes (if applicable) - NA
- [x] New/Existing tests provide coverage for changes

### CODE REVIEW

**Comment by o2buzzle** [comment]
Please run `clang-format` on the modified code if you can

**Comment by mrshaw01** [comment]
Some changes I made to your branch:
- Refactored `test_*.py`
- Moved changes from `tt-metal/ttnn/ttnn/types.py` to `ttnn/ttnn/operations/moreh.py`

**Comment by mrshaw01** [comment]
Some changes I made to your branch (P2) (on the forward phase):

- Defined a macro to shorten the script (reducing many repetitive definitions)
- Removed unnecessary includes
- Checked naming conventions
- Checked type declarations
- Handled ambiguous `std::optional`
- Resolved unnecessary `init_device_compute_kernel_config`

Details: [GitHub link](https://github.com/tenstorrent/tt-metal/compare/3a7e84927d5c75239288d40502b5873c60c9207d..1469f4c4ca4026aa4f2c0b085548dc21765be04c)

**Comment by mrshaw01** [comment]
Some changes I made to your branch (P3) (on the backward phase):

- Defined a macro to shorten the script (reducing many repetitive definitions)
- Removed unnecessary includes
- Checked naming conventions
- Checked type declarations
- Handled ambiguous `std::optional`
- Resolved unnecessary `init_device_compute_kernel_config`

Details: [GitHub link](https://github.com/tenstorrent/tt-metal/compare/1469f4c4ca4026aa4f2c0b085548dc21765be04c..908579d962b71c85aa08ae9fb187eaa8e5a91675)

**Review by mrshaw01 — APPROVED** [review]
The revision phase is done; please review!

**Review by razorback3 — APPROVED** [review]

**Review by ayerofieiev-tt — APPROVED** [review]

**Pull request merged**
