### PR TITLE
#5048: Add CreateDevices and CloseDevices api to detail

### PR DESCRIPTION
**Pull request by aliuTT**

### CODE REVIEW

**Comment by aliuTT** [comment]
I think we really need a cluster handle to manage all this, but for now this should unblock checking in Falcon40B to main. I'm returning a map of all devices that are reserved based on user provided list.

**Review by TT-billteng — APPROVED** [review]

**Review by abhullar-tt — APPROVED** [review]
I think you already did it but if not can you open an issue to track the device cluster proposals

**Comment by aliuTT** [comment]
fyi @tt-aho

**Comment by aliuTT** [comment]
This one? https://github.com/tenstorrent-metal/tt-metal/issues/5048 I'll update it to comment about this PR

**Pull request merged**
