### PR TITLE
#6503: Llama 2 Refactor All Test files, allow repro on any device

### PR DESCRIPTION
**Pull request by kevin-mii**
1. Added three environment variables, need to set before running llama test code
Example path:
```
export LLAMA_CKPT_DIR="/proj_sw/user_dev/llama-data-repacked-2/llama-2-70b/"
export LLAMA_TOKENIZER_PATH="/proj_sw/user_dev/llama-data/tokenizer.model"
export LLAMA_CACHE_PATH="/proj_sw/user_dev/llama-data-cache/weights-cache"
```
2. Refactor all test files to have intuitive parameters for testing.
3. Added `models/demos/llama2_70b/scripts/llama_test_suite.sh`, to run all tests
4. Combined test_galaxy with current unit tests

### CODE REVIEW

**Comment by mikevin920** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8330877510

**Review by cglagovich — APPROVED** [review]
Nice refactor

**Comment by mikevin920** [comment]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8334392985

**Comment by mikevin920** [comment]
Ran llama_test_suite_8chip.sh & llama_test_suite_emulated, and demo.py, all test passed

**Review by eyonland — APPROVED** [review]

**Comment by cglagovich** [comment]
Testing multi-device action https://github.com/tenstorrent-metal/tt-metal/actions/runs/8343887974

**Pull request merged**
