### PR TITLE
#8260: reshard uneven shard

### PR DESCRIPTION
**Pull request by ntarafdar**

### CODE REVIEW

**Review by arakhmati — APPROVED** [review]

**Review by boris-drazic — APPROVED** [review]

**Review by shwetankTT — APPROVED** [review]

**Comment by shwetankTT** [comment]
@tarafdarTT Please merge this PR.

**Comment by tarafdarTT** [comment]
hey @shwetankTT sorry about that I'll merge it in today/tomorrow. Was working on something else but will work on this now.

**Comment by tarafdarTT** [comment]
@shwetankTT will merge as soon as pipelines pass: https://github.com/tenstorrent/tt-metal/actions/runs/9084985373

**Comment by davorchap** [comment]
@tarafdarTT this was reverted? 

It is blocking https://github.com/tenstorrent/tt-metal/issues/8131

**Pull request merged**
