### PR TITLE
#0: Fix scatter op

### PR DESCRIPTION
**Pull request by VirdhatchaniKN**
The implemented scatter operation from [PR](https://github.com/tenstorrent-metal/tt-metal/pull/3787) does not work as expected if the src tensor has 0 in it

This change will fix the issue

### CODE REVIEW

**Review by tt-aho — APPROVED** [review]
lgtm. So just for my understanding, this op is basically just slice assignment, and not exactly equivalent to torch scatter right?

**Review by muthutt — CHANGES_REQUESTED** [review]
@umadevimcw - thanks for identifying the bug; please resolve the comments

**Review by muthutt — CHANGES_REQUESTED** [review]
Please address comments @VirdhatchaniKN - tagged Uma accidentally

**Review by tt-aho — APPROVED** [review]

**Review by muthutt — APPROVED** [review]
LGTM

**Pull request merged**
